import {
  type EmbodiedPipelineStage,
  type EventDataProfile,
  EventDataProfileSchema,
} from "../../domain/embodied-data.js";

export interface EmbodiedLaunchEventSeed {
  slug: string;
  title: string;
  fact: string;
  interpretation: string;
  futureWatch: string;
  recommendedAction: string;
  category: string;
  company: string;
  keywords: readonly string[];
  date: string;
  contentScope: "embodied-data";
  tracks: readonly EmbodiedPipelineStage[];
  actors: readonly string[];
  dataProfile: EventDataProfile;
  evidenceSlugs: readonly string[];
}

type ProfileInput = Partial<
  Pick<
    EventDataProfile,
    | "scenarios"
    | "embodiments"
    | "tasks"
    | "modalities"
    | "acquisitionMethods"
    | "dataFormats"
    | "standards"
    | "qualityMetrics"
    | "deliveryImpact"
  >
>;

const profile = (stage: EmbodiedPipelineStage, input: ProfileInput = {}): EventDataProfile =>
  EventDataProfileSchema.parse({
    pipelineStages: [stage],
    scenarios: input.scenarios ?? ["robot data production"],
    embodiments: input.embodiments ?? ["single-arm"],
    tasks: input.tasks ?? ["manipulation"],
    modalities: input.modalities ?? ["rgb", "joint-state", "action", "language"],
    acquisitionMethods: input.acquisitionMethods ?? ["teleoperation"],
    dataFormats: input.dataFormats ?? [],
    standards: input.standards ?? [],
    scaleClaims: [],
    qualityMetrics: input.qualityMetrics ?? ["task success and replay validity"],
    costSignals: [],
    deliveryImpact:
      input.deliveryImpact ?? "为具身数据项目提供可复用的生产边界、验证方法与交付判断依据。",
    evidenceStatus: "verified",
  });

const launchEvent = (
  value: Omit<EmbodiedLaunchEventSeed, "contentScope">,
): EmbodiedLaunchEventSeed => ({ ...value, contentScope: "embodied-data" });

export const embodiedLaunchEvents: EmbodiedLaunchEventSeed[] = [
  launchEvent({
    slug: "behavior-1k-task-definition",
    title: "BEHAVIOR-1K 把家庭活动拆成可执行任务定义",
    fact: "BEHAVIOR-1K 发布家庭活动任务与仿真基准，并公开任务定义和评测环境。",
    interpretation: "数据团队可以先用任务、对象和终止条件约束需求，再决定采集哪些示范。",
    futureWatch: "观察真实机器人复现、任务覆盖扩展与失败定义是否保持一致。",
    recommendedAction: "把任务定义、成功条件和异常样本要求写入采集验收单。",
    category: "benchmark",
    company: "Stanford Vision and Learning Lab",
    keywords: ["任务定义", "家庭活动", "仿真", "验收"],
    date: "2024-02-29T00:00:00.000Z",
    tracks: ["demand-definition"],
    actors: [],
    dataProfile: profile("demand-definition", {
      scenarios: ["household activities"],
      embodiments: ["mobile-manipulator"],
      acquisitionMethods: ["simulation"],
    }),
    evidenceSlugs: ["behavior-1k-project"],
  }),
  launchEvent({
    slug: "libero-lifelong-task-suites",
    title: "LIBERO 用任务套件检验持续学习的数据组织",
    fact: "LIBERO 发布面向终身机器人学习的任务套件、数据和统一评测代码。",
    interpretation: "任务分组与顺序成为衡量数据是否支持知识迁移和抗遗忘的共同接口。",
    futureWatch: "观察真实场景任务是否沿用同一评测边界，以及任务泄漏如何控制。",
    recommendedAction: "按技能、对象、空间关系和长程依赖重组内部黄金任务集。",
    category: "benchmark",
    company: "Lifelong Robot Learning Lab",
    keywords: ["任务套件", "终身学习", "知识迁移", "评测"],
    date: "2023-06-06T00:00:00.000Z",
    tracks: ["demand-definition"],
    actors: [],
    dataProfile: profile("demand-definition", { scenarios: ["tabletop manipulation"] }),
    evidenceSlugs: ["libero-project"],
  }),
  launchEvent({
    slug: "calvin-long-horizon-language-benchmark",
    title: "CALVIN 将长程语言任务纳入连续评测",
    fact: "CALVIN 开源语言条件下的长程机器人操作基准与训练环境。",
    interpretation: "连续完成任务链比孤立动作成功率更接近数据交付的真实验收边界。",
    futureWatch: "观察任务链长度、恢复能力与跨环境复现是否形成稳定指标。",
    recommendedAction: "为关键交付场景增加连续任务、恢复与重试验收用例。",
    category: "benchmark",
    company: "CALVIN Project",
    keywords: ["长程任务", "语言条件", "连续评测", "恢复"],
    date: "2022-06-15T00:00:00.000Z",
    tracks: ["demand-definition"],
    actors: [],
    dataProfile: profile("demand-definition", {
      scenarios: ["tabletop long-horizon tasks"],
      acquisitionMethods: ["simulation", "teleoperation"],
    }),
    evidenceSlugs: ["calvin-project"],
  }),
  launchEvent({
    slug: "rt1-data-driven-robotics",
    title: "RT-1 证明任务与机器人数据可以统一建模",
    fact: "Google Robotics 发布 RT-1，并公开以多任务机器人数据训练统一策略的研究。",
    interpretation: "需求定义开始从单技能脚本转向可共享的任务语义和动作表示。",
    futureWatch: "观察不同本体和现场条件下的任务语义是否仍可复用。",
    recommendedAction: "优先统一任务标签、动作语义和失败原因，而不是只扩充视频数量。",
    category: "research",
    company: "Google DeepMind",
    keywords: ["多任务", "任务语义", "动作表示", "机器人策略"],
    date: "2022-12-13T00:00:00.000Z",
    tracks: ["demand-definition"],
    actors: [],
    dataProfile: profile("demand-definition", { scenarios: ["everyday manipulation"] }),
    evidenceSlugs: ["rt1-paper"],
  }),
  launchEvent({
    slug: "ubtech-industrial-task-program",
    title: "优必选把工业场景任务作为人形数据入口",
    fact: "优必选公开以工业制造场景推进人形机器人训练与应用验证的产品路线。",
    interpretation: "场景订单可以反向约束任务清单、工位安全和数据验收，而不是从通用动作出发。",
    futureWatch: "观察公开案例是否给出持续运行、接管和任务成功的可核验证据。",
    recommendedAction: "按工位建立任务树，并为每个任务记录安全边界与人工接管条件。",
    category: "industry",
    company: "UBTECH Robotics",
    keywords: ["工业场景", "任务树", "人形机器人", "验收"],
    date: "2024-07-01T00:00:00.000Z",
    tracks: ["demand-definition"],
    actors: [],
    dataProfile: profile("demand-definition", {
      scenarios: ["industrial manufacturing"],
      embodiments: ["humanoid"],
      tasks: ["loco-manipulation"],
    }),
    evidenceSlugs: ["ubtech-industrial-source"],
  }),
  launchEvent({
    slug: "nexdata-embodied-delivery-scope",
    title: "具身数据服务开始按场景与模态定义交付",
    fact: "Nexdata 与同类服务商公开面向具身智能的数据采集、标注和评测服务范围。",
    interpretation: "外包数据交付需要从人力规模表述转向场景、本体、模态和质量口径。",
    futureWatch: "观察服务商是否公开可审计的质量、许可和交付边界。",
    recommendedAction: "招标文件必须列出模态同步、失败样本、许可和验收抽检要求。",
    category: "service",
    company: "Nexdata",
    keywords: ["数据服务", "交付范围", "标注", "评测"],
    date: "2024-12-01T00:00:00.000Z",
    tracks: ["demand-definition"],
    actors: [],
    dataProfile: profile("demand-definition", {
      scenarios: ["outsourced data delivery"],
      acquisitionMethods: ["hybrid"],
    }),
    evidenceSlugs: ["nexdata-service-page", "discover-service-corroboration"],
  }),
  launchEvent({
    slug: "droid-distributed-collection",
    title: "DROID 验证分布式真实场景采集路线",
    fact: "DROID 公开跨地点真实环境机器人操作数据集、采集方法与硬件复现指南。",
    interpretation: "分布式采集可以扩大环境差异，但会把硬件一致性与现场校准变成核心运营问题。",
    futureWatch: "观察跨站点数据偏差、复现成本和现场故障率的独立报告。",
    recommendedAction: "在扩站前固定设备基线、校准流程、任务协议和异常回传格式。",
    category: "dataset",
    company: "DROID Dataset Team",
    keywords: ["分布式采集", "真实场景", "遥操作", "硬件复现"],
    date: "2024-03-19T00:00:00.000Z",
    tracks: ["acquisition-route"],
    actors: [],
    dataProfile: profile("acquisition-route", {
      scenarios: ["in-the-wild manipulation"],
      acquisitionMethods: ["teleoperation"],
    }),
    evidenceSlugs: ["droid-paper"],
  }),
  launchEvent({
    slug: "bridgedata-v2-reusable-demonstrations",
    title: "BridgeData V2 强化跨环境示范复用",
    fact: "BridgeData V2 公开跨环境机器人操作示范与训练基线。",
    interpretation: "采集路线的价值不只在单场景成功，还在任务和环境变化后的复用能力。",
    futureWatch: "观察不同机构硬件上的迁移效果和数据混合策略。",
    recommendedAction: "用跨环境保留集衡量新增采集是否真的增加泛化，而非重复已有分布。",
    category: "dataset",
    company: "UC Berkeley RAIL",
    keywords: ["示范数据", "跨环境", "泛化", "数据混合"],
    date: "2023-08-24T00:00:00.000Z",
    tracks: ["acquisition-route"],
    actors: [],
    dataProfile: profile("acquisition-route", { scenarios: ["multi-environment manipulation"] }),
    evidenceSlugs: ["bridgedata-v2-paper"],
  }),
  launchEvent({
    slug: "robomind-unified-teleoperation",
    title: "RoboMIND 以统一平台组织多本体遥操作",
    fact: "RoboMIND 发布多本体遥操作数据、统一采集平台与仿真对应环境。",
    interpretation: "多本体扩张必须同时控制采集协议、状态表示和失败样本语义。",
    futureWatch: "观察数据在新本体上的复用率以及失败示范是否改善策略恢复。",
    recommendedAction: "把本体差异显式映射到统一字段，并保留原始动作与失败原因。",
    category: "dataset",
    company: "Open X-Humanoid",
    keywords: ["多本体", "统一平台", "失败示范", "数字孪生"],
    date: "2024-12-18T00:00:00.000Z",
    tracks: ["acquisition-route"],
    actors: [],
    dataProfile: profile("acquisition-route", {
      scenarios: ["multi-embodiment manipulation"],
      embodiments: ["single-arm", "dual-arm", "humanoid"],
      acquisitionMethods: ["teleoperation", "simulation"],
    }),
    evidenceSlugs: ["robomind-paper"],
  }),
  launchEvent({
    slug: "agibot-world-bimanual-corpus",
    title: "AgiBot World 开放双臂操作数据生产资产",
    fact: "AgiBot World 开源面向双臂和人形机器人学习的数据、工具与基线。",
    interpretation: "机器人团队开始把采集、数据管理、训练和评测作为一体化资产公开。",
    futureWatch: "观察外部团队能否复现数据加载、训练与真实部署链路。",
    recommendedAction: "用小规模复现检查格式、任务定义和训练入口是否真正闭环。",
    category: "dataset",
    company: "OpenDriveLab and AgiBot",
    keywords: ["双臂", "人形机器人", "开源数据", "训练闭环"],
    date: "2025-03-09T00:00:00.000Z",
    tracks: ["acquisition-route"],
    actors: [],
    dataProfile: profile("acquisition-route", {
      scenarios: ["bimanual manipulation"],
      embodiments: ["dual-arm", "humanoid"],
    }),
    evidenceSlugs: ["agibot-world-repository"],
  }),
  launchEvent({
    slug: "pi0-data-mixture-policy",
    title: "π0 把异构机器人数据混合作为基础模型前提",
    fact: "Physical Intelligence 公开 π0 机器人基础模型及其跨平台数据混合路线。",
    interpretation: "采集路线需要围绕统一训练接口管理异构本体、任务和动作空间。",
    futureWatch: "观察独立团队的跨本体复现和数据配比消融。",
    recommendedAction: "先验证动作标准化与数据配比，再决定是否扩大异构数据采购。",
    category: "research",
    company: "Physical Intelligence",
    keywords: ["数据混合", "跨本体", "动作空间", "基础模型"],
    date: "2024-10-31T00:00:00.000Z",
    tracks: ["acquisition-route"],
    actors: [],
    dataProfile: profile("acquisition-route", {
      scenarios: ["cross-platform robot learning"],
      embodiments: ["single-arm", "mobile-manipulator"],
      acquisitionMethods: ["hybrid"],
    }),
    evidenceSlugs: ["pi0-blog"],
  }),
  launchEvent({
    slug: "discover-managed-collection-route",
    title: "采集服务商开始交付端到端机器人数据流程",
    fact: "DISCOVER 与同类服务商公开机器人数据采集、管理和训练支持的服务路径。",
    interpretation: "端到端服务降低启动门槛，但数据权属、现场控制和质量透明度成为采购风险。",
    futureWatch: "观察客户案例是否披露来源、质检、返工和许可边界。",
    recommendedAction: "将原始数据可访问性、返工机制和退出迁移条款写入合同。",
    category: "service",
    company: "DISCOVER Robotics",
    keywords: ["托管采集", "数据管理", "质量透明", "采购"],
    date: "2025-02-01T00:00:00.000Z",
    tracks: ["acquisition-route"],
    actors: [],
    dataProfile: profile("acquisition-route", {
      scenarios: ["managed robot data collection"],
      acquisitionMethods: ["hybrid"],
    }),
    evidenceSlugs: ["discover-service-page", "gesen-service-corroboration"],
  }),
  launchEvent({
    slug: "rh20t-force-aware-capture",
    title: "RH20T 将力觉与多视角同步带入操作数据",
    fact: "RH20T 公开包含视觉、机器人状态与力觉信息的机器人操作数据与采集系统。",
    interpretation: "接触任务的有效数据不能只依赖视频，传感同步与标定决定训练上限。",
    futureWatch: "观察力觉传感器漂移、跨设备标定和缺失模态处理。",
    recommendedAction: "为接触任务建立时钟、外参、力觉零点和掉帧验收记录。",
    category: "dataset",
    company: "Shanghai Jiao Tong University",
    keywords: ["力觉", "多视角", "同步", "标定"],
    date: "2023-07-02T00:00:00.000Z",
    tracks: ["multimodal-capture"],
    actors: [],
    dataProfile: profile("multimodal-capture", {
      modalities: ["rgb", "depth", "force-torque", "joint-state", "action"],
    }),
    evidenceSlugs: ["rh20t-project"],
  }),
  launchEvent({
    slug: "holoassist-multimodal-human-demonstration",
    title: "HoloAssist 连接第一视角示范与交互反馈",
    fact: "HoloAssist 开放第一视角视频、语音和人机交互标注，用于程序性任务研究。",
    interpretation: "人类示范的上下文、语言和纠错信号可以补充纯机器人轨迹。",
    futureWatch: "观察人类行为到机器人动作的对齐误差和许可边界。",
    recommendedAction: "将人类示范作为语义补充层，并单独记录可迁移与不可迁移动作。",
    category: "dataset",
    company: "Microsoft Research",
    keywords: ["第一视角", "语音", "示范", "交互反馈"],
    date: "2023-09-29T00:00:00.000Z",
    tracks: ["multimodal-capture"],
    actors: [],
    dataProfile: profile("multimodal-capture", {
      scenarios: ["procedural human assistance"],
      embodiments: ["wearable-human"],
      modalities: ["rgb", "depth", "audio", "pose", "language"],
      acquisitionMethods: ["wearable"],
    }),
    evidenceSlugs: ["holoassist-repository"],
  }),
  launchEvent({
    slug: "ego-exo4d-synchronized-demonstrations",
    title: "Ego-Exo4D 用内外视角同步描述人类技能",
    fact: "Ego-Exo4D 发布同步第一视角与外部视角的人类活动数据和基准。",
    interpretation: "内外视角互补有助于拆分意图、手部状态与环境关系。",
    futureWatch: "观察多机位同步误差、遮挡和技能到机器人动作的迁移效果。",
    recommendedAction: "在高遮挡任务中评估内外视角组合，而不是默认增加所有机位。",
    category: "dataset",
    company: "Ego4D Consortium",
    keywords: ["第一视角", "外部视角", "同步", "人类技能"],
    date: "2023-11-30T00:00:00.000Z",
    tracks: ["multimodal-capture"],
    actors: [],
    dataProfile: profile("multimodal-capture", {
      scenarios: ["human skill capture"],
      embodiments: ["wearable-human"],
      modalities: ["rgb", "audio", "pose"],
      acquisitionMethods: ["wearable"],
    }),
    evidenceSlugs: ["ego-exo4d-project"],
  }),
  launchEvent({
    slug: "aloha-bimanual-teleoperation",
    title: "ALOHA 形成低成本双臂遥操作采集方案",
    fact: "ALOHA 与 ACT 开源双臂遥操作硬件、示范采集和策略训练实现。",
    interpretation: "可复现采集硬件把双臂示范从专用系统变成可迭代工程方案。",
    futureWatch: "观察长期维护、操作者差异和不同末端执行器的兼容性。",
    recommendedAction: "先用代表性接触任务验证延迟、手感、标定和操作者学习曲线。",
    category: "capture-tool",
    company: "ALOHA Project",
    keywords: ["双臂遥操作", "低成本硬件", "示范采集", "延迟"],
    date: "2023-04-26T00:00:00.000Z",
    tracks: ["multimodal-capture"],
    actors: [],
    dataProfile: profile("multimodal-capture", {
      scenarios: ["bimanual teleoperation"],
      embodiments: ["dual-arm"],
      modalities: ["rgb", "joint-state", "action"],
    }),
    evidenceSlugs: ["aloha-act-repository"],
  }),
  launchEvent({
    slug: "umi-portable-demonstration-capture",
    title: "UMI 将便携式人类示范转换为机器人数据",
    fact: "Universal Manipulation Interface 开源便携采集装置、数据处理和策略部署方法。",
    interpretation: "脱离机器人本体采集可以提高场景覆盖，但会增加动作映射与标定复杂度。",
    futureWatch: "观察不同手持装置、末端执行器和相机配置的迁移误差。",
    recommendedAction: "先为目标本体定义可达动作域，再评估便携采集带来的覆盖增益。",
    category: "capture-tool",
    company: "Stanford REAL",
    keywords: ["便携采集", "人类示范", "动作映射", "标定"],
    date: "2024-02-15T00:00:00.000Z",
    tracks: ["multimodal-capture"],
    actors: [],
    dataProfile: profile("multimodal-capture", {
      scenarios: ["portable human demonstration"],
      embodiments: ["wearable-human", "single-arm"],
      acquisitionMethods: ["manual-demonstration"],
    }),
    evidenceSlugs: ["umi-repository"],
  }),
  launchEvent({
    slug: "astribot-manipulation-capture-stack",
    title: "星尘智能把精细操作演示与本体协同公开",
    fact: "星尘智能公开人形机器人精细操作与数据采集相关的产品演示和技术路线。",
    interpretation: "高自由度本体要求采集设备、动作表示和安全控制共同设计。",
    futureWatch: "观察连续任务、真实接触和第三方复现证据。",
    recommendedAction: "把演示拆成可重复任务，并记录接触、失败和人工接管全过程。",
    category: "industry",
    company: "Astribot",
    keywords: ["精细操作", "人形机器人", "动作表示", "接管"],
    date: "2024-04-29T00:00:00.000Z",
    tracks: ["multimodal-capture"],
    actors: [],
    dataProfile: profile("multimodal-capture", {
      scenarios: ["dexterous household manipulation"],
      embodiments: ["humanoid"],
      tasks: ["loco-manipulation"],
    }),
    evidenceSlugs: ["astribot-official"],
  }),
  launchEvent({
    slug: "roboset-reproducible-production-baseline",
    title: "RoboSet 以开放基线约束数据生产复现",
    fact: "RoboSet 公开机器人示范数据、任务配置和训练基线。",
    interpretation: "生产团队可以用公开基线检查数据读取、任务划分和训练前处理是否一致。",
    futureWatch: "观察版本升级对任务划分和历史结果可比性的影响。",
    recommendedAction: "将数据版本、划分、处理脚本和基线结果绑定为同一交付包。",
    category: "dataset",
    company: "RoboSet Project",
    keywords: ["生产基线", "版本", "任务划分", "复现"],
    date: "2023-09-05T00:00:00.000Z",
    tracks: ["production-operations"],
    actors: [],
    dataProfile: profile("production-operations", { scenarios: ["repeatable data production"] }),
    evidenceSlugs: ["roboset-project"],
  }),
  launchEvent({
    slug: "droid-consortium-site-operations",
    title: "DROID 协作网络把跨站点运营纳入数据工程",
    fact: "DROID 团队公开跨机构采集组织、统一硬件和现场操作指南。",
    interpretation: "跨站点扩产依赖培训、备件、校准和数据回传，而不只是采集脚本。",
    futureWatch: "观察站点间质量分布、设备停机和操作者差异。",
    recommendedAction: "建立站点级产能、返工、停机和校准看板，并保留版本审计。",
    category: "operations",
    company: "DROID Consortium",
    keywords: ["跨站点", "运营", "校准", "产能"],
    date: "2024-03-19T00:00:00.000Z",
    tracks: ["production-operations"],
    actors: [],
    dataProfile: profile("production-operations", {
      scenarios: ["distributed collection operations"],
      qualityMetrics: ["site consistency and equipment uptime"],
    }),
    evidenceSlugs: ["droid-consortium-project"],
  }),
  launchEvent({
    slug: "unitree-simulation-training-loop",
    title: "宇树开源仿真训练入口连接人形本体",
    fact: "Unitree Robotics 开源面向其机器人平台的仿真训练环境和部署示例。",
    interpretation: "本体厂商提供训练入口，可缩短数据生成、策略验证和部署反馈链。",
    futureWatch: "观察仿真与真实执行的差异、版本兼容和安全限制。",
    recommendedAction: "建立固定回归任务，对每次仿真和固件升级执行同一真实验证。",
    category: "tooling",
    company: "Unitree Robotics",
    keywords: ["仿真训练", "人形本体", "部署", "回归"],
    date: "2024-08-19T00:00:00.000Z",
    tracks: ["production-operations"],
    actors: [],
    dataProfile: profile("production-operations", {
      scenarios: ["humanoid locomotion training"],
      embodiments: ["humanoid", "quadruped"],
      tasks: ["locomotion"],
      acquisitionMethods: ["simulation"],
    }),
    evidenceSlugs: ["unitree-rl-gym-repository"],
  }),
  launchEvent({
    slug: "fourier-humanoid-training-platform",
    title: "傅利叶智能将训练平台与人形本体并行推进",
    fact: "傅利叶智能公开人形机器人平台、开发与训练生态的产品路线。",
    interpretation: "训练平台和本体协同可以减少接口摩擦，但也会提高供应商绑定风险。",
    futureWatch: "观察开发接口、数据可迁移性和真实场景持续运行证据。",
    recommendedAction: "采购前验证原始数据导出、接口稳定性和跨平台迁移路径。",
    category: "industry",
    company: "Fourier Intelligence",
    keywords: ["人形平台", "训练生态", "接口", "迁移"],
    date: "2024-01-30T00:00:00.000Z",
    tracks: ["production-operations"],
    actors: [],
    dataProfile: profile("production-operations", {
      scenarios: ["humanoid training platform"],
      embodiments: ["humanoid"],
      tasks: ["loco-manipulation"],
    }),
    evidenceSlugs: ["fourier-official"],
  }),
  launchEvent({
    slug: "robotera-teleoperation-operations",
    title: "星动纪元把遥操作采集纳入人形训练流程",
    fact: "星动纪元公开人形机器人、遥操作与模型训练相关的产品能力。",
    interpretation: "遥操作不再是一次性演示工具，而是持续数据生产和难例回收入口。",
    futureWatch: "观察操作者效率、任务覆盖和模型上线后的难例回流。",
    recommendedAction: "把遥操作任务、策略失败与返采优先级连成同一运营队列。",
    category: "industry",
    company: "RobotEra",
    keywords: ["遥操作", "人形训练", "难例回流", "运营"],
    date: "2024-08-21T00:00:00.000Z",
    tracks: ["production-operations"],
    actors: [],
    dataProfile: profile("production-operations", {
      scenarios: ["humanoid data operations"],
      embodiments: ["humanoid"],
    }),
    evidenceSlugs: ["robotera-official"],
  }),
  launchEvent({
    slug: "gesen-data-cleaning-operations",
    title: "具身数据供应开始强调清洗与训练交付",
    fact: "格森智能与同类服务商公开机器人数据采集、清洗和训练支持能力。",
    interpretation: "数据服务竞争正在从单纯采集人力转向可追踪的处理与交付流程。",
    futureWatch: "观察质量规则、返工周期和客户侧训练结果是否可验证。",
    recommendedAction: "要求供应商交付规则版本、抽检记录和可复算的质量报告。",
    category: "service",
    company: "GESEN AI",
    keywords: ["数据清洗", "训练交付", "返工", "质量报告"],
    date: "2025-03-01T00:00:00.000Z",
    tracks: ["production-operations"],
    actors: [],
    dataProfile: profile("production-operations", {
      scenarios: ["outsourced data operations"],
      acquisitionMethods: ["hybrid"],
    }),
    evidenceSlugs: ["gesen-service-page", "nexdata-service-corroboration"],
  }),
  launchEvent({
    slug: "open-x-standardized-datasets",
    title: "Open X-Embodiment 推动跨机器人数据标准化",
    fact: "Open X-Embodiment 公开标准化机器人数据集合与跨本体训练研究。",
    interpretation: "格式标准化让多机构数据可以进入同一训练管线，但语义一致性仍需单独治理。",
    futureWatch: "观察动作、观测和任务语义在新数据源中的兼容性。",
    recommendedAction: "在格式转换之外维护字段语义、单位、坐标系和缺失值契约。",
    category: "standard",
    company: "Open X-Embodiment Collaboration",
    keywords: ["数据标准化", "跨本体", "字段语义", "互操作"],
    date: "2023-10-13T00:00:00.000Z",
    tracks: ["data-engineering-standards"],
    actors: [],
    dataProfile: profile("data-engineering-standards", {
      scenarios: ["cross-embodiment dataset integration"],
      acquisitionMethods: ["hybrid"],
      dataFormats: ["RLDS"],
      standards: ["Open X-Embodiment schema"],
    }),
    evidenceSlugs: ["open-x-paper"],
  }),
  launchEvent({
    slug: "ario-unified-robot-data-representation",
    title: "ARIO 提出统一机器人数据表示",
    fact: "ARIO 公开面向多来源机器人数据的统一表示、数据处理与训练接口。",
    interpretation: "统一表示可以降低数据接入成本，但必须保留原始本体和传感器差异。",
    futureWatch: "观察转换损失、版本兼容和外部数据集接入效果。",
    recommendedAction: "保留原始层与规范层双份映射，并为每次转换生成审计报告。",
    category: "standard",
    company: "ARIO Project",
    keywords: ["统一表示", "数据转换", "多来源", "审计"],
    date: "2025-04-14T00:00:00.000Z",
    tracks: ["data-engineering-standards"],
    actors: [],
    dataProfile: profile("data-engineering-standards", {
      scenarios: ["multi-source robot data integration"],
      acquisitionMethods: ["hybrid"],
      dataFormats: ["ARIO representation"],
    }),
    evidenceSlugs: ["ario-project"],
  }),
  launchEvent({
    slug: "lerobot-open-dataset-toolchain",
    title: "LeRobot 打通开放数据集与训练工具链",
    fact: "Hugging Face 开源 LeRobot 数据集接口、训练代码和机器人学习工具。",
    interpretation: "统一开源工具链降低数据加载、版本共享和基线复现成本。",
    futureWatch: "观察格式版本、数据迁移和不同硬件后端的兼容性。",
    recommendedAction: "用内部小样本验证格式转换、元数据完整性和训练结果一致性。",
    category: "standard",
    company: "Hugging Face",
    keywords: ["数据集格式", "工具链", "版本", "开源"],
    date: "2024-05-14T00:00:00.000Z",
    tracks: ["data-engineering-standards"],
    actors: [],
    dataProfile: profile("data-engineering-standards", {
      scenarios: ["robot dataset publication"],
      dataFormats: ["LeRobotDataset"],
      standards: ["LeRobot dataset schema"],
    }),
    evidenceSlugs: ["lerobot-repository"],
  }),
  launchEvent({
    slug: "rlds-episodic-data-contract",
    title: "RLDS 将机器人轨迹抽象为可组合 episode",
    fact: "Google Research 开源 RLDS，为强化学习和机器人数据定义 episode 与 step 结构。",
    interpretation: "稳定的 episode 契约让采集、转换、训练和评测可以共享数据边界。",
    futureWatch: "观察嵌套观测、变长序列和大规模流式处理的兼容性。",
    recommendedAction: "用契约测试锁定 episode 边界、终止原因、字段类型和版本。",
    category: "standard",
    company: "Google Research",
    keywords: ["episode", "数据契约", "强化学习", "版本"],
    date: "2022-03-15T00:00:00.000Z",
    tracks: ["data-engineering-standards"],
    actors: [],
    dataProfile: profile("data-engineering-standards", {
      scenarios: ["episodic robot data storage"],
      dataFormats: ["RLDS"],
      standards: ["RLDS episode schema"],
    }),
    evidenceSlugs: ["rlds-repository"],
  }),
  launchEvent({
    slug: "rosbag2-recording-storage-plugins",
    title: "rosbag2 以插件化存储承接传感器记录",
    fact: "ROS 2 rosbag2 持续提供消息记录、回放和存储插件接口。",
    interpretation: "生产采集需要把消息中间件、存储格式和回放验证视为同一工程边界。",
    futureWatch: "观察高带宽传感器、时间戳一致性和存储插件升级风险。",
    recommendedAction: "为记录和回放建立带宽、丢包、时钟和版本兼容测试。",
    category: "standard",
    company: "Open Source Robotics Foundation",
    keywords: ["ROS 2", "记录", "回放", "存储插件"],
    date: "2022-05-24T00:00:00.000Z",
    tracks: ["data-engineering-standards"],
    actors: [],
    dataProfile: profile("data-engineering-standards", {
      scenarios: ["sensor stream recording"],
      modalities: ["rgb", "depth", "point-cloud", "imu", "joint-state"],
      dataFormats: ["rosbag2"],
      standards: ["ROS 2 messages"],
    }),
    evidenceSlugs: ["rosbag2-repository"],
  }),
  launchEvent({
    slug: "mcap-interoperable-sensor-container",
    title: "MCAP 提供跨工具的机器人日志容器",
    fact: "Foxglove 开源 MCAP 规范与多语言实现，用于时间序列和机器人消息存储。",
    interpretation: "开放容器格式可以降低采集、回放、可视化和长期归档之间的转换成本。",
    futureWatch: "观察不同语言实现、压缩方式和 schema 演进的兼容性。",
    recommendedAction: "用真实高带宽样本验证写入、索引、恢复和跨工具读取。",
    category: "standard",
    company: "Foxglove",
    keywords: ["MCAP", "日志容器", "互操作", "归档"],
    date: "2022-02-10T00:00:00.000Z",
    tracks: ["data-engineering-standards"],
    actors: [],
    dataProfile: profile("data-engineering-standards", {
      scenarios: ["robot log storage"],
      dataFormats: ["MCAP"],
      standards: ["MCAP specification"],
    }),
    evidenceSlugs: ["mcap-repository"],
  }),
  launchEvent({
    slug: "robocasa-synthetic-household-data",
    title: "RoboCasa 用程序化场景生成家庭操作数据",
    fact: "RoboCasa 开源家庭操作仿真环境、任务和程序化场景生成工具。",
    interpretation: "合成数据可以扩展布局和对象组合，但必须通过真实任务验证有效性。",
    futureWatch: "观察仿真偏差、资产覆盖与真实部署成功率的关联。",
    recommendedAction: "为每类合成变化配置真实保留集，并按失败类型决定继续生成什么数据。",
    category: "simulation",
    company: "RoboCasa Project",
    keywords: ["合成数据", "家庭场景", "程序化生成", "真实验证"],
    date: "2024-06-04T00:00:00.000Z",
    tracks: ["quality-training-feedback"],
    actors: [],
    dataProfile: profile("quality-training-feedback", {
      scenarios: ["synthetic household manipulation"],
      acquisitionMethods: ["simulation", "synthetic"],
    }),
    evidenceSlugs: ["robocasa-repository"],
  }),
  launchEvent({
    slug: "isaac-sim-synthetic-sensor-data",
    title: "Isaac Sim 将传感器仿真用于合成数据验证",
    fact: "NVIDIA Isaac Sim 提供机器人仿真、传感器模拟和合成数据工作流。",
    interpretation: "高保真传感器模型为稀缺场景补数据，但不能替代真实噪声和硬件失效样本。",
    futureWatch: "观察传感器模型误差、资产域差异和 sim-to-real 结果。",
    recommendedAction: "把合成数据按生成配置版本化，并与真实保留集持续对照。",
    category: "simulation",
    company: "NVIDIA",
    keywords: ["传感器仿真", "合成数据", "sim-to-real", "版本"],
    date: "2022-01-31T00:00:00.000Z",
    tracks: ["quality-training-feedback"],
    actors: [],
    dataProfile: profile("quality-training-feedback", {
      scenarios: ["synthetic sensor generation"],
      acquisitionMethods: ["simulation", "synthetic"],
      modalities: ["rgb", "depth", "point-cloud", "imu"],
    }),
    evidenceSlugs: ["isaac-sim-repository"],
  }),
  launchEvent({
    slug: "isaac-lab-training-evaluation-loop",
    title: "Isaac Lab 统一仿真训练与策略评测",
    fact: "NVIDIA Isaac Lab 开源模块化机器人学习环境、任务配置与训练接口。",
    interpretation: "训练环境与评测任务统一后，数据生成可以直接由失败指标驱动。",
    futureWatch: "观察环境版本变化、随机化配置和真实验证的一致性。",
    recommendedAction: "冻结黄金环境和随机种子，并将策略失败自动回流到数据需求。",
    category: "simulation",
    company: "NVIDIA",
    keywords: ["仿真训练", "策略评测", "失败回流", "环境版本"],
    date: "2024-04-01T00:00:00.000Z",
    tracks: ["quality-training-feedback"],
    actors: [],
    dataProfile: profile("quality-training-feedback", {
      scenarios: ["simulation training evaluation"],
      acquisitionMethods: ["simulation"],
    }),
    evidenceSlugs: ["isaac-lab-repository"],
  }),
  launchEvent({
    slug: "isaac-teleop-simulation-capture",
    title: "Isaac TeleOp 连接人类示范与仿真数据生成",
    fact: "NVIDIA Isaac 平台公开遥操作、仿真和机器人示范采集工作流。",
    interpretation: "在仿真中先验证采集交互可以降低硬件占用，但需要严格校验真实动作映射。",
    futureWatch: "观察端到端延迟、手部映射和真实执行误差。",
    recommendedAction: "用高风险接触任务对比仿真示范与真实示范的策略效果。",
    category: "capture-tool",
    company: "NVIDIA",
    keywords: ["遥操作", "仿真", "示范采集", "动作映射"],
    date: "2025-03-18T00:00:00.000Z",
    tracks: ["quality-training-feedback"],
    actors: [],
    dataProfile: profile("quality-training-feedback", {
      scenarios: ["simulation teleoperation"],
      acquisitionMethods: ["teleoperation", "simulation"],
    }),
    evidenceSlugs: ["isaac-teleop-official"],
  }),
  launchEvent({
    slug: "gello-policy-feedback-capture",
    title: "GELLO 让遥操作装置服务于快速策略迭代",
    fact: "GELLO 开源低成本机器人遥操作装置、软件和示范采集实现。",
    interpretation: "低成本控制器有利于快速返采难例，但设备一致性会直接影响数据质量。",
    futureWatch: "观察长时间使用的漂移、操作者疲劳和跨机械臂适配。",
    recommendedAction: "把训练失败转成返采队列，并为每台控制器保留校准与维护记录。",
    category: "capture-tool",
    company: "GELLO Project",
    keywords: ["遥操作装置", "难例返采", "校准", "策略迭代"],
    date: "2023-09-22T00:00:00.000Z",
    tracks: ["quality-training-feedback"],
    actors: [],
    dataProfile: profile("quality-training-feedback", {
      scenarios: ["rapid teleoperation iteration"],
      acquisitionMethods: ["teleoperation"],
    }),
    evidenceSlugs: ["gello-repository"],
  }),
  launchEvent({
    slug: "galaxea-open-data-feedback-loop",
    title: "星海图把开放数据与移动操作训练联动",
    fact: "Galaxea AI 公开移动操作机器人、模型和数据相关的研发与开源入口。",
    interpretation: "本体、数据与模型协同可以缩短失败回流，但公开能力仍需逐项证据验证。",
    futureWatch: "观察数据版本、真实任务成功和第三方复现。",
    recommendedAction: "只把有公开证据的能力写入同行矩阵，并为每项声明设置失效条件。",
    category: "industry",
    company: "Galaxea AI",
    keywords: ["移动操作", "开放数据", "失败回流", "同行证据"],
    date: "2025-01-15T00:00:00.000Z",
    tracks: ["quality-training-feedback"],
    actors: [],
    dataProfile: profile("quality-training-feedback", {
      scenarios: ["mobile manipulation training"],
      embodiments: ["mobile-manipulator"],
      tasks: ["loco-manipulation"],
    }),
    evidenceSlugs: ["galaxea-official"],
  }),
];
