export type EmbodiedEvidenceRole = "primary" | "corroborating";

export interface EmbodiedEventEvidence {
  slug: string;
  eventSlug: string;
  sourceSlug: string;
  sourceIdentity: string;
  sourceTier: 1 | 2;
  role: EmbodiedEvidenceRole;
  title: string;
  url: string;
  publishedAt: string;
}

const evidence = (value: EmbodiedEventEvidence): EmbodiedEventEvidence => value;

export const embodiedEventEvidence: EmbodiedEventEvidence[] = [
  evidence({
    slug: "behavior-1k-project",
    eventSlug: "behavior-1k-task-definition",
    sourceSlug: "behavior-1k",
    sourceIdentity: "Stanford Vision and Learning Lab",
    sourceTier: 1,
    role: "primary",
    title: "BEHAVIOR-1K project repository",
    url: "https://github.com/StanfordVL/BEHAVIOR-1K",
    publishedAt: "2024-02-29T00:00:00.000Z",
  }),
  evidence({
    slug: "libero-project",
    eventSlug: "libero-lifelong-task-suites",
    sourceSlug: "libero-benchmark",
    sourceIdentity: "Lifelong Robot Learning Lab",
    sourceTier: 1,
    role: "primary",
    title: "LIBERO project repository",
    url: "https://github.com/Lifelong-Robot-Learning/LIBERO",
    publishedAt: "2023-06-06T00:00:00.000Z",
  }),
  evidence({
    slug: "calvin-project",
    eventSlug: "calvin-long-horizon-language-benchmark",
    sourceSlug: "calvin-benchmark",
    sourceIdentity: "CALVIN Project",
    sourceTier: 1,
    role: "primary",
    title: "CALVIN project repository",
    url: "https://github.com/mees/calvin",
    publishedAt: "2022-06-15T00:00:00.000Z",
  }),
  evidence({
    slug: "rt1-paper",
    eventSlug: "rt1-data-driven-robotics",
    sourceSlug: "google-deepmind-robotics",
    sourceIdentity: "Google Robotics",
    sourceTier: 1,
    role: "primary",
    title: "RT-1: Robotics Transformer for Real-World Control at Scale",
    url: "https://arxiv.org/abs/2212.06817",
    publishedAt: "2022-12-13T00:00:00.000Z",
  }),
  evidence({
    slug: "ubtech-industrial-source",
    eventSlug: "ubtech-industrial-task-program",
    sourceSlug: "ubtech-robotics",
    sourceIdentity: "UBTECH Robotics",
    sourceTier: 1,
    role: "primary",
    title: "UBTECH Robotics official site",
    url: "https://www.ubtrobot.com/",
    publishedAt: "2024-07-01T00:00:00.000Z",
  }),
  evidence({
    slug: "nexdata-service-page",
    eventSlug: "nexdata-embodied-delivery-scope",
    sourceSlug: "nexdata-embodied-ai",
    sourceIdentity: "Nexdata",
    sourceTier: 2,
    role: "primary",
    title: "Nexdata embodied AI services",
    url: "https://www.nexdata.ai/industries/embodied-ai",
    publishedAt: "2024-12-01T00:00:00.000Z",
  }),
  evidence({
    slug: "discover-service-corroboration",
    eventSlug: "nexdata-embodied-delivery-scope",
    sourceSlug: "discover-robotics-data",
    sourceIdentity: "DISCOVER Robotics",
    sourceTier: 2,
    role: "corroborating",
    title: "DISCOVER robotics data collection services",
    url: "https://www.discover-robotics.com/en/data-collection",
    publishedAt: "2025-02-01T00:00:00.000Z",
  }),
  evidence({
    slug: "droid-paper",
    eventSlug: "droid-distributed-collection",
    sourceSlug: "droid-project",
    sourceIdentity: "DROID Dataset Team",
    sourceTier: 1,
    role: "primary",
    title: "DROID: A Large-Scale In-The-Wild Robot Manipulation Dataset",
    url: "https://arxiv.org/abs/2403.12945",
    publishedAt: "2024-03-19T00:00:00.000Z",
  }),
  evidence({
    slug: "bridgedata-v2-paper",
    eventSlug: "bridgedata-v2-reusable-demonstrations",
    sourceSlug: "bridge-data-v2",
    sourceIdentity: "UC Berkeley RAIL",
    sourceTier: 1,
    role: "primary",
    title: "BridgeData V2: A Dataset for Robot Learning at Scale",
    url: "https://arxiv.org/abs/2308.12952",
    publishedAt: "2023-08-24T00:00:00.000Z",
  }),
  evidence({
    slug: "robomind-paper",
    eventSlug: "robomind-unified-teleoperation",
    sourceSlug: "robomind",
    sourceIdentity: "Open X-Humanoid",
    sourceTier: 1,
    role: "primary",
    title: "RoboMIND: Benchmark on Multi-embodiment Intelligence Normative Data",
    url: "https://arxiv.org/abs/2412.13877",
    publishedAt: "2024-12-18T00:00:00.000Z",
  }),
  evidence({
    slug: "agibot-world-repository",
    eventSlug: "agibot-world-bimanual-corpus",
    sourceSlug: "agibot-world",
    sourceIdentity: "OpenDriveLab and AgiBot",
    sourceTier: 1,
    role: "primary",
    title: "AgiBot World project repository",
    url: "https://github.com/OpenDriveLab/AgiBot-World",
    publishedAt: "2025-03-09T00:00:00.000Z",
  }),
  evidence({
    slug: "pi0-blog",
    eventSlug: "pi0-data-mixture-policy",
    sourceSlug: "physical-intelligence",
    sourceIdentity: "Physical Intelligence",
    sourceTier: 1,
    role: "primary",
    title: "π0: A Vision-Language-Action Flow Model for General Robot Control",
    url: "https://www.physicalintelligence.company/blog/pi0",
    publishedAt: "2024-10-31T00:00:00.000Z",
  }),
  evidence({
    slug: "discover-service-page",
    eventSlug: "discover-managed-collection-route",
    sourceSlug: "discover-robotics-data",
    sourceIdentity: "DISCOVER Robotics",
    sourceTier: 2,
    role: "primary",
    title: "DISCOVER robotics data acquisition",
    url: "https://www.discover-robotics.com/en/data-collection",
    publishedAt: "2025-02-01T00:00:00.000Z",
  }),
  evidence({
    slug: "gesen-service-corroboration",
    eventSlug: "discover-managed-collection-route",
    sourceSlug: "gesen-ai",
    sourceIdentity: "Zhejiang Gesen Intelligence Technology",
    sourceTier: 2,
    role: "corroborating",
    title: "GESEN AI official services",
    url: "https://www.gesenai.cn/",
    publishedAt: "2025-03-01T00:00:00.000Z",
  }),
  evidence({
    slug: "rh20t-project",
    eventSlug: "rh20t-force-aware-capture",
    sourceSlug: "rh20t",
    sourceIdentity: "Shanghai Jiao Tong University",
    sourceTier: 1,
    role: "primary",
    title: "RH20T project",
    url: "https://rh20t.github.io/",
    publishedAt: "2023-07-02T00:00:00.000Z",
  }),
  evidence({
    slug: "holoassist-repository",
    eventSlug: "holoassist-multimodal-human-demonstration",
    sourceSlug: "holoassist",
    sourceIdentity: "Microsoft Research",
    sourceTier: 1,
    role: "primary",
    title: "HoloAssist project",
    url: "https://holoassist.github.io/",
    publishedAt: "2023-09-29T00:00:00.000Z",
  }),
  evidence({
    slug: "ego-exo4d-project",
    eventSlug: "ego-exo4d-synchronized-demonstrations",
    sourceSlug: "ego-exo4d",
    sourceIdentity: "Ego4D Consortium",
    sourceTier: 1,
    role: "primary",
    title: "Ego-Exo4D project",
    url: "https://ego-exo4d-data.org/",
    publishedAt: "2023-11-30T00:00:00.000Z",
  }),
  evidence({
    slug: "aloha-act-repository",
    eventSlug: "aloha-bimanual-teleoperation",
    sourceSlug: "aloha-act",
    sourceIdentity: "ALOHA Project",
    sourceTier: 1,
    role: "primary",
    title: "ALOHA and ACT project repository",
    url: "https://github.com/tonyzhaozh/act",
    publishedAt: "2023-04-26T00:00:00.000Z",
  }),
  evidence({
    slug: "umi-repository",
    eventSlug: "umi-portable-demonstration-capture",
    sourceSlug: "universal-manipulation-interface",
    sourceIdentity: "Stanford REAL",
    sourceTier: 1,
    role: "primary",
    title: "Universal Manipulation Interface repository",
    url: "https://github.com/real-stanford/universal_manipulation_interface",
    publishedAt: "2024-02-15T00:00:00.000Z",
  }),
  evidence({
    slug: "astribot-official",
    eventSlug: "astribot-manipulation-capture-stack",
    sourceSlug: "astribot",
    sourceIdentity: "Astribot",
    sourceTier: 1,
    role: "primary",
    title: "Astribot official site",
    url: "https://www.astribot.com/",
    publishedAt: "2024-04-29T00:00:00.000Z",
  }),
  evidence({
    slug: "roboset-project",
    eventSlug: "roboset-reproducible-production-baseline",
    sourceSlug: "roboset",
    sourceIdentity: "RoboSet Project",
    sourceTier: 1,
    role: "primary",
    title: "RoboSet project",
    url: "https://robopen.github.io/roboset/",
    publishedAt: "2023-09-05T00:00:00.000Z",
  }),
  evidence({
    slug: "droid-consortium-project",
    eventSlug: "droid-consortium-site-operations",
    sourceSlug: "droid-consortium",
    sourceIdentity: "DROID Consortium",
    sourceTier: 1,
    role: "primary",
    title: "DROID distributed collection project",
    url: "https://droid-dataset.github.io/",
    publishedAt: "2024-03-19T00:00:00.000Z",
  }),
  evidence({
    slug: "unitree-rl-gym-repository",
    eventSlug: "unitree-simulation-training-loop",
    sourceSlug: "unitree-robotics",
    sourceIdentity: "Unitree Robotics",
    sourceTier: 1,
    role: "primary",
    title: "Unitree RL Gym repository",
    url: "https://github.com/unitreerobotics/unitree_rl_gym",
    publishedAt: "2024-08-19T00:00:00.000Z",
  }),
  evidence({
    slug: "fourier-official",
    eventSlug: "fourier-humanoid-training-platform",
    sourceSlug: "fourier-intelligence",
    sourceIdentity: "Fourier Intelligence",
    sourceTier: 1,
    role: "primary",
    title: "Fourier Intelligence official site",
    url: "https://fourierintelligence.com/",
    publishedAt: "2024-01-30T00:00:00.000Z",
  }),
  evidence({
    slug: "robotera-official",
    eventSlug: "robotera-teleoperation-operations",
    sourceSlug: "robotera",
    sourceIdentity: "RobotEra",
    sourceTier: 1,
    role: "primary",
    title: "RobotEra official site",
    url: "https://www.robotera.com/",
    publishedAt: "2024-08-21T00:00:00.000Z",
  }),
  evidence({
    slug: "gesen-service-page",
    eventSlug: "gesen-data-cleaning-operations",
    sourceSlug: "gesen-ai",
    sourceIdentity: "Zhejiang Gesen Intelligence Technology",
    sourceTier: 2,
    role: "primary",
    title: "GESEN AI official services",
    url: "https://www.gesenai.cn/",
    publishedAt: "2025-03-01T00:00:00.000Z",
  }),
  evidence({
    slug: "nexdata-service-corroboration",
    eventSlug: "gesen-data-cleaning-operations",
    sourceSlug: "nexdata-embodied-ai",
    sourceIdentity: "Nexdata",
    sourceTier: 2,
    role: "corroborating",
    title: "Nexdata embodied AI services",
    url: "https://www.nexdata.ai/industries/embodied-ai",
    publishedAt: "2024-12-01T00:00:00.000Z",
  }),
  evidence({
    slug: "open-x-paper",
    eventSlug: "open-x-standardized-datasets",
    sourceSlug: "open-x-embodiment",
    sourceIdentity: "Open X-Embodiment Collaboration",
    sourceTier: 1,
    role: "primary",
    title: "Open X-Embodiment: Robotic Learning Datasets and RT-X Models",
    url: "https://arxiv.org/abs/2310.08864",
    publishedAt: "2023-10-13T00:00:00.000Z",
  }),
  evidence({
    slug: "ario-project",
    eventSlug: "ario-unified-robot-data-representation",
    sourceSlug: "ario-dataset",
    sourceIdentity: "ARIO Project",
    sourceTier: 1,
    role: "primary",
    title: "ARIO project",
    url: "https://imaei.github.io/project_pages/ario/",
    publishedAt: "2025-04-14T00:00:00.000Z",
  }),
  evidence({
    slug: "lerobot-repository",
    eventSlug: "lerobot-open-dataset-toolchain",
    sourceSlug: "huggingface-lerobot",
    sourceIdentity: "Hugging Face",
    sourceTier: 1,
    role: "primary",
    title: "LeRobot repository",
    url: "https://github.com/huggingface/lerobot",
    publishedAt: "2024-05-14T00:00:00.000Z",
  }),
  evidence({
    slug: "rlds-repository",
    eventSlug: "rlds-episodic-data-contract",
    sourceSlug: "google-rlds",
    sourceIdentity: "Google Research",
    sourceTier: 1,
    role: "primary",
    title: "RLDS repository",
    url: "https://github.com/google-research/rlds",
    publishedAt: "2022-03-15T00:00:00.000Z",
  }),
  evidence({
    slug: "rosbag2-repository",
    eventSlug: "rosbag2-recording-storage-plugins",
    sourceSlug: "ros2-rosbag2",
    sourceIdentity: "Open Source Robotics Foundation",
    sourceTier: 1,
    role: "primary",
    title: "ROS 2 rosbag2 repository",
    url: "https://github.com/ros2/rosbag2",
    publishedAt: "2022-05-24T00:00:00.000Z",
  }),
  evidence({
    slug: "mcap-repository",
    eventSlug: "mcap-interoperable-sensor-container",
    sourceSlug: "foxglove-mcap",
    sourceIdentity: "Foxglove",
    sourceTier: 1,
    role: "primary",
    title: "MCAP repository",
    url: "https://github.com/foxglove/mcap",
    publishedAt: "2022-02-10T00:00:00.000Z",
  }),
  evidence({
    slug: "robocasa-repository",
    eventSlug: "robocasa-synthetic-household-data",
    sourceSlug: "robocasa",
    sourceIdentity: "RoboCasa Project",
    sourceTier: 1,
    role: "primary",
    title: "RoboCasa repository",
    url: "https://github.com/robocasa/robocasa",
    publishedAt: "2024-06-04T00:00:00.000Z",
  }),
  evidence({
    slug: "isaac-sim-repository",
    eventSlug: "isaac-sim-synthetic-sensor-data",
    sourceSlug: "nvidia-isaac-sim",
    sourceIdentity: "NVIDIA",
    sourceTier: 1,
    role: "primary",
    title: "NVIDIA Isaac Sim repository",
    url: "https://github.com/isaac-sim/IsaacSim",
    publishedAt: "2022-01-31T00:00:00.000Z",
  }),
  evidence({
    slug: "isaac-lab-repository",
    eventSlug: "isaac-lab-training-evaluation-loop",
    sourceSlug: "nvidia-isaac-lab",
    sourceIdentity: "NVIDIA",
    sourceTier: 1,
    role: "primary",
    title: "NVIDIA Isaac Lab repository",
    url: "https://github.com/isaac-sim/IsaacLab",
    publishedAt: "2024-04-01T00:00:00.000Z",
  }),
  evidence({
    slug: "isaac-teleop-official",
    eventSlug: "isaac-teleop-simulation-capture",
    sourceSlug: "nvidia-isaac-teleop",
    sourceIdentity: "NVIDIA",
    sourceTier: 1,
    role: "primary",
    title: "NVIDIA Isaac Sim official page",
    url: "https://developer.nvidia.com/isaac/sim",
    publishedAt: "2025-03-18T00:00:00.000Z",
  }),
  evidence({
    slug: "gello-repository",
    eventSlug: "gello-policy-feedback-capture",
    sourceSlug: "gello",
    sourceIdentity: "GELLO Project",
    sourceTier: 1,
    role: "primary",
    title: "GELLO software repository",
    url: "https://github.com/wuphilipp/gello_software",
    publishedAt: "2023-09-22T00:00:00.000Z",
  }),
  evidence({
    slug: "galaxea-official",
    eventSlug: "galaxea-open-data-feedback-loop",
    sourceSlug: "galaxea-ai",
    sourceIdentity: "Galaxea AI",
    sourceTier: 1,
    role: "primary",
    title: "Galaxea AI official site",
    url: "https://www.galaxea-ai.com/",
    publishedAt: "2025-01-15T00:00:00.000Z",
  }),
];
