import type { EmbodiedPipelineStage } from "../../domain/embodied-data.js";
import type { SourceMapStatus } from "../../domain/embodied-source-map.js";
import type { CatalogSource, SourceCategory } from "../sources.js";

export type EmbodiedCatalogSource = CatalogSource & {
  owner: string;
  mapStatus: SourceMapStatus;
  pipelineStages: EmbodiedPipelineStage[];
  substituteFor: string[];
  restrictionNote: string;
  robotsPolicy: string;
  freshnessSloHours: number;
  adapterVersion: string;
};

type SourceInput = Pick<
  EmbodiedCatalogSource,
  | "slug"
  | "name"
  | "owner"
  | "homepageUrl"
  | "endpoint"
  | "adapter"
  | "tier"
  | "role"
  | "region"
  | "language"
  | "category"
  | "acquisition"
  | "topics"
  | "pipelineStages"
> &
  Partial<
    Pick<
      EmbodiedCatalogSource,
      | "mapStatus"
      | "substituteFor"
      | "restrictionNote"
      | "lifecycleStatus"
      | "authorityScore"
      | "qualityScore"
      | "maintenanceStatus"
      | "cadence"
      | "licenseNote"
      | "robotsPolicy"
      | "freshnessSloHours"
      | "adapterVersion"
      | "identityHosts"
      | "html"
    >
  >;

const governed = (input: SourceInput): EmbodiedCatalogSource => ({
  ...input,
  authorityScore: input.authorityScore ?? 85,
  qualityScore: input.qualityScore ?? 70,
  enabled: false,
  lifecycleStatus: input.lifecycleStatus ?? "shadow",
  mapStatus: input.mapStatus ?? "pending",
  substituteFor: input.substituteFor ?? [],
  restrictionNote: input.restrictionNote ?? "",
  maintenanceStatus: input.maintenanceStatus ?? "candidate",
  cadence: input.cadence ?? "weekly",
  licenseNote:
    input.licenseNote ??
    "Use public metadata and short factual excerpts only; retain attribution and verify project-specific license terms before reuse.",
  robotsPolicy:
    input.robotsPolicy ??
    "Respect published robots rules and terms; stop collection when automated access is not explicitly allowed.",
  freshnessSloHours: input.freshnessSloHours ?? 168,
  adapterVersion: input.adapterVersion ?? "1",
  identityHosts: input.identityHosts ?? [new URL(input.homepageUrl).hostname],
});

const github = (
  input: Omit<SourceInput, "endpoint" | "adapter" | "acquisition" | "homepageUrl"> & {
    repository: string;
  },
) =>
  governed({
    ...input,
    homepageUrl: `https://github.com/${input.repository}`,
    endpoint: `https://github.com/${input.repository}/releases.atom`,
    adapter: "github-releases",
    acquisition: "github",
  });

const website = (
  input: Omit<SourceInput, "endpoint" | "adapter" | "acquisition"> & { endpoint?: string },
) =>
  governed({
    ...input,
    endpoint: input.endpoint ?? input.homepageUrl,
    adapter: "web-scraper",
    acquisition: "html",
  });

const manual = (input: Omit<SourceInput, "endpoint" | "adapter" | "acquisition">) =>
  governed({
    ...input,
    endpoint: input.homepageUrl,
    adapter: "manual",
    acquisition: "manual",
    lifecycleStatus: "draft",
    maintenanceStatus: input.maintenanceStatus ?? "manual",
    robotsPolicy:
      "Automation is not approved. Review robots.txt and owner terms before an adapter trial; manual public-metadata review only.",
    licenseNote:
      "Public metadata and short attributed summaries only. Dataset, model, code and standard-text licenses require separate review.",
  });

export const legacySourcePolicy = {
  contentScope: "legacy-ai",
  enabled: false,
  observationEnabled: false,
  lifecycleStatus: "retired",
  maintenanceStatus: "retired",
} as const;

export const embodiedSourceCatalog: EmbodiedCatalogSource[] = [
  website({
    slug: "droid-project",
    pipelineStages: ["acquisition-route", "production-operations", "quality-training-feedback"],
    identityHosts: ["droid-dataset.github.io"],
    name: "DROID Dataset",
    owner: "DROID Dataset Team",
    homepageUrl: "https://droid-dataset.github.io/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["teleoperation", "robot-manipulation", "distributed-collection"],
  }),
  website({
    slug: "bridge-data-v2",
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["rail-berkeley.github.io"],
    name: "BridgeData V2",
    owner: "UC Berkeley RAIL",
    homepageUrl: "https://rail-berkeley.github.io/bridgedata/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["teleoperation", "autonomous-rollout", "manipulation"],
  }),
  website({
    slug: "open-x-embodiment",
    pipelineStages: ["data-engineering-standards", "quality-training-feedback"],
    identityHosts: ["robotics-transformer-x.github.io"],
    name: "Open X-Embodiment",
    owner: "Open X-Embodiment Collaboration",
    homepageUrl: "https://robotics-transformer-x.github.io/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["cross-embodiment", "rlds", "robot-learning"],
  }),
  website({
    slug: "rh20t",
    pipelineStages: ["multimodal-capture", "quality-training-feedback"],
    identityHosts: ["rh20t.github.io"],
    name: "RH20T",
    owner: "Shanghai Jiao Tong University",
    homepageUrl: "https://rh20t.github.io/",
    tier: 1,
    role: "research",
    region: "CN",
    language: "en",
    category: "dataset-benchmark",
    topics: ["multimodal-capture", "force", "robot-manipulation"],
  }),
  website({
    slug: "roboset",
    pipelineStages: ["acquisition-route", "production-operations", "quality-training-feedback"],
    identityHosts: ["robopen.github.io"],
    name: "RoboSet",
    owner: "RoboSet Project",
    homepageUrl: "https://robopen.github.io/roboset/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["robot-demonstration", "manipulation", "benchmark"],
  }),
  website({
    slug: "robomind",
    pipelineStages: ["acquisition-route", "multimodal-capture", "quality-training-feedback"],
    identityHosts: ["x-humanoid.com", "x-humanoid-robomind.github.io"],
    name: "RoboMIND",
    owner: "Open X-Humanoid",
    homepageUrl: "https://x-humanoid-robomind.github.io/",
    tier: 1,
    role: "research",
    region: "CN",
    language: "en",
    category: "dataset-benchmark",
    topics: ["multi-embodiment", "teleoperation", "digital-twin"],
  }),
  github({
    slug: "agibot-world",
    pipelineStages: ["acquisition-route", "production-operations", "quality-training-feedback"],
    identityHosts: ["opendrivelab.com", "agibot.com"],
    name: "AgiBot World",
    owner: "OpenDriveLab and AgiBot",
    repository: "OpenDriveLab/AgiBot-World",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["bimanual-manipulation", "large-scale-data", "robot-foundation-model"],
  }),
  github({
    slug: "behavior-1k",
    pipelineStages: ["demand-definition", "acquisition-route", "quality-training-feedback"],
    identityHosts: ["svl.stanford.edu"],
    name: "BEHAVIOR-1K",
    owner: "Stanford Vision and Learning Lab",
    repository: "StanfordVL/BEHAVIOR-1K",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["task-definition", "simulation", "household-activities"],
  }),
  github({
    slug: "libero-benchmark",
    pipelineStages: ["demand-definition", "quality-training-feedback"],
    identityHosts: [],
    name: "LIBERO",
    owner: "Lifelong Robot Learning Lab",
    repository: "Lifelong-Robot-Learning/LIBERO",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["benchmark", "lifelong-learning", "manipulation"],
  }),
  governed({
    slug: "robocasa",
    endpoint: "https://api.github.com/repos/robocasa/robocasa/releases?per_page=3",
    adapter: "json-api",
    acquisition: "api",
    adapterVersion: "1",
    robotsPolicy:
      "Public release API fixture verified. Policy review remains pending; do not enable observation. GitHub Atom paths are robots-disallowed.",
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["robocasa.ai"],
    name: "RoboCasa",
    owner: "RoboCasa Project",
    homepageUrl: "https://github.com/robocasa/robocasa",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["simulation", "synthetic-data", "household-manipulation"],
  }),
  github({
    slug: "calvin-benchmark",
    pipelineStages: ["demand-definition", "quality-training-feedback"],
    identityHosts: [],
    name: "CALVIN",
    owner: "CALVIN Project",
    repository: "mees/calvin",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["benchmark", "language-conditioned", "long-horizon"],
  }),
  website({
    slug: "holoassist",
    pipelineStages: ["multimodal-capture"],
    identityHosts: ["holoassist.github.io"],
    name: "HoloAssist",
    owner: "Microsoft Research",
    homepageUrl: "https://holoassist.github.io/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["egocentric-video", "human-demonstration", "multimodal"],
  }),
  website({
    slug: "ego-exo4d",
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["ego-exo4d-data.org"],
    name: "Ego-Exo4D",
    owner: "Ego4D Consortium",
    homepageUrl: "https://ego-exo4d-data.org/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["egocentric-video", "exo-centric-video", "human-demonstration"],
  }),
  website({
    slug: "ario-dataset",
    pipelineStages: ["data-engineering-standards"],
    identityHosts: ["imaei.github.io"],
    name: "ARIO",
    owner: "ARIO Project",
    homepageUrl: "https://imaei.github.io/project_pages/ario/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["unified-representation", "multi-embodiment", "data-engineering"],
  }),
  github({
    slug: "huggingface-lerobot",
    pipelineStages: ["data-engineering-standards", "quality-training-feedback"],
    identityHosts: ["huggingface.co"],
    name: "LeRobot",
    owner: "Hugging Face",
    repository: "huggingface/lerobot",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["dataset-format", "robot-learning", "open-source"],
    freshnessSloHours: 72,
  }),
  github({
    slug: "google-rlds",
    pipelineStages: ["data-engineering-standards"],
    identityHosts: ["research.google", "deepmind.google"],
    name: "RLDS",
    owner: "Google Research",
    repository: "google-research/rlds",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["dataset-schema", "episodes", "data-engineering"],
  }),
  github({
    slug: "ros2-rosbag2",
    pipelineStages: ["multimodal-capture", "data-engineering-standards"],
    identityHosts: ["ros.org"],
    name: "ROS 2 rosbag2",
    owner: "Open Source Robotics Foundation",
    repository: "ros2/rosbag2",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["sensor-recording", "storage", "ros2"],
    freshnessSloHours: 72,
  }),
  github({
    slug: "foxglove-mcap",
    pipelineStages: ["data-engineering-standards"],
    identityHosts: ["foxglove.dev"],
    name: "MCAP",
    owner: "Foxglove",
    repository: "foxglove/mcap",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["container-format", "sensor-data", "interoperability"],
  }),
  github({
    slug: "universal-manipulation-interface",
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["real.stanford.edu"],
    name: "Universal Manipulation Interface",
    owner: "Stanford REAL",
    repository: "real-stanford/universal_manipulation_interface",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["human-demonstration", "portable-capture", "manipulation"],
  }),
  github({
    slug: "gello",
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: [],
    name: "GELLO",
    owner: "GELLO Project",
    repository: "wuphilipp/gello_software",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["teleoperation", "low-cost-hardware", "demonstration"],
  }),
  github({
    slug: "aloha-act",
    pipelineStages: ["acquisition-route", "multimodal-capture", "quality-training-feedback"],
    identityHosts: [],
    name: "ALOHA and ACT",
    owner: "ALOHA Project",
    repository: "tonyzhaozh/act",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["bimanual-teleoperation", "action-chunking", "demonstration"],
  }),
  github({
    slug: "nvidia-isaac-sim",
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["nvidia.com", "developer.nvidia.com"],
    name: "NVIDIA Isaac Sim",
    owner: "NVIDIA",
    repository: "isaac-sim/IsaacSim",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["simulation", "synthetic-data", "sensor-simulation"],
    freshnessSloHours: 72,
  }),
  github({
    slug: "nvidia-isaac-lab",
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["nvidia.com", "developer.nvidia.com"],
    name: "NVIDIA Isaac Lab",
    owner: "NVIDIA",
    repository: "isaac-sim/IsaacLab",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["simulation", "robot-learning", "synthetic-data"],
    freshnessSloHours: 72,
  }),
  website({
    slug: "nvidia-isaac-teleop",
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["nvidia.com", "developer.nvidia.com"],
    name: "NVIDIA Isaac TeleOp",
    owner: "NVIDIA",
    homepageUrl: "https://developer.nvidia.com/isaac/sim",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["teleoperation", "simulation", "demonstration"],
  }),
  website({
    slug: "google-deepmind-robotics",
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["research.google", "deepmind.google"],
    name: "Google DeepMind Robotics",
    owner: "Google DeepMind",
    homepageUrl: "https://deepmind.google/discover/blog/",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["robot-learning", "data-scaling", "evaluation"],
  }),
  github({
    slug: "unitree-robotics",
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["unitree.com"],
    name: "Unitree Robotics",
    owner: "Unitree Robotics",
    repository: "unitreerobotics/unitree_rl_gym",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["humanoid", "robot-learning", "simulation"],
  }),
  website({
    slug: "fourier-intelligence",
    pipelineStages: ["acquisition-route", "production-operations", "quality-training-feedback"],
    identityHosts: ["fourierintelligence.com"],
    name: "Fourier Intelligence",
    owner: "Fourier Intelligence",
    homepageUrl: "https://fourierintelligence.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["humanoid", "data-collection", "training"],
  }),
  website({
    slug: "ubtech-robotics",
    pipelineStages: ["demand-definition", "production-operations"],
    identityHosts: ["ubtrobot.com"],
    name: "UBTECH Robotics",
    owner: "UBTECH Robotics",
    homepageUrl: "https://www.ubtrobot.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["humanoid", "industrial-scenarios", "training"],
  }),
  website({
    slug: "robotera",
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["robotera.com"],
    name: "RobotEra",
    owner: "RobotEra",
    homepageUrl: "https://www.robotera.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["humanoid", "teleoperation", "robot-learning"],
  }),
  website({
    slug: "astribot",
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["astribot.com"],
    name: "Astribot",
    owner: "Astribot",
    homepageUrl: "https://www.astribot.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["humanoid", "manipulation", "data-collection"],
  }),
  website({
    slug: "nexdata-embodied-ai",
    pipelineStages: [
      "multimodal-capture",
      "production-operations",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["nexdata.ai"],
    name: "Nexdata Embodied AI",
    owner: "Nexdata",
    homepageUrl: "https://www.nexdata.ai/industries/embodied-ai",
    tier: 2,
    role: "primary",
    region: "CN",
    language: "en",
    category: "data-service",
    topics: ["data-collection", "annotation", "evaluation"],
  }),
  website({
    slug: "discover-robotics-data",
    pipelineStages: [
      "acquisition-route",
      "multimodal-capture",
      "production-operations",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["discover-robotics.com"],
    name: "DISCOVER Robotics Data Acquisition",
    owner: "DISCOVER Robotics",
    homepageUrl: "https://www.discover-robotics.com/en/data-collection",
    tier: 2,
    role: "primary",
    region: "CN",
    language: "en",
    category: "data-service",
    topics: ["data-collection", "data-management", "training"],
  }),
  website({
    slug: "gesen-ai",
    pipelineStages: [
      "production-operations",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["gesenai.cn"],
    name: "GESEN AI",
    owner: "Zhejiang Gesen Intelligence Technology",
    homepageUrl: "https://www.gesenai.cn/",
    tier: 2,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "data-service",
    topics: ["data-collection", "data-cleaning", "robot-training"],
  }),
  website({
    slug: "galaxea-ai",
    pipelineStages: ["acquisition-route", "production-operations", "quality-training-feedback"],
    identityHosts: ["galaxea-ai.com"],
    name: "Galaxea AI",
    owner: "Galaxea AI",
    homepageUrl: "https://www.galaxea-ai.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "peer-evidence",
    topics: ["robot-data", "open-source", "mobile-manipulation"],
  }),
  website({
    slug: "physical-intelligence",
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["physicalintelligence.company"],
    name: "Physical Intelligence",
    owner: "Physical Intelligence",
    homepageUrl: "https://www.physicalintelligence.company/blog",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "peer-evidence",
    topics: ["robot-foundation-model", "data-mixture", "evaluation"],
  }),
  website({
    slug: "samr-standards",
    endpoint: "https://www.samr.gov.cn/bzjss/",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Fixture contract verified. Automation policy and owner-terms review remain pending; do not enable observation.",
    html: {
      records: ".contentLeft0102box",
      title: {
        selector: ".contentLeft0102 > a",
      },
      link: {
        selector: ".contentLeft0102 > a",
        attribute: "href",
      },
      detail: {
        take: 3,
        title: {
          selector: ".zt_xilan_03",
        },
        date: {
          selector: ".zt_xilan_04",
          prefix: "发布时间：",
          format: "ymd",
          semantic: "published",
        },
        alternateDate: {
          selector: "meta[name='PubDate']",
          attribute: "content",
        },
      },
    },
    name: "SAMR Standards",
    owner: "State Administration for Market Regulation",
    homepageUrl: "https://www.samr.gov.cn/bzjss/",
    tier: 1,
    role: "policy",
    region: "CN",
    language: "zh-CN",
    category: "standard-policy",
    topics: ["data-engineering-standards", "quality-training-feedback"],
    pipelineStages: ["data-engineering-standards", "quality-training-feedback"],
    identityHosts: ["samr.gov.cn", "std.samr.gov.cn", "openstd.samr.gov.cn"],
    mapStatus: "substitute",
    substituteFor: ["cesi-embodied-standards"],
  }),
  manual({
    slug: "miit-embodied-policy",
    name: "MIIT Embodied Policy",
    owner: "Ministry of Industry and Information Technology",
    homepageUrl:
      "https://www.miit.gov.cn/zwgk/zcwj/wjfb/tz/art/2026/art_f291ccd3da4c47ce95741de63cc088e6.html",
    tier: 1,
    role: "policy",
    region: "CN",
    language: "zh-CN",
    category: "standard-policy",
    topics: ["demand-definition", "production-operations", "quality-training-feedback"],
    pipelineStages: ["demand-definition", "production-operations", "quality-training-feedback"],
    identityHosts: ["miit.gov.cn"],
  }),
  manual({
    slug: "cesi-embodied-standards",
    name: "CESI Embodied Standards",
    owner: "China Electronics Standardization Institute",
    homepageUrl: "https://www.cesi.cn/",
    tier: 1,
    role: "policy",
    region: "CN",
    language: "zh-CN",
    category: "standard-policy",
    topics: ["data-engineering-standards", "quality-training-feedback"],
    pipelineStages: ["data-engineering-standards", "quality-training-feedback"],
    identityHosts: ["cesi.cn"],
    mapStatus: "restricted",
    restrictionNote:
      "Official site returned a JavaScript cloud-protection challenge; do not bypass it.",
    maintenanceStatus: "restricted",
  }),
  website({
    slug: "beijing-humanoid-center",
    endpoint: "https://www.x-humanoid.com/news.html",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Fixture contract verified. Automation policy and owner-terms review remain pending; do not enable observation.",
    html: {
      records: ".item.col-md-4",
      title: {
        selector: ".title_body .multiline-ellipsis",
      },
      link: {
        selector: ".title_body .multiline-ellipsis",
        attribute: "href",
      },
      date: {
        selector: ".item2 > .col-md-6:not(.text-right)",
        format: "ymd",
        semantic: "published",
      },
    },
    name: "Beijing Humanoid Robot Innovation Center",
    owner: "Beijing Humanoid Robot Innovation Center",
    homepageUrl: "https://x-humanoid.com/about.html",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["acquisition-route", "production-operations", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "production-operations", "quality-training-feedback"],
    identityHosts: ["x-humanoid.com", "x-humanoid-robomind.github.io"],
  }),
  manual({
    slug: "shanghai-humanoid-center",
    name: "Shanghai Humanoid Robot Innovation Center",
    owner: "Humanoid Robot Shanghai",
    homepageUrl: "https://www.openloong.net/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["production-operations", "data-engineering-standards", "quality-training-feedback"],
    pipelineStages: [
      "production-operations",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["openloong.net"],
  }),
  manual({
    slug: "shanghai-embodied-policy",
    name: "Shanghai Embodied Policy",
    owner: "Shanghai Municipal Government",
    homepageUrl:
      "https://www.shanghai.gov.cn/nw12344/20250806/f9cb53544505426d807055ca20bd69fc.html",
    tier: 1,
    role: "policy",
    region: "CN",
    language: "zh-CN",
    category: "standard-policy",
    topics: ["demand-definition", "acquisition-route", "production-operations"],
    pipelineStages: ["demand-definition", "acquisition-route", "production-operations"],
    identityHosts: ["shanghai.gov.cn"],
  }),
  manual({
    slug: "beijing-embodied-policy",
    name: "Beijing Embodied Policy",
    owner: "Beijing Municipal Government",
    homepageUrl: "https://www.beijing.gov.cn/zhengce/zhengcefagui/202503/t20250304_4024579.html",
    tier: 1,
    role: "policy",
    region: "CN",
    language: "zh-CN",
    category: "standard-policy",
    topics: ["demand-definition", "acquisition-route", "production-operations"],
    pipelineStages: ["demand-definition", "acquisition-route", "production-operations"],
    identityHosts: ["beijing.gov.cn"],
  }),
  manual({
    slug: "shenzhen-embodied-policy",
    name: "Shenzhen Embodied Policy",
    owner: "Shenzhen Municipal Government",
    homepageUrl: "https://stic.sz.gov.cn/gkmlpt/content/12/12052/mpost_12052515.html",
    tier: 1,
    role: "policy",
    region: "CN",
    language: "zh-CN",
    category: "standard-policy",
    topics: ["demand-definition", "acquisition-route", "production-operations"],
    pipelineStages: ["demand-definition", "acquisition-route", "production-operations"],
    identityHosts: ["stic.sz.gov.cn"],
  }),
  manual({
    slug: "guangzhou-embodied-policy",
    name: "Guangzhou Embodied Policy",
    owner: "Guangzhou Municipal Government",
    homepageUrl: "https://gxj.gz.gov.cn/yw/zchb/zcwj/cyzc/content/post_10886099.html",
    tier: 1,
    role: "policy",
    region: "CN",
    language: "zh-CN",
    category: "standard-policy",
    topics: ["demand-definition", "production-operations", "data-engineering-standards"],
    pipelineStages: ["demand-definition", "production-operations", "data-engineering-standards"],
    identityHosts: ["gxj.gz.gov.cn"],
  }),
  manual({
    slug: "galbot",
    name: "Galbot",
    owner: "Galbot",
    homepageUrl: "https://www.galbot.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["galbot.com"],
  }),
  manual({
    slug: "limx-dynamics",
    name: "LimX Dynamics",
    owner: "LimX Dynamics",
    homepageUrl: "https://www.limxdynamics.com/zh",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["limxdynamics.com"],
  }),
  manual({
    slug: "noetix-robotics",
    name: "Noetix Robotics",
    owner: "Noetix Robotics",
    homepageUrl: "https://en.noetixrobotics.com/about.html",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["acquisition-route", "multimodal-capture"],
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["en.noetixrobotics.com"],
  }),
  manual({
    slug: "engineai",
    name: "EngineAI",
    owner: "EngineAI Robotics",
    homepageUrl: "https://www.engineai.com.cn/policy",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["multimodal-capture", "data-engineering-standards"],
    pipelineStages: ["multimodal-capture", "data-engineering-standards"],
    identityHosts: ["engineai.com.cn"],
  }),
  manual({
    slug: "xpeng-robotics",
    name: "XPeng Robotics",
    owner: "XPeng",
    homepageUrl: "https://www.xiaopeng.com/news/company_news/5511.html",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["xiaopeng.com", "xpeng.com"],
  }),
  manual({
    slug: "tencent-robotics-x",
    name: "Tencent Robotics X and Tairos",
    owner: "Tencent",
    homepageUrl: "https://tairos.tencent.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["tencent.com", "roboticsx.tencent.com", "tairos.tencent.com"],
  }),
  manual({
    slug: "bytedance-seed-robotics",
    name: "ByteDance Seed Robotics",
    owner: "ByteDance",
    homepageUrl: "https://seed.bytedance.com/zh/direction/robotics",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["multimodal-capture", "quality-training-feedback"],
    pipelineStages: ["multimodal-capture", "quality-training-feedback"],
    identityHosts: ["bytedance.com", "seed.bytedance.com", "picoxr.com"],
  }),
  governed({
    slug: "internrobotics",
    endpoint: "https://api.github.com/repos/InternRobotics/InternUtopia/releases?per_page=3",
    adapter: "json-api",
    acquisition: "api",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Public release API fixture verified. Policy review remains pending; do not enable observation. GitHub Atom paths are robots-disallowed.",
    name: "InternRobotics",
    owner: "Shanghai AI Laboratory",
    homepageUrl: "https://github.com/InternRobotics",
    tier: 1,
    role: "research",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["acquisition-route", "data-engineering-standards", "quality-training-feedback"],
    pipelineStages: [
      "acquisition-route",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["shlab.org.cn", "pjlab.org.cn", "internrobotics.shlab.org.cn"],
  }),
  governed({
    slug: "horizon-holomotion",
    endpoint: "https://api.github.com/repos/HorizonRobotics/HoloMotion/releases?per_page=3",
    adapter: "json-api",
    acquisition: "api",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Public release API fixture verified. Policy review remains pending; do not enable observation. GitHub Atom paths are robots-disallowed.",
    name: "Horizon HoloMotion",
    owner: "Horizon Robotics",
    homepageUrl: "https://github.com/HorizonRobotics/HoloMotion",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: [
      "acquisition-route",
      "multimodal-capture",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    pipelineStages: [
      "acquisition-route",
      "multimodal-capture",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["horizon.auto"],
  }),
  manual({
    slug: "tsinghua-air-robotics",
    name: "Tsinghua AIR Robotics",
    owner: "Tsinghua University AIR",
    homepageUrl: "https://air.tsinghua.edu.cn/kxyj/znjqr.htm",
    tier: 1,
    role: "research",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["air.tsinghua.edu.cn"],
  }),
  website({
    slug: "opendrivelab",
    endpoint: "https://opendrivelab.com/",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Fixture contract verified. Automation policy and owner-terms review remain pending; do not enable observation.",
    html: {
      records: "div:has(> span[data-slot='badge'])",
      title: {
        selector: "> div > span",
      },
      link: {
        selector: "a[href^='/']:not([href='//'])",
        attribute: "href",
      },
      date: {
        selector: "> span[data-slot='badge']",
        format: "ymd",
        semantic: "published",
      },
    },
    name: "OpenDriveLab",
    owner: "OpenDriveLab",
    homepageUrl: "https://opendrivelab.com/",
    tier: 1,
    role: "research",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["opendrivelab.com"],
  }),
  manual({
    slug: "deep-robotics",
    name: "DEEP Robotics",
    owner: "DEEP Robotics",
    homepageUrl: "https://github.com/DeepRoboticsLab/deep-robotics-simulation",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["deeprobotics.cn"],
  }),
  manual({
    slug: "datatang-embodied",
    name: "DataTang Embodied Data",
    owner: "DataTang",
    homepageUrl: "https://datatang.com/news/1222",
    tier: 2,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "data-service",
    topics: [
      "acquisition-route",
      "multimodal-capture",
      "production-operations",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    pipelineStages: [
      "acquisition-route",
      "multimodal-capture",
      "production-operations",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["datatang.com", "datatang.ai", "datatang.net"],
  }),
  website({
    slug: "pnp-robotics",
    endpoint: "https://www.pnprobotics.com/",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Fixture contract verified. Automation policy and owner-terms review remain pending; do not enable observation.",
    html: {
      records: ".m_news_info",
      title: {
        selector: ".news_title .article_title",
      },
      link: {
        selector: ".news_title .article_title",
        attribute: "href",
      },
      detail: {
        take: 2,
        title: {
          selector: ".newsDetail > h1.title",
        },
        date: {
          selector: ".newsInfoWrap .leftInfo > .newsInfo:first-child",
          prefix: "发表时间：",
          format: "ymd",
          semantic: "published",
        },
      },
    },
    name: "PNP Robotics",
    owner: "PNP Robotics",
    homepageUrl: "https://www.pnprobotics.com/",
    tier: 2,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "data-service",
    topics: ["acquisition-route", "multimodal-capture", "production-operations"],
    pipelineStages: ["acquisition-route", "multimodal-capture", "production-operations"],
    identityHosts: ["pnprobotics.com"],
  }),
  manual({
    slug: "noitom",
    name: "Noitom",
    owner: "Noitom",
    homepageUrl: "https://www.noitom.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "capture-tool",
    topics: ["acquisition-route", "multimodal-capture"],
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["noitom.com", "noitom.com.cn"],
  }),
  manual({
    slug: "pico-motion-tracking",
    name: "PICO Motion Tracking",
    owner: "ByteDance",
    homepageUrl: "https://www.picoxr.com/global/products/pico-motion-tracker",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "capture-tool",
    topics: ["multimodal-capture"],
    pipelineStages: ["multimodal-capture"],
    identityHosts: ["bytedance.com", "seed.bytedance.com", "picoxr.com"],
  }),
  manual({
    slug: "robotwin",
    name: "RoboTwin",
    owner: "RoboTwin Project",
    homepageUrl: "https://robotwin-platform.github.io/",
    tier: 1,
    role: "research",
    region: "CN",
    language: "en",
    category: "dataset-benchmark",
    topics: ["demand-definition", "acquisition-route", "quality-training-feedback"],
    pipelineStages: ["demand-definition", "acquisition-route", "quality-training-feedback"],
    identityHosts: ["robotwin-platform.github.io"],
  }),
  manual({
    slug: "orbbec",
    name: "Orbbec",
    owner: "Orbbec",
    homepageUrl: "https://www.orbbec.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "capture-tool",
    topics: ["multimodal-capture"],
    pipelineStages: ["multimodal-capture"],
    identityHosts: ["orbbec.com"],
  }),
  manual({
    slug: "agilex-data-capture",
    name: "AgileX Data Capture",
    owner: "AgileX Robotics",
    homepageUrl: "https://www.agilex.ai/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "capture-tool",
    topics: ["acquisition-route", "multimodal-capture"],
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["agilex.ai"],
  }),
  manual({
    slug: "dobot-data-capture",
    name: "Dobot Data Capture",
    owner: "Dobot Robotics",
    homepageUrl: "https://www.dobot-robots.com/products",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "capture-tool",
    topics: ["acquisition-route", "multimodal-capture", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "multimodal-capture", "quality-training-feedback"],
    identityHosts: ["dobot-robots.com"],
  }),
  manual({
    slug: "paxini",
    name: "PaXini",
    owner: "PaXini",
    homepageUrl: "https://www.paxini.com/cn/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "capture-tool",
    topics: ["acquisition-route", "multimodal-capture", "data-engineering-standards"],
    pipelineStages: ["acquisition-route", "multimodal-capture", "data-engineering-standards"],
    identityHosts: ["paxini.com"],
  }),
  manual({
    slug: "dexforce",
    name: "DexForce",
    owner: "DexForce",
    homepageUrl: "https://www.dexforce.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["acquisition-route", "multimodal-capture", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "multimodal-capture", "quality-training-feedback"],
    identityHosts: ["dexforce.com"],
  }),
  manual({
    slug: "leju-training",
    name: "Leju Training Grounds",
    owner: "Leju Robotics",
    homepageUrl: "https://www.lejurobot.com/en",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["production-operations", "quality-training-feedback"],
    pipelineStages: ["production-operations", "quality-training-feedback"],
    identityHosts: ["lejurobot.com"],
  }),
  manual({
    slug: "linkerbot-data",
    name: "Linkerbot Data",
    owner: "Linkerbot",
    homepageUrl: "https://www.linkerbot.cn/data/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "capture-tool",
    topics: [
      "acquisition-route",
      "multimodal-capture",
      "production-operations",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    pipelineStages: [
      "acquisition-route",
      "multimodal-capture",
      "production-operations",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["linkerbot.cn"],
  }),
  manual({
    slug: "spirit-ai",
    name: "Spirit AI",
    owner: "Spirit AI",
    homepageUrl: "https://docs.spirit-ai.com/v2.6/sdk/data-format.html",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["multimodal-capture", "data-engineering-standards", "quality-training-feedback"],
    pipelineStages: [
      "multimodal-capture",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["docs.spirit-ai.com"],
  }),
  website({
    slug: "figure-ai",
    html: {
      records: "a.article-list-item",
      title: {
        selector: ".article-list-item__heading",
      },
      link: {
        attribute: "href",
      },
      date: {
        selector: "time",
        attribute: "datetime",
        format: "iso",
        semantic: "published",
      },
    },
    endpoint: "https://www.figure.ai/news",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Public news metadata fixture verified. Robots does not block news; owner-terms review remains pending before observation.",
    name: "Figure AI",
    owner: "Figure AI",
    homepageUrl: "https://www.figure.ai/helix",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["figure.ai"],
  }),
  website({
    slug: "one-x",
    endpoint: "https://www.1x.tech/ai",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Fixture contract verified. Automation policy and owner-terms review remain pending; do not enable observation.",
    html: {
      records: "script#__NEXT_DATA__",
      jsonPath: "props.pageProps.ai.*.blogLink",
      title: {
        path: "title",
      },
      link: {
        path: "slug.current",
        prefix: "/discover/",
      },
      date: {
        path: "date",
        format: "iso",
        semantic: "published",
      },
    },
    name: "1X",
    owner: "1X Technologies",
    homepageUrl: "https://www.1x.tech/ai",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["1x.tech"],
  }),
  manual({
    slug: "apptronik",
    name: "Apptronik",
    owner: "Apptronik",
    homepageUrl: "https://apptronik.com/company/press-releases",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["production-operations", "quality-training-feedback"],
    pipelineStages: ["production-operations", "quality-training-feedback"],
    identityHosts: ["apptronik.com"],
  }),
  manual({
    slug: "sanctuary-ai",
    name: "Sanctuary AI",
    owner: "Sanctuary AI",
    homepageUrl: "https://sanctuary.ai/news/",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["multimodal-capture", "quality-training-feedback"],
    pipelineStages: ["multimodal-capture", "quality-training-feedback"],
    identityHosts: ["sanctuary.ai"],
  }),
  manual({
    slug: "rai-institute",
    name: "RAI Institute",
    owner: "Robotics and AI Institute",
    homepageUrl: "https://rai-inst.com/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["rai-inst.com"],
  }),
  manual({
    slug: "toyota-research-robotics",
    name: "Toyota Research Institute Robotics",
    owner: "Toyota Research Institute",
    homepageUrl: "https://www.tri.global/our-work/robotics",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["acquisition-route", "quality-training-feedback"],
    pipelineStages: ["acquisition-route", "quality-training-feedback"],
    identityHosts: ["tri.global"],
    mapStatus: "restricted",
    restrictionNote: "Official robotics page returned HTTP 403 on recheck; manual review only.",
    maintenanceStatus: "restricted",
  }),
  governed({
    slug: "nvidia-isaac-groot",
    endpoint: "https://api.github.com/repos/NVIDIA/Isaac-GR00T/releases?per_page=3",
    adapter: "json-api",
    acquisition: "api",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Public release API fixture verified. Policy review remains pending; do not enable observation. GitHub Atom paths are robots-disallowed.",
    name: "NVIDIA Isaac GR00T",
    owner: "NVIDIA",
    homepageUrl: "https://github.com/NVIDIA/Isaac-GR00T",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["acquisition-route", "data-engineering-standards", "quality-training-feedback"],
    pipelineStages: [
      "acquisition-route",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["nvidia.com", "developer.nvidia.com"],
  }),
  website({
    slug: "nist-physical-ai",
    endpoint: "https://www.nist.gov/programs-projects/physical-ai-and-data-generation-robotics",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Fixture contract verified. Automation policy and owner-terms review remain pending; do not enable observation.",
    html: {
      records: "html",
      title: {
        selector: "meta[property='og:title']",
        attribute: "content",
      },
      date: {
        selector: ".text-italic.font-sans-2xs",
        prefix: "Created ",
        format: "month-name",
        semantic: "created",
      },
    },
    name: "NIST Physical AI",
    owner: "National Institute of Standards and Technology",
    homepageUrl: "https://www.nist.gov/programs-projects/physical-ai-and-data-generation-robotics",
    tier: 1,
    role: "policy",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["demand-definition", "data-engineering-standards", "quality-training-feedback"],
    pipelineStages: [
      "demand-definition",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["nist.gov"],
  }),
  manual({
    slug: "iso-tc299",
    name: "ISO TC 299 Robotics",
    owner: "International Organization for Standardization",
    homepageUrl: "https://www.iso.org/committee/5915511.html",
    tier: 1,
    role: "policy",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["demand-definition", "data-engineering-standards", "quality-training-feedback"],
    pipelineStages: [
      "demand-definition",
      "data-engineering-standards",
      "quality-training-feedback",
    ],
    identityHosts: ["iso.org"],
    mapStatus: "restricted",
    restrictionNote:
      "Public committee metadata only; standard texts may require purchase and must not be scraped.",
    maintenanceStatus: "restricted",
  }),
  website({
    slug: "itu-robot-data-factory",
    endpoint: "https://www.itu.int/ITU-T/workprog/wp_item.aspx?isn=24285",
    adapterVersion: "1",
    lifecycleStatus: "draft",
    maintenanceStatus: "manual",
    robotsPolicy:
      "Fixture contract verified. Automation policy and owner-terms review remain pending; do not enable observation.",
    html: {
      records: "table:has(#ctl00_ContentPlaceHolder1_rpt_main_ctl00_lbl_subject)",
      title: {
        selector: "#ctl00_ContentPlaceHolder1_rpt_main_ctl00_lbl_subject",
      },
      date: {
        selector: "#ctl00_ContentPlaceHolder1_rpt_main_ctl00_lbl_first_registration_date",
        format: "ymd",
        semantic: "registered",
      },
    },
    name: "ITU Robot Data Factory",
    owner: "International Telecommunication Union",
    homepageUrl: "https://www.itu.int/ITU-T/workprog/wp_item.aspx?isn=24285",
    tier: 1,
    role: "policy",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["production-operations", "data-engineering-standards"],
    pipelineStages: ["production-operations", "data-engineering-standards"],
    identityHosts: ["itu.int"],
  }),
  manual({
    slug: "manus",
    name: "MANUS",
    owner: "MANUS",
    homepageUrl: "https://www.manus-meta.com/",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["acquisition-route", "multimodal-capture"],
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["manus-meta.com"],
  }),
  manual({
    slug: "xsens",
    name: "Xsens",
    owner: "Xsens Technologies",
    homepageUrl: "https://www.xsens.com/",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["acquisition-route", "multimodal-capture"],
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["xsens.com", "movella.com"],
  }),
  manual({
    slug: "senseglove",
    name: "SenseGlove",
    owner: "SenseGlove",
    homepageUrl: "https://www.senseglove.com/",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["acquisition-route", "multimodal-capture"],
    pipelineStages: ["acquisition-route", "multimodal-capture"],
    identityHosts: ["senseglove.com"],
  }),
  manual({
    slug: "realsense",
    name: "RealSense",
    owner: "RealSense",
    homepageUrl: "https://www.realsenseai.com/",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["multimodal-capture"],
    pipelineStages: ["multimodal-capture"],
    identityHosts: ["realsenseai.com", "realsense.com"],
  }),
];

export const embodiedSourceSlugs = new Set(embodiedSourceCatalog.map((source) => source.slug));

export const embodiedSourceCategories = new Set<SourceCategory>(
  embodiedSourceCatalog.map((source) => source.category),
);
