import type { CatalogSource, SourceCategory } from "../sources.js";

export type EmbodiedCatalogSource = CatalogSource & {
  owner: string;
  robotsPolicy: string;
  freshnessSloHours: number;
  adapterVersion: string;
};

type SourceInput = Pick<
  EmbodiedCatalogSource,
  | "slug"
  | "name"
  | "owner"
  | "homepageUrl"
  | "endpoint"
  | "adapter"
  | "tier"
  | "role"
  | "region"
  | "language"
  | "category"
  | "acquisition"
  | "topics"
> &
  Partial<
    Pick<
      EmbodiedCatalogSource,
      | "authorityScore"
      | "qualityScore"
      | "maintenanceStatus"
      | "cadence"
      | "licenseNote"
      | "robotsPolicy"
      | "freshnessSloHours"
      | "adapterVersion"
      | "identityHosts"
    >
  >;

const governed = (input: SourceInput): EmbodiedCatalogSource => ({
  ...input,
  authorityScore: input.authorityScore ?? 85,
  qualityScore: input.qualityScore ?? 70,
  enabled: false,
  lifecycleStatus: "shadow",
  maintenanceStatus: input.maintenanceStatus ?? "candidate",
  cadence: input.cadence ?? "weekly",
  licenseNote:
    input.licenseNote ??
    "Use public metadata and short factual excerpts only; retain attribution and verify project-specific license terms before reuse.",
  robotsPolicy:
    input.robotsPolicy ??
    "Respect published robots rules and terms; stop collection when automated access is not explicitly allowed.",
  freshnessSloHours: input.freshnessSloHours ?? 168,
  adapterVersion: input.adapterVersion ?? "1",
  identityHosts: input.identityHosts ?? [new URL(input.homepageUrl).hostname],
});

const github = (
  input: Omit<SourceInput, "endpoint" | "adapter" | "acquisition" | "homepageUrl"> & {
    repository: string;
  },
) =>
  governed({
    ...input,
    homepageUrl: `https://github.com/${input.repository}`,
    endpoint: `https://github.com/${input.repository}/releases.atom`,
    adapter: "github-releases",
    acquisition: "github",
  });

const website = (
  input: Omit<SourceInput, "endpoint" | "adapter" | "acquisition"> & { endpoint?: string },
) =>
  governed({
    ...input,
    endpoint: input.endpoint ?? input.homepageUrl,
    adapter: "web-scraper",
    acquisition: "html",
  });

export const legacySourcePolicy = {
  contentScope: "legacy-ai",
  enabled: false,
  observationEnabled: false,
  lifecycleStatus: "retired",
  maintenanceStatus: "retired",
} as const;

export const embodiedSourceCatalog: EmbodiedCatalogSource[] = [
  website({
    slug: "droid-project",
    name: "DROID Dataset",
    owner: "DROID Dataset Team",
    homepageUrl: "https://droid-dataset.github.io/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["teleoperation", "robot-manipulation", "distributed-collection"],
  }),
  website({
    slug: "bridge-data-v2",
    name: "BridgeData V2",
    owner: "UC Berkeley RAIL",
    homepageUrl: "https://rail-berkeley.github.io/bridgedata/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["teleoperation", "autonomous-rollout", "manipulation"],
  }),
  website({
    slug: "open-x-embodiment",
    name: "Open X-Embodiment",
    owner: "Open X-Embodiment Collaboration",
    homepageUrl: "https://robotics-transformer-x.github.io/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["cross-embodiment", "rlds", "robot-learning"],
  }),
  website({
    slug: "rh20t",
    name: "RH20T",
    owner: "Shanghai Jiao Tong University",
    homepageUrl: "https://rh20t.github.io/",
    tier: 1,
    role: "research",
    region: "CN",
    language: "en",
    category: "dataset-benchmark",
    topics: ["multimodal-capture", "force", "robot-manipulation"],
  }),
  website({
    slug: "roboset",
    name: "RoboSet",
    owner: "RoboSet Project",
    homepageUrl: "https://robopen.github.io/roboset/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["robot-demonstration", "manipulation", "benchmark"],
  }),
  website({
    slug: "robomind",
    name: "RoboMIND",
    owner: "Open X-Humanoid",
    homepageUrl: "https://x-humanoid-robomind.github.io/",
    tier: 1,
    role: "research",
    region: "CN",
    language: "en",
    category: "dataset-benchmark",
    topics: ["multi-embodiment", "teleoperation", "digital-twin"],
  }),
  github({
    slug: "agibot-world",
    name: "AgiBot World",
    owner: "OpenDriveLab and AgiBot",
    repository: "OpenDriveLab/AgiBot-World",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["bimanual-manipulation", "large-scale-data", "robot-foundation-model"],
  }),
  github({
    slug: "behavior-1k",
    name: "BEHAVIOR-1K",
    owner: "Stanford Vision and Learning Lab",
    repository: "StanfordVL/BEHAVIOR-1K",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["task-definition", "simulation", "household-activities"],
  }),
  github({
    slug: "libero-benchmark",
    name: "LIBERO",
    owner: "Lifelong Robot Learning Lab",
    repository: "Lifelong-Robot-Learning/LIBERO",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["benchmark", "lifelong-learning", "manipulation"],
  }),
  github({
    slug: "robocasa",
    name: "RoboCasa",
    owner: "RoboCasa Project",
    repository: "robocasa/robocasa",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["simulation", "synthetic-data", "household-manipulation"],
  }),
  github({
    slug: "calvin-benchmark",
    name: "CALVIN",
    owner: "CALVIN Project",
    repository: "mees/calvin",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["benchmark", "language-conditioned", "long-horizon"],
  }),
  website({
    slug: "holoassist",
    name: "HoloAssist",
    owner: "Microsoft Research",
    homepageUrl: "https://holoassist.github.io/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["egocentric-video", "human-demonstration", "multimodal"],
  }),
  website({
    slug: "ego-exo4d",
    name: "Ego-Exo4D",
    owner: "Ego4D Consortium",
    homepageUrl: "https://ego-exo4d-data.org/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["egocentric-video", "exo-centric-video", "human-demonstration"],
  }),
  website({
    slug: "ario-dataset",
    name: "ARIO",
    owner: "ARIO Project",
    homepageUrl: "https://imaei.github.io/project_pages/ario/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "dataset-benchmark",
    topics: ["unified-representation", "multi-embodiment", "data-engineering"],
  }),
  github({
    slug: "huggingface-lerobot",
    name: "LeRobot",
    owner: "Hugging Face",
    repository: "huggingface/lerobot",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["dataset-format", "robot-learning", "open-source"],
    freshnessSloHours: 72,
  }),
  github({
    slug: "google-rlds",
    name: "RLDS",
    owner: "Google Research",
    repository: "google-research/rlds",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["dataset-schema", "episodes", "data-engineering"],
  }),
  github({
    slug: "ros2-rosbag2",
    name: "ROS 2 rosbag2",
    owner: "Open Source Robotics Foundation",
    repository: "ros2/rosbag2",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["sensor-recording", "storage", "ros2"],
    freshnessSloHours: 72,
  }),
  github({
    slug: "foxglove-mcap",
    name: "MCAP",
    owner: "Foxglove",
    repository: "foxglove/mcap",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "standard-policy",
    topics: ["container-format", "sensor-data", "interoperability"],
  }),
  github({
    slug: "universal-manipulation-interface",
    name: "Universal Manipulation Interface",
    owner: "Stanford REAL",
    repository: "real-stanford/universal_manipulation_interface",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["human-demonstration", "portable-capture", "manipulation"],
  }),
  github({
    slug: "gello",
    name: "GELLO",
    owner: "GELLO Project",
    repository: "wuphilipp/gello_software",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["teleoperation", "low-cost-hardware", "demonstration"],
  }),
  github({
    slug: "aloha-act",
    name: "ALOHA and ACT",
    owner: "ALOHA Project",
    repository: "tonyzhaozh/act",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["bimanual-teleoperation", "action-chunking", "demonstration"],
  }),
  github({
    slug: "nvidia-isaac-sim",
    name: "NVIDIA Isaac Sim",
    owner: "NVIDIA",
    repository: "isaac-sim/IsaacSim",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["simulation", "synthetic-data", "sensor-simulation"],
    freshnessSloHours: 72,
  }),
  github({
    slug: "nvidia-isaac-lab",
    name: "NVIDIA Isaac Lab",
    owner: "NVIDIA",
    repository: "isaac-sim/IsaacLab",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["simulation", "robot-learning", "synthetic-data"],
    freshnessSloHours: 72,
  }),
  website({
    slug: "nvidia-isaac-teleop",
    name: "NVIDIA Isaac TeleOp",
    owner: "NVIDIA",
    homepageUrl: "https://developer.nvidia.com/isaac/sim",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "capture-tool",
    topics: ["teleoperation", "simulation", "demonstration"],
  }),
  website({
    slug: "google-deepmind-robotics",
    name: "Google DeepMind Robotics",
    owner: "Google DeepMind",
    homepageUrl: "https://deepmind.google/discover/blog/",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "robot-team",
    topics: ["robot-learning", "data-scaling", "evaluation"],
  }),
  github({
    slug: "unitree-robotics",
    name: "Unitree Robotics",
    owner: "Unitree Robotics",
    repository: "unitreerobotics/unitree_rl_gym",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["humanoid", "robot-learning", "simulation"],
  }),
  website({
    slug: "fourier-intelligence",
    name: "Fourier Intelligence",
    owner: "Fourier Intelligence",
    homepageUrl: "https://fourierintelligence.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["humanoid", "data-collection", "training"],
  }),
  website({
    slug: "ubtech-robotics",
    name: "UBTECH Robotics",
    owner: "UBTECH Robotics",
    homepageUrl: "https://www.ubtrobot.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "robot-team",
    topics: ["humanoid", "industrial-scenarios", "training"],
  }),
  website({
    slug: "robotera",
    name: "RobotEra",
    owner: "RobotEra",
    homepageUrl: "https://www.robotera.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["humanoid", "teleoperation", "robot-learning"],
  }),
  website({
    slug: "astribot",
    name: "Astribot",
    owner: "Astribot",
    homepageUrl: "https://www.astribot.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "robot-team",
    topics: ["humanoid", "manipulation", "data-collection"],
  }),
  website({
    slug: "nexdata-embodied-ai",
    name: "Nexdata Embodied AI",
    owner: "Nexdata",
    homepageUrl: "https://www.nexdata.ai/industries/embodied-ai",
    tier: 2,
    role: "primary",
    region: "CN",
    language: "en",
    category: "data-service",
    topics: ["data-collection", "annotation", "evaluation"],
  }),
  website({
    slug: "discover-robotics-data",
    name: "DISCOVER Robotics Data Acquisition",
    owner: "DISCOVER Robotics",
    homepageUrl: "https://www.discover-robotics.com/en/data-collection",
    tier: 2,
    role: "primary",
    region: "CN",
    language: "en",
    category: "data-service",
    topics: ["data-collection", "data-management", "training"],
  }),
  website({
    slug: "gesen-ai",
    name: "GESEN AI",
    owner: "Zhejiang Gesen Intelligence Technology",
    homepageUrl: "https://www.gesenai.cn/",
    tier: 2,
    role: "primary",
    region: "CN",
    language: "zh-CN",
    category: "data-service",
    topics: ["data-collection", "data-cleaning", "robot-training"],
  }),
  website({
    slug: "galaxea-ai",
    name: "Galaxea AI",
    owner: "Galaxea AI",
    homepageUrl: "https://www.galaxea-ai.com/",
    tier: 1,
    role: "primary",
    region: "CN",
    language: "en",
    category: "peer-evidence",
    topics: ["robot-data", "open-source", "mobile-manipulation"],
  }),
  website({
    slug: "physical-intelligence",
    name: "Physical Intelligence",
    owner: "Physical Intelligence",
    homepageUrl: "https://www.physicalintelligence.company/blog",
    tier: 1,
    role: "primary",
    region: "GLOBAL",
    language: "en",
    category: "peer-evidence",
    topics: ["robot-foundation-model", "data-mixture", "evaluation"],
  }),
  website({
    slug: "droid-consortium",
    name: "DROID Consortium",
    owner: "DROID Dataset Team",
    homepageUrl: "https://droid-dataset.github.io/",
    tier: 1,
    role: "research",
    region: "GLOBAL",
    language: "en",
    category: "peer-evidence",
    topics: ["distributed-collection", "robot-data", "quality"],
  }),
];

export const embodiedSourceSlugs = new Set(embodiedSourceCatalog.map((source) => source.slug));

export const embodiedSourceCategories = new Set<SourceCategory>(
  embodiedSourceCatalog.map((source) => source.category),
);
