import type { CuratedEventSeed } from "./history.js";

const event = (value: CuratedEventSeed): CuratedEventSeed => value;

/**
 * First-party milestones that explain how the current AI market formed.
 * Product/company lifecycle changes live in the narrative catalog so facts are not duplicated.
 */
export const earlyHistoryEvents = [
  event({
    slug: "stable-diffusion-public-release",
    title: "Stable Diffusion 公开发布：生成式 AI 第一次大规模进入开放生态",
    fact: "Stability AI 在 2022 年 8 月公开发布 Stable Diffusion 的模型与代码。",
    summary: "图像生成从少数实验室的封闭能力变成开发者可下载、改造和部署的开放基础设施。",
    technical: "潜空间扩散显著降低图像生成的训练与推理门槛，开放权重催生微调、插件与本地部署生态。",
    industry: "开放模型证明基础能力可以快速外溢到创作者工具、设计软件和大量垂直应用。",
    future: "持续观察开放模型许可、训练数据治理，以及图像和视频生成的产品化边界。",
    business:
      "创业团队首次能够不依赖封闭 API 构建差异化生成式视觉产品，但护城河必须来自工作流和分发。",
    category: "model-release",
    company: "Stability AI",
    keywords: ["Stable Diffusion", "开放权重", "图像生成"],
    scores: [99, 0, 94, 90],
    date: "2022-08-22T00:00:00.000Z",
    source: "stability-ai",
    url: "https://stability.ai/news-updates/stable-diffusion-public-release",
    tracks: ["tech-evolution", "commercialization", "global-innovation", "to-c", "to-d"],
    actors: [],
  }),
  event({
    slug: "chatgpt-research-preview",
    title: "ChatGPT 上线：大模型从能力演示变成大众产品",
    fact: "OpenAI 在 2022 年 11 月 30 日发布 ChatGPT research preview。",
    summary: "对话界面把指令微调与人类反馈训练转化为普通用户可以直接理解和持续使用的产品体验。",
    technical: "ChatGPT 基于 GPT-3.5 系列并使用 RLHF，使多轮对话、拒答和指令遵循成为可消费能力。",
    industry:
      "AI 竞争从论文和 API 跃迁为用户增长、产品入口与持续迭代的竞争，开启生成式 AI 产品周期。",
    future: "观察模型能力、使用成本、可靠性和分发如何共同决定通用助手的长期留存。",
    business: "企业和创业者需要从单点生成工具转向重新设计知识工作流程与用户入口。",
    category: "product-launch",
    company: "OpenAI",
    keywords: ["ChatGPT", "GPT-3.5", "RLHF", "对话产品"],
    scores: [100, 0, 100, 100],
    date: "2022-11-30T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/chatgpt/",
    tracks: ["tech-evolution", "commercialization", "agi-progress", "to-c", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "chatgpt-whisper-apis",
    title: "ChatGPT 与 Whisper API 发布：生成式 AI 进入开发者规模化接入阶段",
    fact: "OpenAI 在 2023 年 3 月发布 ChatGPT 和 Whisper API，并显著降低对话模型使用成本。",
    summary: "消费级产品验证后的模型能力被标准化为 API，应用创业和既有软件集成开始加速。",
    technical: "结构化消息接口和语音转写 API 让开发者可以组合多轮对话、语音输入与业务数据。",
    industry: "模型平台与应用层的边界开始形成，调用成本、稳定性和数据边界成为产品决策变量。",
    future: "观察模型厂商向工具、检索、Agent 运行时扩张后，独立应用层还能保留多少价值。",
    business: "团队可以低成本验证 AI 功能，但需要避免把简单 API 包装误当作可持续产品壁垒。",
    category: "developer-platform",
    company: "OpenAI",
    keywords: ["ChatGPT API", "Whisper", "开发者平台"],
    scores: [99, 0, 94, 95],
    date: "2023-03-01T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-chatgpt-and-whisper-apis/",
    tracks: ["commercialization", "model-economics", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "gpt-4-multimodal-release",
    title: "GPT-4 发布：大模型进入更可靠的多模态推理阶段",
    fact: "OpenAI 在 2023 年 3 月发布 GPT-4，支持图像输入并在多项专业考试中显著提升表现。",
    summary: "前沿模型从流畅生成进一步走向复杂推理和专业任务，企业开始认真评估大模型的生产价值。",
    technical: "规模化预训练、对齐与系统评测共同提升复杂任务性能，但幻觉和可解释性仍未解决。",
    industry: "旗舰模型成为平台竞争的核心资产，围绕模型访问、云算力和应用集成的联盟加深。",
    future: "观察基准提升能否稳定转化为真实任务成功率，以及多模态输入如何改变工作流。",
    business: "高价值知识工作获得更强自动化基础，同时需要为验证、权限和人工接管设计流程。",
    category: "model-release",
    company: "OpenAI",
    keywords: ["GPT-4", "多模态", "专业任务"],
    scores: [100, 0, 99, 98],
    date: "2023-03-14T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/gpt-4-research/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "microsoft-365-copilot-introduced",
    title: "Microsoft 365 Copilot 发布：大模型开始进入组织核心工作流",
    fact: "Microsoft 在 2023 年 3 月发布 Microsoft 365 Copilot，将大模型接入 Word、Excel、PowerPoint、Outlook 与 Teams。",
    summary: "生成式 AI 从独立聊天窗口进入企业软件与权限体系，Copilot 成为一类新的产品形态。",
    technical:
      "模型通过 Microsoft Graph 和应用上下文调用组织数据，同时引入权限、治理和可靠性要求。",
    industry: "掌握分发、数据和工作流的平台公司获得结构性优势，独立应用需要寻找更深的垂直价值。",
    future: "观察席位付费、真实使用频率、组织产能提升以及数据治理成本。",
    business: "企业采购应围绕具体任务和采用率衡量价值，而不是只按是否接入大模型判断数字化程度。",
    category: "enterprise-product",
    company: "Microsoft",
    keywords: ["Microsoft 365 Copilot", "企业软件", "工作流"],
    scores: [99, 0, 96, 98],
    date: "2023-03-16T00:00:00.000Z",
    source: "microsoft-ai",
    url: "https://blogs.microsoft.com/blog/2023/03/16/introducing-microsoft-365-copilot-your-copilot-for-work/",
    tracks: ["commercialization", "agi-progress", "investing", "to-b"],
    actors: ["microsoft"],
  }),
  event({
    slug: "chatgpt-plugins-launch",
    title: "ChatGPT Plugins 发布：模型开始连接外部工具与实时信息",
    fact: "OpenAI 在 2023 年 3 月发布 ChatGPT Plugins，允许模型调用第三方服务、计算与检索能力。",
    summary:
      "大模型从只生成文本转向调用外部系统，今天 Agent 工具使用和协议生态由此获得早期产品验证。",
    technical:
      "插件通过描述文件和 API 约定暴露工具，模型负责选择与调用，但权限和错误恢复仍很初级。",
    industry: "模型入口试图成为新的应用分发层，工具生态、平台控制与安全边界成为核心议题。",
    future: "观察开放协议、工具发现、授权、可靠执行和生态分成如何演进。",
    business: "开发者需要把能力设计成可组合工具，同时避免对单一入口和短期分发红利过度依赖。",
    category: "agent-platform",
    company: "OpenAI",
    keywords: ["ChatGPT Plugins", "工具调用", "Agent"],
    scores: [99, 0, 94, 92],
    date: "2023-03-23T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/chatgpt-plugins/",
    tracks: ["agi-progress", "commercialization", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-2-public-release",
    title: "Claude 2 发布：长上下文与安全路线形成前沿模型竞争分支",
    fact: "Anthropic 在 2023 年 7 月发布 Claude 2，并开放网页与 API 访问。",
    summary: "前沿模型市场不再只有单一领先者，长上下文、安全训练和企业服务成为差异化方向。",
    technical: "Claude 2 提升编码、推理和上下文长度，并延续 Constitutional AI 的对齐路线。",
    industry: "模型采购进入多供应商阶段，企业开始比较能力、价格、安全承诺和平台依赖。",
    future: "观察长上下文是否转化为可靠知识工作，以及安全训练如何影响可用性。",
    business: "企业可通过多模型路由降低锁定风险，但必须建立统一评测和数据治理边界。",
    category: "model-release",
    company: "Anthropic",
    keywords: ["Claude 2", "长上下文", "Constitutional AI"],
    scores: [99, 0, 92, 92],
    date: "2023-07-11T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-2",
    tracks: ["tech-evolution", "commercialization", "to-b", "to-d"],
    actors: ["anthropic"],
  }),
  event({
    slug: "china-generative-ai-interim-measures",
    title: "生成式 AI 服务管理暂行办法公布：中国市场形成明确的产品治理框架",
    fact: "中国七部门在 2023 年 7 月公布《生成式人工智能服务管理暂行办法》，自 8 月 15 日起施行。",
    summary:
      "面向公众的生成式 AI 服务获得明确监管框架，创新、备案、安全与内容责任被纳入同一产品周期。",
    technical: "训练数据、个人信息、生成内容与安全评估要求开始影响模型开发和上线流程。",
    industry: "中国 AI 产品竞争不仅取决于模型能力，也取决于合规工程、本地生态和服务规模。",
    future: "观察备案、行业应用、数据跨境和基础模型治理规则的持续演进。",
    business: "进入中国市场的团队需要把合规能力前置为产品与工程能力，而不是发布前的附加检查。",
    category: "policy",
    company: "中国国家互联网信息办公室",
    keywords: ["生成式 AI", "暂行办法", "治理", "中国"],
    scores: [100, 0, 91, 94],
    date: "2023-07-13T00:00:00.000Z",
    source: "cac-ai",
    url: "https://www.cac.gov.cn/2023-07/13/c_1690898327029107.htm",
    tracks: ["global-innovation", "commercialization", "to-c", "to-b", "to-g"],
    actors: [],
  }),
  event({
    slug: "llama-2-open-model-release",
    title: "Llama 2 发布：开放模型成为可持续的产业路线",
    fact: "Meta 与 Microsoft 在 2023 年 7 月发布 Llama 2，并允许研究和商业使用。",
    summary: "开放权重模型从实验性资产走向企业可部署底座，模型生态开始形成闭源与开放两条主线。",
    technical: "多尺寸基础与对话模型、公开评测和合作云分发降低了私有部署与二次训练门槛。",
    industry: "云厂商、模型社区和应用公司获得闭源 API 之外的选择，开放生态影响模型定价和创新速度。",
    future: "观察开放许可、衍生模型质量、企业采用和安全治理如何平衡。",
    business: "有数据与部署要求的团队可以控制模型栈，但需要承担评测、运维和安全责任。",
    category: "model-release",
    company: "Meta",
    keywords: ["Llama 2", "开放模型", "商业许可"],
    scores: [100, 0, 97, 95],
    date: "2023-07-18T00:00:00.000Z",
    source: "meta-ai",
    url: "https://about.fb.com/news/2023/07/llama-2/",
    tracks: ["tech-evolution", "model-economics", "global-innovation", "to-d", "to-b"],
    actors: ["meta"],
  }),
  event({
    slug: "qwen-7b-open-release",
    title: "Qwen-7B 开放：中文大模型进入开放生态建设阶段",
    fact: "Qwen 团队在 2023 年 8 月公开 Qwen-7B 与 Qwen-7B-Chat 的代码和模型权重。",
    summary:
      "中国团队开始用开放模型、开发工具和社区协作参与全球基础模型生态，而不只是提供本地聊天产品。",
    technical: "通用与对话模型同时开放，并提供量化、微调和推理支持，降低中文场景开发门槛。",
    industry: "中文开放模型成为开发者和企业可选底座，也为后续多尺寸、多模态模型矩阵奠定基础。",
    future: "观察开放模型在全球开发者采用、工具生态、企业部署和前沿能力上的持续贡献。",
    business: "中国开发者获得更适配本地语言与部署环境的基础模型，应用层可更快完成验证。",
    category: "model-release",
    company: "Alibaba Cloud",
    keywords: ["Qwen-7B", "开放模型", "中文大模型"],
    scores: [99, 0, 92, 92],
    date: "2023-08-03T00:00:00.000Z",
    source: "qwen",
    url: "https://github.com/QwenLM/Qwen",
    tracks: ["tech-evolution", "global-innovation", "model-economics", "to-d"],
    actors: ["alibaba"],
  }),
  event({
    slug: "mistral-7b-release",
    title: "Mistral 7B 发布：小模型效率成为开放生态的新竞争轴",
    fact: "Mistral AI 在 2023 年 9 月发布 Mistral 7B 开放模型。",
    summary: "更小但性能更强的模型证明产业价值并不只来自参数规模，架构效率和部署成本同样重要。",
    technical: "Grouped-query attention 与 sliding-window attention 改善推理效率和长序列处理。",
    industry: "欧洲创业公司以开放模型切入前沿竞争，强化了多区域、多路线模型生态。",
    future: "观察高效小模型在端侧、私有部署和任务路由中的真实采用。",
    business: "企业可以用更低基础设施成本部署专用模型，但需要按任务成功率而非参数量选型。",
    category: "model-release",
    company: "Mistral AI",
    keywords: ["Mistral 7B", "小模型", "推理效率"],
    scores: [99, 0, 91, 91],
    date: "2023-09-27T00:00:00.000Z",
    source: "mistral",
    url: "https://mistral.ai/news/announcing-mistral-7b",
    tracks: ["tech-evolution", "model-economics", "global-innovation", "to-d", "to-b"],
    actors: [],
  }),
  event({
    slug: "openai-devday-assistants-api",
    title: "OpenAI DevDay：模型平台向 Assistants、工具与定制能力扩张",
    fact: "OpenAI 在 2023 年 11 月 DevDay 发布 GPT-4 Turbo、Assistants API、新工具和定制模型计划。",
    summary: "模型 API 从单次生成扩张为带线程、检索、代码执行和函数调用的应用运行时。",
    technical: "更长上下文、JSON mode、函数调用、持久线程和托管工具降低了构建 AI 应用的工程门槛。",
    industry: "模型厂商开始吸收向量检索、Agent 编排和应用后端能力，平台与创业公司的边界重新划分。",
    future: "观察平台抽象能否提高长任务可靠性，以及开发者如何保留数据和产品控制权。",
    business: "团队应把平台便利与供应商锁定、成本结构、可观测性放在同一架构决策中。",
    category: "developer-platform",
    company: "OpenAI",
    keywords: ["DevDay", "Assistants API", "GPT-4 Turbo", "工具调用"],
    scores: [100, 0, 96, 97],
    date: "2023-11-06T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/new-models-and-developer-products-announced-at-devday/",
    tracks: ["agi-progress", "commercialization", "model-economics", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "gemini-1-multimodal-model-family",
    title: "Gemini 1.0 发布：原生多模态成为前沿模型平台标准",
    fact: "Google 在 2023 年 12 月发布 Gemini Ultra、Pro 与 Nano 三种尺寸的原生多模态模型。",
    summary: "前沿模型竞争从文本能力扩展到跨文本、图像、音频与视频的统一理解和多端部署。",
    technical: "同一模型家族覆盖数据中心到端侧，并围绕多模态训练、推理和工具使用展开。",
    industry: "搜索、Android、Cloud 和办公产品的分发能力被重新纳入模型竞争，平台生态的重要性上升。",
    future: "观察多模态能力在真实产品中的延迟、成本、可靠性与端云协同。",
    business: "企业需要比较模型能力之外的云、设备、数据和办公生态协同价值。",
    category: "model-release",
    company: "Google",
    keywords: ["Gemini 1.0", "原生多模态", "端侧模型"],
    scores: [100, 0, 97, 96],
    date: "2023-12-06T00:00:00.000Z",
    source: "deepmind",
    url: "https://deepmind.google/discover/blog/welcome-to-the-gemini-era/",
    tracks: [
      "tech-evolution",
      "agi-progress",
      "commercialization",
      "model-economics",
      "to-c",
      "to-b",
    ],
    actors: ["google"],
  }),
] as const satisfies readonly CuratedEventSeed[];
