export interface CuratedEventSeed {
  slug: string;
  title: string;
  fact: string;
  summary: string;
  technical: string;
  industry: string;
  future: string;
  business: string;
  category: string;
  company: string;
  keywords: readonly string[];
  scores: readonly [confidence: number, heat: number, impact: number, value: number];
  date: string;
  source: string;
  url: string;
  tracks: readonly string[];
  actors: readonly string[];
}

const event = (value: CuratedEventSeed): CuratedEventSeed => value;

/**
 * Editorially selected milestones for the two-year window. These are not a news archive:
 * every row must represent a durable change and link to a first-party source.
 */
export const historicalEvents = [
  event({
    slug: "llama-3-1-open-frontier-model",
    title: "Llama 3.1 405B 发布：开放权重第一次进入前沿模型竞争",
    fact: "Meta 发布 Llama 3.1 405B、70B 与 8B 模型，扩展到 128K 上下文并开放权重下载。",
    summary:
      "开放模型从追随路线进入可与闭源前沿模型直接比较的阶段，云厂商和开发者获得了可控制、可蒸馏的基础模型资产。",
    technical: "405B 模型、FP8 推理和合成数据/蒸馏工具链，证明开放生态也能组织超大规模训练与部署。",
    industry: "模型竞争从单一 API 变成闭源能力、开放权重和云分发三种路线并存。",
    future: "观察开放模型在真实企业工作负载中的使用量、衍生模型质量和推理成本。",
    business: "To D 团队获得更强的私有化和模型定制底座；模型厂商必须用产品和服务维持闭源溢价。",
    category: "model-release",
    company: "Meta",
    keywords: ["Llama 3.1", "开放权重", "405B", "蒸馏"],
    scores: [98, 0, 94, 91],
    date: "2024-07-23T00:00:00.000Z",
    source: "meta-ai",
    url: "https://ai.meta.com/blog/meta-llama-3-1/",
    tracks: ["tech-evolution", "agi-progress", "to-d", "commercialization"],
    actors: ["meta"],
  }),
  event({
    slug: "eu-ai-act-enters-force",
    title: "欧盟 AI Act 生效：通用模型进入正式合规周期",
    fact: "欧盟《人工智能法案》于 2024 年 8 月 1 日生效，并为通用模型和高风险系统设置分阶段义务。",
    summary: "AI 治理从原则讨论进入产品、模型、数据和供应链责任可执行的阶段。",
    technical: "模型文档、风险评估、透明度和系统级监控开始成为工程交付的一部分。",
    industry: "进入欧洲市场的模型与应用厂商需要把合规成本前置，政策能力成为 To B/To G 竞争门槛。",
    future: "观察 GPAI 义务、实施准则和高风险系统标准如何改变模型发布与采购。",
    business: "企业采购需要同时评估模型能力、部署地区、数据边界和法规责任。",
    category: "policy",
    company: "European Union",
    keywords: ["EU AI Act", "GPAI", "合规", "To G"],
    scores: [99, 0, 92, 90],
    date: "2024-08-01T00:00:00.000Z",
    source: "eu-ai-office",
    url: "https://digital-strategy.ec.europa.eu/en/news/european-artificial-intelligence-act-comes-force",
    tracks: ["commercialization", "investing", "to-b", "to-g"],
    actors: [],
  }),
  event({
    slug: "openai-o1-test-time-reasoning",
    title: "OpenAI o1 预览：能力扩展从训练 Scaling 转向推理时计算",
    fact: "OpenAI 发布 o1-preview 与 o1-mini，模型会在回答前投入更多推理计算。",
    summary: "推理时计算成为新的能力杠杆，行业开始从即时生成转向可分配思考预算的问题求解。",
    technical: "强化学习和长链推理让数学、代码与科学问题的性能随推理预算增长。",
    industry: "模型定价、延迟和能力不再是一条固定曲线，推理基础设施与任务路由的重要性上升。",
    future: "观察可验证推理、错误恢复、长链成本和推理过程可控性。",
    business: "高价值复杂任务可以接受更高延迟与成本，企业应按任务价值而非统一 token 单价选模。",
    category: "reasoning",
    company: "OpenAI",
    keywords: ["o1", "推理时计算", "强化学习", "reasoning"],
    scores: [99, 0, 98, 95],
    date: "2024-09-12T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-openai-o1-preview/",
    tracks: ["tech-evolution", "agi-progress", "model-economics", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "qwen-2-5-open-model-matrix",
    title: "Qwen2.5 发布：中国开放模型形成全尺寸与垂直模型矩阵",
    fact: "阿里巴巴 Qwen 团队发布 Qwen2.5 系列，覆盖 0.5B 到 72B，并扩展代码、数学和视觉语言模型。",
    summary:
      "中国模型竞争从单点旗舰转向尺寸、任务和部署形态完整覆盖，开放生态成为参与全球创新的重要路径。",
    technical: "统一模型家族降低了从端侧到云端、从通用到代码/数学任务的迁移成本。",
    industry: "阿里把模型、云 API 与开源社区连接起来，强化国内开发者分发和海外影响力。",
    future: "观察海外开发者采用、端侧部署、企业微调和与国际前沿模型的差距变化。",
    business: "国内 To D 团队获得低门槛模型底座，云厂商可通过托管、数据与工具链承接商业价值。",
    category: "model-release",
    company: "Alibaba / Qwen",
    keywords: ["Qwen2.5", "开放模型", "中国创新", "模型矩阵"],
    scores: [97, 0, 90, 90],
    date: "2024-09-19T00:00:00.000Z",
    source: "qwen",
    url: "https://qwenlm.github.io/blog/qwen2.5/",
    tracks: ["tech-evolution", "global-innovation", "to-d", "commercialization"],
    actors: ["alibaba"],
  }),
  event({
    slug: "claude-computer-use",
    title: "Claude Computer Use：模型开始直接操作通用软件界面",
    fact: "Anthropic 发布计算机使用能力测试版，Claude 可以观察屏幕并操作鼠标和键盘。",
    summary:
      "Agent 不再依赖每个应用提供专用 API，通用界面操作打开了更广的自动化空间，也暴露出可靠性与安全难题。",
    technical: "视觉定位、操作规划、状态反馈和长任务纠错第一次被组合成通用桌面执行能力。",
    industry: "RPA、浏览器自动化和模型 Agent 的边界开始融合。",
    future: "观察真实任务成功率、提示注入防护、权限隔离和人工接管。",
    business: "优先选择可验证、可回滚的窄流程，避免把演示成功率直接等同生产 ROI。",
    category: "agent",
    company: "Anthropic",
    keywords: ["Computer Use", "Agent", "GUI", "自动化"],
    scores: [98, 0, 95, 94],
    date: "2024-10-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/3-5-models-and-computer-use",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["anthropic"],
  }),
  event({
    slug: "model-context-protocol",
    title: "MCP 开源：Agent 的工具连接开始形成公共协议",
    fact: "Anthropic 开源 Model Context Protocol，用统一方式连接 AI 助手、数据源和工具。",
    summary:
      "模型与外部系统的连接从厂商私有插件走向可复用协议，Agent 生态开始出现类似 USB 的接口层。",
    technical: "Client、server、resource 与 tool 的标准化降低了上下文接入和工具复用成本。",
    industry: "竞争焦点从谁拥有最多插件转向谁控制客户端、权限、目录和运行时。",
    future: "观察跨厂商支持、鉴权、安全沙箱、远程 MCP 和企业治理。",
    business: "To D 公司应优先提供协议兼容的能力资产，而非只绑定单一模型平台。",
    category: "developer-platform",
    company: "Anthropic",
    keywords: ["MCP", "Agent 协议", "工具调用", "生态"],
    scores: [98, 0, 96, 96],
    date: "2024-11-25T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/model-context-protocol",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["anthropic"],
  }),
  event({
    slug: "gemini-2-agentic-era",
    title: "Gemini 2.0 发布：Google 把多模态模型推进到 Agent 系统",
    fact: "Google 发布 Gemini 2.0 Flash，并展示 Project Astra、Mariner 和代码 Agent 等原型。",
    summary:
      "模型能力被组织为感知、推理、工具使用和行动的完整系统，Google 开始把搜索、浏览器、Android 与模型结合。",
    technical: "原生多模态输入输出、工具调用和低延迟推理让实时 Agent 成为产品主线。",
    industry: "拥有浏览器、移动操作系统和搜索入口的平台获得结构性分发优势。",
    future: "观察原型向稳定产品转化的速度，以及跨产品权限和用户信任。",
    business: "独立 Agent 产品必须拥有 Google 难以复制的行业流程、数据或交付闭环。",
    category: "model-release",
    company: "Google DeepMind",
    keywords: ["Gemini 2.0", "Project Astra", "Mariner", "多模态 Agent"],
    scores: [98, 0, 96, 95],
    date: "2024-12-11T00:00:00.000Z",
    source: "google-ai",
    url: "https://blog.google/technology/google-deepmind/google-gemini-ai-update-december-2024/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-c", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "deepseek-v3-efficient-frontier",
    title: "DeepSeek-V3 开源：训练效率成为全球模型竞争的新变量",
    fact: "DeepSeek 发布并开放 DeepSeek-V3 权重与技术报告，采用 671B MoE、37B 激活参数和 FP8 训练。",
    summary:
      "DeepSeek 用架构、系统和工程协同压低前沿模型训练成本，证明不同资源条件可以形成独立的前沿创新路径。",
    technical: "MLA、DeepSeekMoE、无辅助损失负载均衡、MTP 和 FP8 共同提升训练与推理效率。",
    industry: "模型竞争增加了单位算力产出这一核心维度，并推动国内硬件与推理栈适配。",
    future: "观察独立复现、真实 API 负载、国产算力适配和后续推理模型。",
    business: "成本效率会压缩通用 API 毛利，但扩大模型进入低客单价业务的空间。",
    category: "model-release",
    company: "DeepSeek",
    keywords: ["DeepSeek-V3", "MoE", "FP8", "训练效率"],
    scores: [98, 0, 97, 96],
    date: "2024-12-26T00:00:00.000Z",
    source: "deepseek",
    url: "https://github.com/deepseek-ai/DeepSeek-V3",
    tracks: ["tech-evolution", "global-innovation", "model-economics", "to-d", "investing"],
    actors: ["deepseek"],
  }),
  event({
    slug: "deepseek-r1-open-reasoning",
    title: "DeepSeek-R1 开源：推理能力与低成本冲击全球模型格局",
    fact: "DeepSeek 发布 R1、R1-Zero 和蒸馏模型，公开权重与技术方法。",
    summary:
      "中国团队把前沿推理能力、开放权重和极具竞争力的价格组合起来，促使全球市场重新评估算力壁垒和模型定价。",
    technical: "纯强化学习、冷启动、多阶段训练和蒸馏展示了可复用的推理能力构建路线。",
    industry: "开放推理模型加速价格下降，并让中国模型第一次成为全球开发者和资本市场的共同变量。",
    future: "观察真实工具使用、长任务可靠性、蒸馏生态和下一代训练成本。",
    business: "通用模型溢价承压，应用公司更应把价值建立在数据、流程和分发而非模型转售。",
    category: "reasoning",
    company: "DeepSeek",
    keywords: ["DeepSeek-R1", "推理", "强化学习", "开放权重"],
    scores: [99, 0, 99, 99],
    date: "2025-01-20T00:00:00.000Z",
    source: "deepseek",
    url: "https://github.com/deepseek-ai/DeepSeek-R1",
    tracks: ["tech-evolution", "agi-progress", "global-innovation", "investing", "model-economics"],
    actors: ["deepseek"],
  }),
  event({
    slug: "openai-operator-browser-agent",
    title: "Operator 发布：OpenAI 从对话产品进入浏览器任务执行",
    fact: "OpenAI 发布 Operator 研究预览，模型可以在浏览器中点击、输入并完成多步骤任务。",
    summary:
      "ChatGPT 的产品边界从回答问题扩展到代替用户执行，消费级 Agent 开始验证真实交易与服务流程。",
    technical: "Computer-Using Agent 将视觉、推理和交互动作放进闭环，但仍需要频繁的人类确认。",
    industry: "浏览器成为 Agent 的通用执行层，电商、旅行和本地服务平台需要重新考虑机器用户。",
    future: "观察支付/登录场景、反自动化策略、成功率和责任边界。",
    business: "To C Agent 的核心指标应从使用时长转为完成任务数、节省时间和交易转化。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["Operator", "Browser Agent", "CUA", "To C"],
    scores: [98, 0, 95, 94],
    date: "2025-01-23T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-operator/",
    tracks: ["tech-evolution", "commercialization", "to-c", "agi-progress"],
    actors: ["openai"],
  }),
  event({
    slug: "openai-deep-research",
    title: "Deep Research 发布：Agent 首次把复杂知识工作做成标准产品",
    fact: "OpenAI 在 ChatGPT 发布 Deep Research，可自主搜索、分析并综合大量在线来源。",
    summary:
      "长时研究任务成为可购买的消费与专业能力，Agent 的价值从即时回答转向替代数小时知识劳动。",
    technical: "浏览、检索、证据选择、长上下文推理和报告生成被组合成持续数十分钟的工作流。",
    industry: "研究、咨询、投研和专业信息服务开始面对结果型 AI 产品的直接竞争。",
    future: "观察引用准确性、付费使用量、垂直数据库接入和结果责任。",
    business: "专业服务团队应把 AI 用于扩大研究覆盖，并把差异化转向私有数据与判断框架。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["Deep Research", "研究 Agent", "知识工作", "ChatGPT"],
    scores: [98, 0, 96, 97],
    date: "2025-02-02T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-deep-research/",
    tracks: ["agi-progress", "commercialization", "to-c", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-3-7-code-preview",
    title: "Claude 3.7 与 Claude Code：混合推理进入开发者工作流",
    fact: "Anthropic 发布 Claude 3.7 Sonnet，并预览在终端中工作的 Claude Code。",
    summary: "模型厂商不再只提供模型能力，而是直接占据代码库、终端和工程任务入口。",
    technical: "可控扩展思考与 Agent 工具循环结合，让模型在速度、成本和任务深度之间动态取舍。",
    industry: "编码助手从补全和聊天升级为能规划、修改、测试与提交的工程协作者。",
    future: "观察真实 PR 合并率、长任务恢复、代码安全和团队级治理。",
    business: "开发工具市场的价值将集中到上下文、执行环境、评测和组织工作流。",
    category: "coding-agent",
    company: "Anthropic",
    keywords: ["Claude 3.7", "Claude Code", "混合推理", "编码 Agent"],
    scores: [99, 0, 97, 98],
    date: "2025-02-24T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-3-7-sonnet",
    tracks: ["tech-evolution", "agi-progress", "to-d", "commercialization"],
    actors: ["anthropic"],
  }),
  event({
    slug: "openai-responses-agents-sdk",
    title: "Responses API 与 Agents SDK：OpenAI 建立 Agent 开发平台",
    fact: "OpenAI 发布 Responses API、内置 Web/File/Computer Use 工具和开源 Agents SDK。",
    summary:
      "Agent 从应用团队自组装的框架变成模型平台的标准产品层，工具、追踪和编排被纳入统一 API。",
    technical: "托管工具、handoff、tracing 和状态管理降低了多步 Agent 的工程门槛。",
    industry: "模型 API 厂商开始向 Agent runtime 扩张，与开源框架和自动化平台正面竞争。",
    future: "观察锁定成本、跨模型兼容、可观测性和企业权限治理。",
    business: "To D 产品需要在开放性、行业组件或运行治理上建立差异化。",
    category: "developer-platform",
    company: "OpenAI",
    keywords: ["Responses API", "Agents SDK", "工具调用", "开发平台"],
    scores: [99, 0, 95, 97],
    date: "2025-03-11T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/new-tools-for-building-agents/",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["openai"],
  }),
  event({
    slug: "nvidia-blackwell-ultra-reasoning-factory",
    title: "Blackwell Ultra 发布：推理时 Scaling 重塑 AI 基础设施",
    fact: "NVIDIA 在 GTC 2025 发布 Blackwell Ultra、Dynamo 和面向推理 Agent 的 AI Factory 平台。",
    summary: "算力需求从集中训练扩展到持续、高并发、长链推理，推理吞吐和数据中心协同成为新瓶颈。",
    technical: "GB300、Dynamo、网络和存储共同围绕 test-time scaling 与 Agent 工作负载优化。",
    industry: "芯片价值继续向完整系统、网络、软件和电力基础设施延伸。",
    future: "观察推理收入占比、集群利用率、能源约束和替代加速器。",
    business: "投资判断要从 GPU 出货转向单位推理产出、部署周期和数据中心现金流。",
    category: "infrastructure",
    company: "NVIDIA",
    keywords: ["Blackwell Ultra", "Dynamo", "推理基础设施", "AI Factory"],
    scores: [99, 0, 97, 96],
    date: "2025-03-18T00:00:00.000Z",
    source: "nvidia-blog-ai",
    url: "https://nvidianews.nvidia.com/online-press-kit/gtc-2025-news",
    tracks: ["tech-evolution", "investing", "model-economics", "to-b"],
    actors: ["nvidia"],
  }),
  event({
    slug: "gemini-2-5-thinking-model",
    title: "Gemini 2.5 发布：思考模型成为前沿模型默认形态",
    fact: "Google 发布 Gemini 2.5 Pro 实验版，将推理能力内置为模型的核心能力。",
    summary: "推理从独立产品线变为旗舰模型的默认属性，长上下文、多模态与思考开始合流。",
    technical: "大上下文、代码能力和推理时计算共同面向复杂 Agent 与知识任务。",
    industry: "前沿厂商竞争从是否有 reasoning model 转向单位成本、延迟和产品整合。",
    future: "观察稳定版价格、工具使用、长上下文有效利用率和企业分发。",
    business: "应用团队应减少对固定模型标签的依赖，建立任务级路由和持续评测。",
    category: "reasoning",
    company: "Google DeepMind",
    keywords: ["Gemini 2.5", "Thinking Model", "长上下文", "推理"],
    scores: [98, 0, 96, 94],
    date: "2025-03-25T00:00:00.000Z",
    source: "google-ai",
    url: "https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/",
    tracks: ["tech-evolution", "agi-progress", "model-economics", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "llama-4-native-multimodal-moe",
    title: "Llama 4 发布：开放模型转向原生多模态 MoE",
    fact: "Meta 发布 Llama 4 Scout 与 Maverick，采用原生多模态和混合专家架构。",
    summary: "开放模型路线跟进多模态、超长上下文和稀疏激活，继续压缩闭源模型的基础能力差异。",
    technical: "MoE 让总参数规模与推理成本解耦，Scout 将上下文扩展到千万 token 级别。",
    industry: "开放生态进入复杂系统竞争，但训练透明度、评测可信度和部署门槛仍是约束。",
    future: "观察社区复现、实际上下文利用、企业部署和后续旗舰模型。",
    business: "私有化与开放权重方案更丰富，企业需要评估总拥有成本而不是只看 benchmark。",
    category: "model-release",
    company: "Meta",
    keywords: ["Llama 4", "MoE", "原生多模态", "开放模型"],
    scores: [97, 0, 91, 88],
    date: "2025-04-05T00:00:00.000Z",
    source: "meta-ai",
    url: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["meta"],
  }),
  event({
    slug: "google-a2a-agent-protocol",
    title: "Google A2A 发布：多 Agent 协作进入协议竞争",
    fact: "Google 联合多家企业发布 Agent2Agent Protocol，用于不同平台和厂商 Agent 之间协作。",
    summary: "在 MCP 解决 Agent 与工具连接之后，A2A 把标准化推进到 Agent 身份、任务和结果交换。",
    technical: "Agent Card、任务生命周期、消息与 artifact 形成跨组织协作的公共抽象。",
    industry: "Agent 生态开始从单体应用转向协议、目录、身份和治理组成的网络。",
    future: "观察 MCP/A2A 分工、企业身份、跨域授权和实际互操作案例。",
    business: "平台型产品应把能力封装为可发现、可授权、可审计的 Agent 服务。",
    category: "developer-platform",
    company: "Google",
    keywords: ["A2A", "Agent2Agent", "互操作", "协议"],
    scores: [98, 0, 92, 94],
    date: "2025-04-09T00:00:00.000Z",
    source: "google-developers",
    url: "https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/",
    tracks: ["tech-evolution", "to-d", "to-b", "commercialization"],
    actors: ["google"],
  }),
  event({
    slug: "openai-o3-o4-mini-tools",
    title: "o3 与 o4-mini 发布：推理模型开始主动调用全套工具",
    fact: "OpenAI 发布 o3 和 o4-mini，并让推理模型在 ChatGPT 中组合使用浏览、代码、文件和图像工具。",
    summary: "推理与行动合流，模型从在单一上下文中思考转向选择工具、验证结果并完成任务。",
    technical: "模型原生工具选择把规划、执行和检查纳入统一推理过程。",
    industry: "Agent 能力逐渐内建进旗舰模型，纯编排层产品面临价值压缩。",
    future: "观察工具选择准确性、错误恢复、长任务成本和安全控制。",
    business: "应用公司的壁垒需要从调用链转向数据、权限、评测和业务闭环。",
    category: "reasoning",
    company: "OpenAI",
    keywords: ["o3", "o4-mini", "工具使用", "Agent"],
    scores: [99, 0, 97, 96],
    date: "2025-04-16T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-o3-and-o4-mini/",
    tracks: ["tech-evolution", "agi-progress", "to-c", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "qwen-3-hybrid-thinking",
    title: "Qwen3 开源：中国模型进入混合推理与 Agent 阶段",
    fact: "Qwen 团队发布 Qwen3 系列开放模型，支持 thinking/non-thinking 切换与多语言能力。",
    summary: "国产开放模型快速吸收推理时计算和 MoE 路线，并把成本、尺寸和部署选择做成完整矩阵。",
    technical: "混合推理允许同一模型按任务切换思考预算，MoE 提升参数容量与推理效率。",
    industry: "中国模型与全球前沿的技术代差缩短，竞争转向生态、产品、算力和海外分发。",
    future: "观察 Agent 工具使用、海外采用、企业落地和下一代旗舰模型。",
    business: "国内 To D 市场的模型供给更充分，价值继续向工具链和行业数据迁移。",
    category: "model-release",
    company: "Alibaba / Qwen",
    keywords: ["Qwen3", "混合推理", "MoE", "中国创新"],
    scores: [98, 0, 94, 94],
    date: "2025-04-29T00:00:00.000Z",
    source: "qwen",
    url: "https://qwenlm.github.io/blog/qwen3/",
    tracks: ["tech-evolution", "agi-progress", "global-innovation", "to-d"],
    actors: ["alibaba"],
  }),
  event({
    slug: "openai-codex-cloud-agent",
    title: "Codex 云端 Agent 发布：编码任务从辅助转向委派",
    fact: "OpenAI 发布 Codex 研究预览，可在隔离云环境中并行处理代码库任务。",
    summary:
      "开发者可以把修复、测试和代码理解任务交给后台 Agent，编码产品从同步对话进入异步任务队列。",
    technical: "隔离环境、仓库上下文、并行执行和可审查变更是可靠编码 Agent 的关键系统能力。",
    industry: "GitHub、IDE、终端和云 Agent 开始争夺软件交付的控制面。",
    future: "观察 PR 合并率、运行成本、安全边界和团队协作模式。",
    business: "软件团队需要把 Agent 纳入权限、评审、CI 和产能度量，而不只是购买个人席位。",
    category: "coding-agent",
    company: "OpenAI",
    keywords: ["Codex", "云端 Agent", "异步编码", "软件工程"],
    scores: [98, 0, 97, 98],
    date: "2025-05-16T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-codex/",
    tracks: ["tech-evolution", "commercialization", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-4-long-running-agents",
    title: "Claude 4 发布：长时编码与 Agent 能力成为旗舰卖点",
    fact: "Anthropic 发布 Claude Opus 4 与 Sonnet 4，强调编码、工具使用和长任务能力。",
    summary: "前沿模型的评价中心继续从聊天质量转向可持续执行真实工作的可靠性。",
    technical: "混合推理、并行工具、记忆与长任务行为围绕 Agent 工作负载优化。",
    industry: "Anthropic 以 Claude Code 和企业 API 将模型优势直接转化为开发者与企业产品。",
    future: "观察长任务成功率、Agent 安全等级、企业收入和模型成本。",
    business: "编码与知识工作成为模型商业化最清晰的高价值入口。",
    category: "model-release",
    company: "Anthropic",
    keywords: ["Claude 4", "Opus 4", "Sonnet 4", "长任务"],
    scores: [99, 0, 97, 98],
    date: "2025-05-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-4",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-d", "to-b"],
    actors: ["anthropic"],
  }),
  event({
    slug: "minimax-m1-long-context-reasoning",
    title: "MiniMax-M1 开源：国产推理模型竞争延伸到百万上下文",
    fact: "MiniMax 发布并开源 M1 混合注意力推理模型，提供百万 token 输入上下文。",
    summary: "国产模型厂商开始在推理、长上下文、Agent 工具使用和成本之间寻找差异化路线。",
    technical: "Lightning Attention 与混合注意力降低长上下文计算成本，面向复杂生产力任务。",
    industry: "国内前沿模型从跟随单一 benchmark 转向架构和产品约束共同优化。",
    future: "观察开源复现、长上下文有效性、API 使用和 Agent 产品转化。",
    business: "长文档、代码库和企业知识场景获得更低成本的国产模型选项。",
    category: "reasoning",
    company: "MiniMax",
    keywords: ["MiniMax-M1", "长上下文", "混合注意力", "开源"],
    scores: [96, 0, 88, 88],
    date: "2025-06-16T00:00:00.000Z",
    source: "minimax",
    url: "https://www.minimax.io/news/minimaxm1",
    tracks: ["tech-evolution", "global-innovation", "to-d", "model-economics"],
    actors: ["minimax"],
  }),
  event({
    slug: "kimi-k2-agentic-open-model",
    title: "Kimi K2 开放：Moonshot 把国产模型竞争推向 Agent 与代码",
    fact: "Moonshot AI 发布 Kimi K2 混合专家模型并开放权重，重点强化代码和 Agent 工具使用。",
    summary: "中国头部创业公司从消费级长文本产品延伸到开放基础模型和开发者生态。",
    technical: "大规模 MoE、工具调用和代码训练面向可执行 Agent，而不仅是对话体验。",
    industry: "国内模型厂商同时争夺 To C 用户、To D 生态和海外开发者。",
    future: "观察 API 收入、权重采用、工具调用可靠性和海外生态。",
    business: "创业公司需要证明开放模型能够反向增强付费产品和平台分发。",
    category: "model-release",
    company: "Moonshot AI",
    keywords: ["Kimi K2", "MoE", "Agent", "开放权重"],
    scores: [96, 0, 91, 91],
    date: "2025-07-11T00:00:00.000Z",
    source: "moonshot",
    url: "https://github.com/MoonshotAI/Kimi-K2",
    tracks: ["tech-evolution", "global-innovation", "commercialization", "to-c", "to-d"],
    actors: ["moonshot"],
  }),
  event({
    slug: "chatgpt-agent-research-to-action",
    title: "ChatGPT Agent 发布：研究、浏览与行动合并为统一模式",
    fact: "OpenAI 发布 ChatGPT Agent，将 Operator 的操作、Deep Research 的研究和对话能力整合。",
    summary: "消费级 AI 产品从多个实验入口收敛为目标驱动的通用任务执行模式。",
    technical: "视觉浏览器、文本浏览器、终端、连接器和人工确认共同组成多工具 Agent runtime。",
    industry: "模型、产品入口和执行环境进一步合并，独立通用 Agent 的生存空间缩小。",
    future: "观察高频任务、成功率、交易安全和订阅留存。",
    business: "To C 团队应围绕结果、信任和垂直闭环，而非复制通用聊天与浏览能力。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["ChatGPT Agent", "Operator", "Deep Research", "任务执行"],
    scores: [99, 0, 98, 98],
    date: "2025-07-17T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-chatgpt-agent/",
    tracks: ["agi-progress", "commercialization", "to-c", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "gpt-5-unified-routing",
    title: "GPT-5 发布：快模型与深度推理被统一到一个产品入口",
    fact: "OpenAI 发布 GPT-5，并在 ChatGPT 中通过统一系统路由即时回答和更深推理。",
    summary: "用户不再需要理解复杂模型菜单，模型选择开始由平台按任务难度、成本和延迟自动完成。",
    technical: "路由器、能力模型与安全策略共同决定每个请求的计算预算。",
    industry: "模型品牌让位于产品级体验，平台对成本、分发和用户反馈的控制增强。",
    future: "观察路由质量、API 迁移、单位任务成本和用户对模型人格的偏好。",
    business: "企业应建立自己的任务评测和路由策略，避免把平台默认选择当作最优解。",
    category: "model-release",
    company: "OpenAI",
    keywords: ["GPT-5", "模型路由", "推理", "ChatGPT"],
    scores: [99, 0, 99, 98],
    date: "2025-08-07T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-gpt-5/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "model-economics"],
    actors: ["openai"],
  }),
  event({
    slug: "codex-general-availability",
    title: "Codex 正式可用：编码 Agent 从实验进入团队基础设施",
    fact: "OpenAI 宣布 Codex 正式可用，并发布 SDK、Slack 集成和企业管理能力。",
    summary: "编码 Agent 从单点云任务发展为连接 IDE、终端、团队沟通和组织管理的协作系统。",
    technical: "SDK、运行环境、权限和监控把 Agent 纳入可编程的软件交付流水线。",
    industry: "编码 Agent 的竞争开始从模型能力转向工作流覆盖、团队治理和生态嵌入。",
    future: "观察企业席位、实际代码产出、SDK 生态和安全事故率。",
    business: "软件组织需要重新定义开发者产能、评审责任和 Agent 使用政策。",
    category: "coding-agent",
    company: "OpenAI",
    keywords: ["Codex", "GA", "SDK", "团队协作"],
    scores: [99, 0, 96, 98],
    date: "2025-10-06T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/codex-now-generally-available/",
    tracks: ["commercialization", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-constitution-2026",
    title: "Claude 新宪法发布：模型行为治理走向可审查的制度层",
    fact: "Anthropic 发布 2026 版 Claude Constitution，系统说明模型的价值、行为原则和冲突处理。",
    summary: "前沿模型治理从简单规则列表走向更完整、可讨论的行为框架，安全与产品人格开始合流。",
    technical: "宪法式训练为复杂情境中的原则权衡提供显式监督结构。",
    industry: "模型厂商需要同时竞争能力、可控性、信任和制度透明度。",
    future: "观察外部评测、行为一致性、企业可配置性和监管接受度。",
    business: "高风险行业采购需要把模型行为政策纳入技术和法律尽调。",
    category: "safety-governance",
    company: "Anthropic",
    keywords: ["Claude Constitution", "对齐", "治理", "安全"],
    scores: [98, 0, 88, 89],
    date: "2026-01-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-new-constitution",
    tracks: ["agi-progress", "to-b", "to-g"],
    actors: ["anthropic"],
  }),
  event({
    slug: "claude-opus-4-7-agent-work",
    title: "Claude Opus 4.7 发布：前沿能力继续向复杂工作与 Agent 收敛",
    fact: "Anthropic 发布 Claude Opus 4.7，重点提升代码、Agent、视觉和多步骤任务表现。",
    summary: "模型升级的价值越来越以完成复杂工作来衡量，而不是单一知识或生成 benchmark。",
    technical: "长任务规划、工具使用、视觉理解和一致性成为统一能力包。",
    industry: "Anthropic 继续围绕 Claude Code、Cowork 和企业工作构建模型—产品闭环。",
    future: "观察真实任务完成率、企业收入、推理成本和安全边界。",
    business: "To B 竞争需要同时拥有模型、执行环境、权限和行业工作流。",
    category: "model-release",
    company: "Anthropic",
    keywords: ["Claude Opus 4.7", "Agent", "编码", "复杂工作"],
    scores: [98, 0, 95, 96],
    date: "2026-04-16T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-opus-4-7",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["anthropic"],
  }),
  event({
    slug: "gpt-5-5-real-work",
    title: "GPT-5.5 发布：模型升级围绕端到端真实工作重新定义",
    fact: "OpenAI 发布 GPT-5.5，重点提升编码、研究、数据分析、文档和跨工具操作。",
    summary: "前沿竞争从回答质量继续转向能否理解模糊目标、跨工具执行并检查结果。",
    technical: "Agentic coding、computer use、科学研究和长时执行被统一到旗舰模型。",
    industry: "模型与办公、开发和研究产品的边界进一步消失。",
    future: "观察单位任务成本、失败恢复、工作流接管和企业采用。",
    business: "CEO 应以完整流程节省和结果质量评估模型，而非只比较 token 价格。",
    category: "model-release",
    company: "OpenAI",
    keywords: ["GPT-5.5", "真实工作", "Computer Use", "Agent"],
    scores: [99, 0, 98, 98],
    date: "2026-04-23T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-gpt-5-5/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "anthropic-series-h-scale",
    title: "Anthropic 完成 Series H：模型竞争进入资本、收入与算力共振",
    fact: "Anthropic 宣布完成 650 亿美元 Series H 融资，投后估值 9650 亿美元，并披露年化收入超过 470 亿美元。",
    summary: "前沿模型公司的资本需求、商业收入和算力扩张同步放大，行业集中度继续上升。",
    technical: "持续训练、推理服务和 Agent 产品扩张把资本开支转化为长期基础设施竞争。",
    industry:
      "模型公司正在形成接近云平台的资本密度和收入规模，创业窗口向应用、数据和垂直系统迁移。",
    future: "观察收入质量、算力承诺、企业留存和估值消化。",
    business: "投资判断应把模型收入、推理毛利、资本开支和产品粘性放在同一张表中。",
    category: "investment",
    company: "Anthropic",
    keywords: ["Series H", "融资", "算力", "企业收入"],
    scores: [99, 0, 99, 97],
    date: "2026-05-28T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/series-h",
    tracks: ["investing", "commercialization", "to-b", "model-economics"],
    actors: ["anthropic"],
  }),
  event({
    slug: "predicatelongbench-long-context-difficulty",
    title: "PredicateLongBench：长上下文评测开始测量“任务难度”而非只测长度",
    fact: "2026 年 7 月 9 日提交的 PredicateLongBench 预印本提出可控生成长上下文任务的两条流水线，并报告前沿模型随谓词难度上升出现明显性能下降。",
    summary:
      "长上下文能力长期被“上下文窗口有多长”主导，但窗口可容纳信息不等于模型能在复杂约束下可靠找到并组合证据。该研究把长度与任务难度拆开控制，为企业文档、研究和 Agent 评测提供更接近真实工作的压力测试思路。",
    technical:
      "论文通过谓词结构控制检索条件、组合关系与推理复杂度，并以两类生成流水线构造可重复的数据。核心贡献不是再增加一个平均分，而是提供难度轴，使团队能观察模型在上下文长度相同、约束复杂度不同条件下的退化曲线。",
    industry:
      "模型厂商仅公布长上下文窗口和单一 benchmark 分数将更难支持采购判断；应用团队需要围绕自己的文档结构、约束数量和证据组合方式建立分层评测。",
    future:
      "这是尚未完成独立复现的预印本。下一步应检查数据生成是否引入捷径、不同模型版本的复现实验，以及难度轴与真实法律、金融和研发文档任务的相关性。",
    business:
      "采购长上下文模型时，应把“最大窗口”替换为按任务难度分层的成功率、重试率和人工核验成本，避免为无法转化为可靠结果的容量付费。",
    category: "research",
    company: "PredicateLongBench",
    keywords: ["长上下文", "benchmark", "难度轴", "评测"],
    scores: [92, 0, 84, 86],
    date: "2026-07-09T09:28:06.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08284",
    tracks: ["tech-evolution", "agi-progress", "to-d", "to-b"],
    actors: [],
  }),
  event({
    slug: "compete-then-collaborate-multi-agent",
    title: "Compete Then Collaborate：多智能体推理不再默认“越合作越好”",
    fact: "2026 年 7 月 9 日提交的预印本 Compete Then Collaborate 提出先让 Agent 独立竞争、再选择性协作的推理框架，用于降低过早共识和错误传播。",
    summary:
      "多智能体系统常把更多讨论轮次当成质量来源，但 Agent 过早共享中间结论也可能放大同一种错误。该研究将独立探索与后续协作分阶段，提示系统设计应关注观点多样性、选择机制与协作时机，而不只是增加 Agent 数量。",
    technical:
      "框架先保留多个独立解题轨迹，再根据候选质量和差异选择进入协作的方案，从结构上减少早期信息污染。技术判断重点应放在选择器是否可靠、额外推理成本、不同任务上的收益稳定性，以及失败案例是否真正互补。",
    industry:
      "Agent 平台的竞争将从编排更多角色转向管理推理多样性和协作预算；企业不应把角色数量、消息数量或工作流复杂度直接当成更高可靠性的证据。",
    future:
      "该结果仍属于预印本证据。需要独立复现其基线、公平比较单 Agent 的等成本推理，并验证在代码、研究和工具调用任务中能否保持收益。",
    business:
      "设计高价值 Agent 流程时，可用“独立候选 → 质量门控 → 有条件协作”替代全程群聊，并以每个正确结果的总推理成本衡量是否值得。",
    category: "research",
    company: "Compete Then Collaborate",
    keywords: ["多智能体", "协作", "推理", "Agent 编排"],
    scores: [91, 0, 85, 84],
    date: "2026-07-09T08:32:31.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08255",
    tracks: ["tech-evolution", "agi-progress", "to-d"],
    actors: [],
  }),
  event({
    slug: "autopersonas-agent-simulation-diversity",
    title: "AutoPersonas：Agent 模拟的瓶颈从规模转向角色多样性与重复污染",
    fact: "2026 年 7 月 9 日提交的 AutoPersonas 预印本分析 8 个模型生成的 1,600 个角色，并讨论自动生成 Persona 时的重复、偏差与有效多样性问题。",
    summary:
      "用大量虚拟用户或专家 Agent 做产品研究看似可以低成本扩样，但角色数量并不等于观点覆盖。研究把 Persona 生成本身变成可测量对象，揭示重复模板和模型偏差可能制造虚假的“用户共识”。",
    technical:
      "论文比较多模型生成角色的语义覆盖、重复模式与人口属性分布，核心方法是把 Persona 集合质量从主观观感转成多样性和冗余指标。对模拟系统而言，采样策略、去重和真实用户校准与下游 Agent 能力同等重要。",
    industry:
      "合成用户研究、市场模拟和多 Agent 社会实验需要新的数据质量规范；未经覆盖度与偏差审计的 Persona 池不能替代真实访谈或被包装成市场证据。",
    future:
      "预印本结论仍需在更多语言、地区与垂直人群中复现，并检验角色多样性指标能否预测下游决策质量，而不只是文本表面差异。",
    business:
      "使用合成 Persona 做早期探索时，应保留真实样本校准集，披露模型与采样方法，并把去重率、覆盖缺口和与真实用户的偏差纳入决策置信度。",
    category: "research",
    company: "AutoPersonas",
    keywords: ["Persona", "Agent 模拟", "合成用户", "多样性"],
    scores: [90, 0, 82, 85],
    date: "2026-07-09T08:25:44.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08252",
    tracks: ["tech-evolution", "to-b", "to-d"],
    actors: [],
  }),
  event({
    slug: "blind-spots-bench-vision-language",
    title: "Blind-Spots-Bench：多模态模型高分背后仍有系统性视觉盲区",
    fact: "2026 年 7 月 9 日提交的 Blind-Spots-Bench 预印本构建 235 个样本，评测 10 类视觉语言理解缺口，用于暴露常规平均分容易掩盖的系统性失败。",
    summary:
      "多模态模型在主流 benchmark 上持续提升，但平均准确率难以回答它会在哪类图像关系、局部细节或视觉条件下稳定失败。该研究按盲区类型组织测试，使安全评估从单一排行榜转向可诊断的能力边界。",
    technical:
      "基准通过小规模、类型化样本隔离不同视觉语言缺口，强调失败分布而非总分。落地时需要检查样本规模、任务构造和模型是否见过相似数据，并将类别级召回与置信校准加入真实场景测试。",
    industry:
      "视觉 Agent、文档理解和质检产品不能只引用通用多模态分数；采购和上线门槛需要明确业务中不可接受的盲区，并对这些类别单独验收。",
    future:
      "该预印本样本规模有限，需扩展到真实世界分布、更多语言与视频任务，并验证模型更新后盲区是否迁移而非真正消失。",
    business:
      "在医疗、制造和文档审核场景，应建立盲区清单、人工接管规则与类别级回归集，把“何时不能信模型”作为部署决策的一部分。",
    category: "research",
    company: "Blind-Spots-Bench",
    keywords: ["多模态", "视觉语言模型", "盲区", "安全评测"],
    scores: [91, 0, 86, 87],
    date: "2026-07-09T11:05:17.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08317",
    tracks: ["tech-evolution", "agi-progress", "to-b"],
    actors: [],
  }),
  event({
    slug: "overthinking-secret-leakage-reasoning-models",
    title: "Overthinking：推理模型的长思考可能把秘密泄露风险放大至 10 倍",
    fact: "2026 年 7 月 9 日提交的 Overthinking 预印本评测 2B 至 32B 参数模型，并报告更长推理过程在部分设置下使秘密泄露风险最高增加约 10 倍。",
    summary:
      "推理时间扩展通常被视为能力增强手段，但更长的中间推理也扩大了模型重建、重复或暴露敏感上下文的机会。研究把“想得更久”与信息泄露联系起来，提示推理预算同时是安全预算。",
    technical:
      "论文跨多个模型规模比较秘密保留与推理长度的关系，关注泄露随计算预算变化的趋势。关键技术问题包括威胁模型、提示设置、可见推理与隐藏状态的差异，以及过滤器是否只是掩盖输出而非降低内部暴露。",
    industry:
      "企业在引入 reasoning model 和长链 Agent 时需要重新审视日志、上下文拼接、可观察性与数据最小化；能力评测不能与隐私和安全评测分开。",
    future:
      "“最高约 10 倍”来自特定预印本实验，不应外推为所有模型。需独立复现不同 API、推理可见性、系统提示和防护机制下的绝对风险。",
    business:
      "高敏数据流程应限制不必要的推理预算与上下文范围，分离秘密，审计日志，并以泄露率随推理预算变化的曲线决定哪些任务可以使用深度推理。",
    category: "research",
    company: "Overthinking",
    keywords: ["推理模型", "秘密泄露", "安全", "推理预算"],
    scores: [91, 0, 91, 92],
    date: "2026-07-09T06:02:41.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08173",
    tracks: ["tech-evolution", "agi-progress", "to-b", "to-g"],
    actors: [],
  }),
  event({
    slug: "causalds-causal-data-science-agents",
    title: "CausalDS：数据科学 Agent 从生成代码走向结构因果推断与拒答",
    fact: "2026 年 7 月 9 日提交的 CausalDS 预印本提出面向数据科学 Agent 的因果评测，覆盖结构因果模型、Pearl 三层因果阶梯与在证据不足时拒绝回答。",
    summary:
      "当前数据 Agent 擅长生成查询、图表和相关性分析，但业务决策需要区分观察、干预与反事实。该研究把因果结构和拒答能力纳入评测，使“能产出分析”与“能支持行动决策”之间的差距变得可见。",
    technical:
      "基准围绕结构因果模型构造关联、干预和反事实问题，并检查模型在不可识别或信息不足时是否能够 abstain。核心价值是同时测推理正确性与认识边界，而不是只看最终答案格式或代码是否可运行。",
    industry:
      "企业数据 Copilot 若不能识别因果假设和证据边界，可能把相关性包装成策略建议；数据 Agent 的验收需要增加因果层级、假设披露和拒答率。",
    future:
      "该研究仍是预印本和受控基准。需验证在脏数据、隐藏混杂、时间序列和真实组织指标中是否成立，并比较工具增强 Agent 与纯模型的差异。",
    business:
      "将数据 Agent 用于定价、增长或运营决策前，应要求它明确因果图、识别假设和不可回答条件，并由领域专家审核干预建议，而非只验收 SQL 与图表。",
    category: "research",
    company: "CausalDS",
    keywords: ["因果推断", "数据科学 Agent", "拒答", "评测"],
    scores: [92, 0, 88, 91],
    date: "2026-07-09T02:51:43.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08093",
    tracks: ["tech-evolution", "to-b", "to-d"],
    actors: [],
  }),
] as const satisfies readonly CuratedEventSeed[];

export const industryNarratives = {
  horizon: { start: "2022-08-22", end: "2026-07-13", label: "2022—今天" },
  eras: [
    {
      slug: "public-generative-ai",
      label: "生成式 AI 进入大众市场",
      period: "2022 H2",
      summary:
        "Stable Diffusion 把生成模型带入开放生态，ChatGPT 把大模型从研究能力变成大众每天可以使用的产品。",
      projects: [
        {
          name: "ChatGPT",
          status: "active",
          note: "从 research preview 演化为通用 AI 产品入口。",
          url: "https://openai.com/index/chatgpt/",
        },
        {
          name: "Stable Diffusion",
          status: "active",
          note: "开放权重持续支撑图像生成生态。",
          url: "https://stability.ai/news-updates/stable-diffusion-public-release",
        },
      ],
    },
    {
      slug: "model-platforms-and-copilots",
      label: "模型平台与 Copilot 成形",
      period: "2023",
      summary:
        "GPT-4、Claude 2、Llama 2、Qwen、Mistral 与 Gemini 建立多路线竞争，API、插件和 Copilot 开始进入软件与组织工作流。",
      projects: [
        {
          name: "Microsoft 365 Copilot",
          status: "active",
          note: "将模型、组织数据和办公工作流绑定为企业产品。",
          url: "https://blogs.microsoft.com/blog/2023/03/16/introducing-microsoft-365-copilot-your-copilot-for-work/",
        },
        {
          name: "Artifact",
          status: "acquired",
          note: "独立应用停止后，个性化技术由 Yahoo 收购并继续整合。",
          url: "https://www.yahooinc.com/press/yahoo-announces-the-acquisition-of-artifact-the-news-discovery-platform-created-by-instagram-cofounders-kevin-systrom-and-mike-krieger",
        },
      ],
    },
    {
      slug: "multimodal-and-reasoning",
      label: "多模态、推理与应用分化",
      period: "2024",
      summary:
        "原生多模态与推理时计算打开新的能力曲线，开放模型继续提升；应用市场同时进入整合，单一包装型产品开始失去空间。",
      projects: [
        {
          name: "Inflection AI",
          status: "pivoted",
          note: "联合创始人与部分团队加入 Microsoft AI 后，原有消费助手路线进入组织与战略重构。",
          url: "https://blogs.microsoft.com/blog/2024/03/19/mustafa-suleyman-deepmind-and-inflection-co-founder-joins-microsoft-to-lead-copilot/",
        },
        {
          name: "Stability AI",
          status: "pivoted",
          note: "在领导层和资本结构调整后继续聚焦开放生成媒体模型。",
          url: "https://stability.ai/news/stability-ai-secures-significant-new-investment",
        },
      ],
    },
    {
      slug: "agents-and-runtime",
      label: "Agent 从演示走向运行时",
      period: "2025 H1",
      summary:
        "DeepSeek-R1 重估效率边界，Operator、Deep Research、Claude Code 与 Agents SDK 将模型推进浏览器、代码和长任务。",
      projects: [
        {
          name: "Adept",
          status: "pivoted",
          note: "部分团队加入 Amazon 后，公司转向更聚焦的 Agent 产品与企业路线。",
          url: "https://adept.ai/blog/adept-update/",
        },
        {
          name: "Humane Ai Pin",
          status: "sunset",
          note: "消费者设备服务停止，说明新硬件入口必须同时解决产品价值与持续运营。",
          url: "https://support.humane.com/hc/en-us/articles/34243204841997-Ai-Pin-Consumers-FAQ",
        },
      ],
    },
    {
      slug: "product-and-protocol-convergence",
      label: "协议、产品与工作流合流",
      period: "2025 H2",
      summary:
        "MCP、A2A、Agent 产品与模型原生工具共同形成连接和执行层，竞争从功能演示转向真实工作流所有权。",
      projects: [
        {
          name: "MCP",
          status: "active",
          note: "从单一厂商协议扩展为跨模型、工具和平台的连接生态。",
          url: "https://modelcontextprotocol.io/",
        },
        {
          name: "Codex",
          status: "active",
          note: "编码能力从补全演化为云端与本地协同的 Agent 工作流。",
          url: "https://openai.com/codex/",
        },
      ],
    },
    {
      slug: "real-work-and-industry-concentration",
      label: "真实工作与产业再集中",
      period: "2026 H1—今天",
      summary:
        "旗舰模型围绕复杂工作、科学与长任务继续升级，收入、融资、算力和分发向头部集中，应用层开始按留存和结果重新分化。",
      projects: [
        {
          name: "Claude Code",
          status: "active",
          note: "编码 Agent 向团队协作、长任务、SDK 与企业治理扩张。",
          url: "https://www.anthropic.com/claude-code",
        },
        {
          name: "DeepSeek",
          status: "active",
          note: "开放推理与工程效率持续影响全球模型成本和部署讨论。",
          url: "https://api-docs.deepseek.com/news/",
        },
      ],
    },
  ],
  tracks: [
    {
      slug: "tech-evolution",
      thesis:
        "模型能力的主轴已从单纯扩大预训练，转向推理时计算、原生多模态、数据效率和可验证研究。",
      now: "旗舰模型正以可分配推理预算、多模态输入和科学评测扩展能力边界。",
      next: "下一阶段应关注能力增量能否跨基准复现，以及训练数据、评测污染、可靠性与成本是否透明。",
      stages: [
        {
          period: "2024 H2",
          label: "Reasoning",
          summary: "推理时计算成为新 Scaling 轴。",
          chinaPosition: "Qwen 与 DeepSeek 以开放模型和训练效率形成不同于封闭平台的技术路径。",
        },
        {
          period: "2025 H1",
          label: "Multimodal & efficiency",
          summary: "原生多模态、混合推理和训练效率同时推进。",
          chinaPosition: "中国模型在开放推理、长上下文和成本效率上形成全球影响。",
        },
        {
          period: "2025 H2–2026 H1",
          label: "Verifiable capability",
          summary: "能力评价从榜单分数转向可复现研究与真实任务。",
          chinaPosition: "不同团队在科学、端侧、视频与开放生态中形成各自优势，仍需更多可比证据。",
        },
      ],
    },
    {
      slug: "agi-progress",
      thesis:
        "Agent 的关键变化不是更像人聊天，而是模型开始连接工具、维护任务状态，并承担跨软件的完整工作。",
      now: "编码、研究、浏览器操作和企业流程已经出现可重复的有限自治，软件入口正在从功能菜单转向任务委派。",
      next: "需要关注端到端完成率、记忆、权限、错误恢复、人工接管，以及 Agent 是否真正改变软件的交付和收费方式。",
      stages: [
        {
          period: "2024 H2",
          label: "Deliberation",
          summary: "模型学会投入更多计算思考。",
          chinaPosition: "中国路线迅速转向强化学习与推理。",
        },
        {
          period: "2025",
          label: "Action",
          summary: "模型连接工具并承担数十分钟任务。",
          chinaPosition: "开源推理形成差异化优势，通用 Agent 产品仍在验证全球竞争力。",
        },
        {
          period: "2026 H1",
          label: "Real work",
          summary: "能力评价转向端到端工作和科学。",
          chinaPosition: "需观察高价值任务和全球分发中的真实份额。",
        },
      ],
    },
    {
      slug: "commercialization",
      thesis: "商业化从 API token 消费，转向订阅、席位、任务结果和嵌入核心工作流。",
      now: "编码和知识工作率先形成高价值付费，模型厂商直接向应用和运行时扩张。",
      next: "关键指标将从调用量转为完成任务、留存、毛利和组织产能。",
      stages: [
        {
          period: "2024 H2",
          label: "Copilot",
          summary: "助手嵌入软件，但价值仍以功能辅助为主。",
          chinaPosition: "消费入口扩张快，企业付费仍弱。",
        },
        {
          period: "2025",
          label: "Agent product",
          summary: "研究、浏览和编码出现结果型产品。",
          chinaPosition: "模型价格竞争激烈，应用闭环仍在形成。",
        },
        {
          period: "2026 H1",
          label: "Workflow ownership",
          summary: "模型厂商争夺完整工作流和组织预算。",
          chinaPosition: "云与大厂分发占优，创业公司需深耕行业。",
        },
      ],
    },
    {
      slug: "investing",
      thesis: "资本主线从模型融资，扩展到芯片、数据中心、电力、云承诺和高价值应用。",
      now: "头部模型公司正在形成云平台级资本密度，基础设施与收入规模同步放大。",
      next: "需要同时跟踪训练/推理 CapEx、收入质量、毛利和平台锁定。",
      stages: [
        {
          period: "2024 H2",
          label: "Training race",
          summary: "资本主要押注更大训练集群。",
          chinaPosition: "算力限制推动系统效率和国产适配。",
        },
        {
          period: "2025",
          label: "Inference buildout",
          summary: "推理、Agent 和 AI Factory 成为新增投入。",
          chinaPosition: "DeepSeek 证明效率可以改变资本叙事。",
        },
        {
          period: "2026 H1",
          label: "Concentration",
          summary: "收入与融资进一步集中到头部。",
          chinaPosition: "融资和算力差距扩大，开放生态与成本仍有优势。",
        },
      ],
    },
    {
      slug: "global-innovation",
      thesis:
        "全球 AI 创新不是单向排名：中国的开放模型、工程效率、应用分发与本土算力，正在与美国平台能力、欧洲治理和全球开源生态相互塑造。",
      now: "中国团队已在开放推理、模型效率、视频生成和应用规模上形成独立影响，差异更多来自生态、算力、市场与分发路径。",
      next: "观察跨区域开发者采用、全球收入、开放生态贡献、国产算力闭环和产品长期留存。",
      stages: [
        {
          period: "2024 H2",
          label: "开放模型矩阵",
          summary: "Qwen 建立完整开放模型矩阵。",
          chinaPosition: "Qwen 等模型以多尺寸、开源和工具能力形成完整供给。",
        },
        {
          period: "2025 Q1",
          label: "效率成为创新变量",
          summary: "DeepSeek-V3/R1 改写全球成本认知。",
          chinaPosition: "DeepSeek 把开放推理和工程效率变成全球共同议题。",
        },
        {
          period: "2025 H2–2026 H1",
          label: "产品与全球采用",
          summary: "竞争转向 Agent、分发和收入。",
          chinaPosition: "竞争进入产品留存、企业采用、全球分发与算力协同。",
        },
      ],
    },
    {
      slug: "model-economics",
      thesis: "单位 token 价格仍在下降，但真正重要的成本单位正在变成一次可靠完成的任务。",
      now: "MoE、FP8、推理预算和模型路由共同决定成本曲线。",
      next: "采购需要比较成功率、重试、延迟、人工接管和总拥有成本。",
      stages: [
        {
          period: "2024 H2",
          label: "Token price",
          summary: "开放模型和云竞争压低 API 单价。",
          chinaPosition: "国内价格战扩大模型可及性。",
        },
        {
          period: "2025",
          label: "Reasoning budget",
          summary: "推理时计算让成本随任务难度变化。",
          chinaPosition: "DeepSeek 把效率与价格变成全球竞争力。",
        },
        {
          period: "2026 H1",
          label: "Cost per outcome",
          summary: "采购转向按可靠任务结果衡量。",
          chinaPosition: "需要补齐真实 ROI、SLA 和企业交付证据。",
        },
      ],
    },
  ],
} as const;
