import { capitalHistoryEvents } from "./capital-history-2023-2025.js";
import { directResearchHistory2026 } from "./direct-research-history-2026.js";
import { ecosystemHistoryEvents } from "./ecosystem-history-2026-07.js";
import { researchHistory2022To2025 } from "./research-history-2022-2025.js";
import { researchHistory2026 } from "./research-history-2026.js";
import { vendorHistoryEvents } from "./vendor-history-2026-07.js";

export {
  type EmbodiedLaunchEventSeed,
  embodiedLaunchEvents,
} from "./embodied-data/events.js";

export interface CuratedEventSeed {
  slug: string;
  title: string;
  fact: string;
  summary: string;
  technical: string;
  industry: string;
  future: string;
  business: string;
  category: string;
  company: string;
  keywords: readonly string[];
  scores: readonly [confidence: number, heat: number, impact: number, value: number];
  date: string;
  source: string;
  url: string;
  tracks: readonly string[];
  actors: readonly string[];
}

const event = (value: CuratedEventSeed): CuratedEventSeed => value;

/**
 * Editorially selected milestones for the two-year window. These are not a news archive:
 * every row must represent a durable change and link to a first-party source.
 */
export const historicalEvents = [
  event({
    slug: "llama-3-1-open-frontier-model",
    title: "Llama 3.1 405B 发布：开放权重第一次进入前沿模型竞争",
    fact: "Meta 发布 Llama 3.1 405B、70B 与 8B 模型，扩展到 128K 上下文并开放权重下载。",
    summary:
      "开放模型从追随路线进入可与闭源前沿模型直接比较的阶段，云厂商和开发者获得了可控制、可蒸馏的基础模型资产。",
    technical: "405B 模型、FP8 推理和合成数据/蒸馏工具链，证明开放生态也能组织超大规模训练与部署。",
    industry: "模型竞争从单一 API 变成闭源能力、开放权重和云分发三种路线并存。",
    future: "观察开放模型在真实企业工作负载中的使用量、衍生模型质量和推理成本。",
    business: "To D 团队获得更强的私有化和模型定制基础；模型厂商必须用产品和服务维持闭源溢价。",
    category: "model-release",
    company: "Meta",
    keywords: ["Llama 3.1", "开放权重", "405B", "蒸馏"],
    scores: [98, 0, 94, 91],
    date: "2024-07-23T00:00:00.000Z",
    source: "meta-ai",
    url: "https://ai.meta.com/blog/meta-llama-3-1/",
    tracks: ["tech-evolution", "agi-progress", "to-d", "commercialization"],
    actors: ["meta"],
  }),
  event({
    slug: "eu-ai-act-enters-force",
    title: "欧盟 AI Act 生效：通用模型进入正式合规周期",
    fact: "欧盟《人工智能法案》于 2024 年 8 月 1 日生效，并为通用模型和高风险系统设置分阶段义务。",
    summary: "AI 治理从原则讨论进入产品、模型、数据和供应链责任可执行的阶段。",
    technical: "模型文档、风险评估、透明度和系统级监控开始成为工程交付的一部分。",
    industry: "进入欧洲市场的模型与应用厂商需要把合规成本前置，政策能力成为 To B/To G 竞争门槛。",
    future: "观察 GPAI 义务、实施准则和高风险系统标准如何改变模型发布与采购。",
    business: "企业采购需要同时评估模型能力、部署地区、数据边界和法规责任。",
    category: "policy",
    company: "European Union",
    keywords: ["EU AI Act", "GPAI", "合规", "To G"],
    scores: [99, 0, 92, 90],
    date: "2024-08-01T00:00:00.000Z",
    source: "eu-ai-office",
    url: "https://digital-strategy.ec.europa.eu/en/news/european-artificial-intelligence-act-comes-force",
    tracks: ["commercialization", "investing", "to-b", "to-g"],
    actors: [],
  }),
  event({
    slug: "openai-o1-test-time-reasoning",
    title: "OpenAI o1 预览：能力扩展从训练 Scaling 转向推理时计算",
    fact: "OpenAI 发布 o1-preview 与 o1-mini，模型会在回答前投入更多推理计算。",
    summary: "推理时计算成为新的能力杠杆，行业开始从即时生成转向可分配思考预算的问题求解。",
    technical: "强化学习和长链推理让数学、代码与科学问题的性能随推理预算增长。",
    industry: "模型定价、延迟和能力不再是一条固定曲线，推理基础设施与任务路由的重要性上升。",
    future: "观察可验证推理、错误恢复、长链成本和推理过程可控性。",
    business: "高价值复杂任务可以接受更高延迟与成本，企业应按任务价值而非统一 token 单价选模。",
    category: "reasoning",
    company: "OpenAI",
    keywords: ["o1", "推理时计算", "强化学习", "reasoning"],
    scores: [99, 0, 98, 95],
    date: "2024-09-12T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-openai-o1-preview/",
    tracks: ["tech-evolution", "agi-progress", "model-economics", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "qwen-2-5-open-model-matrix",
    title: "Qwen2.5 发布：中国开放模型形成全尺寸与垂直模型矩阵",
    fact: "阿里巴巴 Qwen 团队发布 Qwen2.5 系列，覆盖 0.5B 到 72B，并扩展代码、数学和视觉语言模型。",
    summary:
      "中国模型竞争从单点旗舰转向尺寸、任务和部署形态完整覆盖，开放生态成为参与全球创新的重要路径。",
    technical: "统一模型家族降低了从端侧到云端、从通用到代码/数学任务的迁移成本。",
    industry: "阿里把模型、云 API 与开源社区连接起来，强化国内开发者分发和海外影响力。",
    future: "观察海外开发者采用、端侧部署、企业微调和与国际前沿模型的差距变化。",
    business: "国内 To D 团队获得门槛更低的基础模型，云厂商可通过托管、数据和工具链承接商业价值。",
    category: "model-release",
    company: "Alibaba / Qwen",
    keywords: ["Qwen2.5", "开放模型", "中国创新", "模型矩阵"],
    scores: [97, 0, 90, 90],
    date: "2024-09-19T00:00:00.000Z",
    source: "qwen",
    url: "https://qwenlm.github.io/blog/qwen2.5/",
    tracks: ["tech-evolution", "global-innovation", "to-d", "commercialization"],
    actors: ["alibaba"],
  }),
  event({
    slug: "claude-computer-use",
    title: "Claude Computer Use：模型开始直接操作通用软件界面",
    fact: "Anthropic 发布计算机使用能力测试版，Claude 可以观察屏幕并操作鼠标和键盘。",
    summary:
      "Agent 不再依赖每个应用提供专用 API，通用界面操作打开了更广的自动化空间，也暴露出可靠性与安全难题。",
    technical: "视觉定位、操作规划、状态反馈和长任务纠错第一次被组合成通用桌面执行能力。",
    industry: "RPA、浏览器自动化和模型 Agent 的边界开始融合。",
    future: "观察真实任务成功率、提示注入防护、权限隔离和人工接管。",
    business: "优先选择可验证、可回滚的窄流程，避免把演示成功率直接等同生产 ROI。",
    category: "agent",
    company: "Anthropic",
    keywords: ["Computer Use", "Agent", "GUI", "自动化"],
    scores: [98, 0, 95, 94],
    date: "2024-10-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/3-5-models-and-computer-use",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["anthropic"],
  }),
  event({
    slug: "model-context-protocol",
    title: "MCP 开源：Agent 的工具连接开始形成公共协议",
    fact: "Anthropic 开源 Model Context Protocol，用统一方式连接 AI 助手、数据源和工具。",
    summary:
      "模型与外部系统的连接从厂商私有插件走向可复用协议，Agent 生态开始出现类似 USB 的接口层。",
    technical: "Client、server、resource 与 tool 的标准化降低了上下文接入和工具复用成本。",
    industry: "竞争焦点从谁拥有最多插件转向谁控制客户端、权限、目录和运行时。",
    future: "观察跨厂商支持、鉴权、安全沙箱、远程 MCP 和企业治理。",
    business: "To D 公司应优先提供协议兼容的能力资产，而非只绑定单一模型平台。",
    category: "developer-platform",
    company: "Anthropic",
    keywords: ["MCP", "Agent 协议", "工具调用", "生态"],
    scores: [98, 0, 96, 96],
    date: "2024-11-25T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/model-context-protocol",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["anthropic"],
  }),
  event({
    slug: "gemini-2-agentic-era",
    title: "Gemini 2.0 发布：Google 把多模态模型推进到 Agent 系统",
    fact: "Google 发布 Gemini 2.0 Flash，并展示 Project Astra、Mariner 和代码 Agent 等原型。",
    summary:
      "模型能力被组织为感知、推理、工具使用和行动的完整系统，Google 开始把搜索、浏览器、Android 与模型结合。",
    technical: "原生多模态输入输出、工具调用和低延迟推理让实时 Agent 成为产品主线。",
    industry: "拥有浏览器、移动操作系统和搜索入口的平台获得结构性分发优势。",
    future: "观察原型向稳定产品转化的速度，以及跨产品权限和用户信任。",
    business: "独立 Agent 产品必须拥有 Google 难以复制的行业流程、数据或完整交付能力。",
    category: "model-release",
    company: "Google DeepMind",
    keywords: ["Gemini 2.0", "Project Astra", "Mariner", "多模态 Agent"],
    scores: [98, 0, 96, 95],
    date: "2024-12-11T00:00:00.000Z",
    source: "google-ai",
    url: "https://blog.google/technology/google-deepmind/google-gemini-ai-update-december-2024/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-c", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "deepseek-v3-efficient-frontier",
    title: "DeepSeek-V3 开源：训练效率成为全球模型竞争的新变量",
    fact: "DeepSeek 发布并开放 DeepSeek-V3 权重与技术报告，采用 671B MoE、37B 激活参数和 FP8 训练。",
    summary:
      "DeepSeek 用架构、系统和工程协同压低前沿模型训练成本，证明不同资源条件可以形成独立的前沿创新路径。",
    technical: "MLA、DeepSeekMoE、无辅助损失负载均衡、MTP 和 FP8 共同提升训练与推理效率。",
    industry: "模型竞争增加了单位算力产出这一核心维度，并推动国内硬件与推理栈适配。",
    future: "观察独立复现、真实 API 负载、国产算力适配和后续推理模型。",
    business: "成本效率会压缩通用 API 毛利，但扩大模型进入低客单价业务的空间。",
    category: "model-release",
    company: "DeepSeek",
    keywords: ["DeepSeek-V3", "MoE", "FP8", "训练效率"],
    scores: [98, 0, 97, 96],
    date: "2024-12-26T00:00:00.000Z",
    source: "deepseek",
    url: "https://github.com/deepseek-ai/DeepSeek-V3",
    tracks: ["tech-evolution", "global-innovation", "model-economics", "to-d", "investing"],
    actors: ["deepseek"],
  }),
  event({
    slug: "deepseek-r1-open-reasoning",
    title: "DeepSeek-R1 开源：推理能力与低成本冲击全球模型格局",
    fact: "DeepSeek 发布 R1、R1-Zero 和蒸馏模型，公开权重与技术方法。",
    summary:
      "中国团队把前沿推理能力、开放权重和极具竞争力的价格组合起来，促使全球市场重新评估算力壁垒和模型定价。",
    technical: "纯强化学习、冷启动、多阶段训练和蒸馏展示了可复用的推理能力构建路线。",
    industry: "开放推理模型加速价格下降，并让中国模型第一次成为全球开发者和资本市场的共同变量。",
    future: "观察真实工具使用、长任务可靠性、蒸馏生态和下一代训练成本。",
    business: "通用模型溢价承压，应用公司更应把价值建立在数据、流程和分发而非模型转售。",
    category: "reasoning",
    company: "DeepSeek",
    keywords: ["DeepSeek-R1", "推理", "强化学习", "开放权重"],
    scores: [99, 0, 99, 99],
    date: "2025-01-20T00:00:00.000Z",
    source: "deepseek",
    url: "https://github.com/deepseek-ai/DeepSeek-R1",
    tracks: ["tech-evolution", "agi-progress", "global-innovation", "investing", "model-economics"],
    actors: ["deepseek"],
  }),
  event({
    slug: "openai-operator-browser-agent",
    title: "Operator 发布：OpenAI 从对话产品进入浏览器任务执行",
    fact: "OpenAI 发布 Operator 研究预览，模型可以在浏览器中点击、输入并完成多步骤任务。",
    summary:
      "ChatGPT 的产品边界从回答问题扩展到代替用户执行，消费级 Agent 开始验证真实交易与服务流程。",
    technical:
      "Computer-Using Agent 已能连续完成视觉识别、推理和交互动作，但仍需要频繁的人类确认。",
    industry: "浏览器成为 Agent 的通用执行层，电商、旅行和本地服务平台需要重新考虑机器用户。",
    future: "观察支付/登录场景、反自动化策略、成功率和责任边界。",
    business: "To C Agent 的核心指标应从使用时长转为完成任务数、节省时间和交易转化。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["Operator", "Browser Agent", "CUA", "To C"],
    scores: [98, 0, 95, 94],
    date: "2025-01-23T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-operator/",
    tracks: ["tech-evolution", "commercialization", "to-c", "agi-progress"],
    actors: ["openai"],
  }),
  event({
    slug: "openai-deep-research",
    title: "Deep Research 发布：Agent 首次把复杂知识工作做成标准产品",
    fact: "OpenAI 在 ChatGPT 发布 Deep Research，可自主搜索、分析并综合大量在线来源。",
    summary:
      "长时研究任务成为可购买的消费与专业能力，Agent 的价值从即时回答转向替代数小时知识劳动。",
    technical: "浏览、检索、证据选择、长上下文推理和报告生成被组合成持续数十分钟的工作流。",
    industry: "研究、咨询、投研和专业信息服务开始面对结果型 AI 产品的直接竞争。",
    future: "观察引用准确性、付费使用量、垂直数据库接入和结果责任。",
    business: "专业服务团队应把 AI 用于扩大研究覆盖，并把差异化转向私有数据与判断框架。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["Deep Research", "研究 Agent", "知识工作", "ChatGPT"],
    scores: [98, 0, 96, 97],
    date: "2025-02-02T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-deep-research/",
    tracks: ["agi-progress", "commercialization", "to-c", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-3-7-code-preview",
    title: "Claude 3.7 与 Claude Code：混合推理进入开发者工作流",
    fact: "Anthropic 发布 Claude 3.7 Sonnet，并预览在终端中工作的 Claude Code。",
    summary: "模型厂商不再只提供模型能力，而是直接占据代码库、终端和工程任务入口。",
    technical: "可控扩展思考与 Agent 工具循环结合，让模型在速度、成本和任务深度之间动态取舍。",
    industry: "编码助手从补全和聊天升级为能规划、修改、测试与提交的工程协作者。",
    future: "观察真实 PR 合并率、长任务恢复、代码安全和团队级治理。",
    business: "开发工具市场的价值将集中到上下文、执行环境、评测和组织工作流。",
    category: "coding-agent",
    company: "Anthropic",
    keywords: ["Claude 3.7", "Claude Code", "混合推理", "编码 Agent"],
    scores: [99, 0, 97, 98],
    date: "2025-02-24T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-3-7-sonnet",
    tracks: ["tech-evolution", "agi-progress", "to-d", "commercialization"],
    actors: ["anthropic"],
  }),
  event({
    slug: "openai-responses-agents-sdk",
    title: "Responses API 与 Agents SDK：OpenAI 建立 Agent 开发平台",
    fact: "OpenAI 发布 Responses API、内置 Web/File/Computer Use 工具和开源 Agents SDK。",
    summary:
      "Agent 从应用团队自组装的框架变成模型平台的标准产品层，工具、追踪和编排被纳入统一 API。",
    technical: "托管工具、handoff、tracing 和状态管理降低了多步 Agent 的工程门槛。",
    industry: "模型 API 厂商开始向 Agent runtime 扩张，与开源框架和自动化平台正面竞争。",
    future: "观察锁定成本、跨模型兼容、可观测性和企业权限治理。",
    business: "To D 产品需要在开放性、行业组件或运行治理上建立差异化。",
    category: "developer-platform",
    company: "OpenAI",
    keywords: ["Responses API", "Agents SDK", "工具调用", "开发平台"],
    scores: [99, 0, 95, 97],
    date: "2025-03-11T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/new-tools-for-building-agents/",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["openai"],
  }),
  event({
    slug: "nvidia-blackwell-ultra-reasoning-factory",
    title: "Blackwell Ultra 发布：推理时 Scaling 重塑 AI 基础设施",
    fact: "NVIDIA 在 GTC 2025 发布 Blackwell Ultra、Dynamo 和面向推理 Agent 的 AI Factory 平台。",
    summary: "算力需求从集中训练扩展到持续、高并发、长链推理，推理吞吐和数据中心协同成为新瓶颈。",
    technical: "GB300、Dynamo、网络和存储共同围绕 test-time scaling 与 Agent 工作负载优化。",
    industry: "芯片价值继续向完整系统、网络、软件和电力基础设施延伸。",
    future: "观察推理收入占比、集群利用率、能源约束和替代加速器。",
    business: "投资判断要从 GPU 出货转向单位推理产出、部署周期和数据中心现金流。",
    category: "infrastructure",
    company: "NVIDIA",
    keywords: ["Blackwell Ultra", "Dynamo", "推理基础设施", "AI Factory"],
    scores: [99, 0, 97, 96],
    date: "2025-03-18T00:00:00.000Z",
    source: "nvidia-blog-ai",
    url: "https://nvidianews.nvidia.com/online-press-kit/gtc-2025-news",
    tracks: ["tech-evolution", "investing", "model-economics", "to-b"],
    actors: ["nvidia"],
  }),
  event({
    slug: "gemini-2-5-thinking-model",
    title: "Gemini 2.5 发布：思考模型成为前沿模型默认形态",
    fact: "Google 发布 Gemini 2.5 Pro 实验版，将推理能力内置为模型的核心能力。",
    summary: "推理从独立产品线变为旗舰模型的默认属性，长上下文、多模态与思考开始合流。",
    technical: "大上下文、代码能力和推理时计算共同面向复杂 Agent 与知识任务。",
    industry: "前沿厂商竞争从是否有 reasoning model 转向单位成本、延迟和产品整合。",
    future: "观察稳定版价格、工具使用、长上下文有效利用率和企业分发。",
    business: "应用团队应减少对固定模型标签的依赖，建立任务级路由和持续评测。",
    category: "reasoning",
    company: "Google DeepMind",
    keywords: ["Gemini 2.5", "Thinking Model", "长上下文", "推理"],
    scores: [98, 0, 96, 94],
    date: "2025-03-25T00:00:00.000Z",
    source: "google-ai",
    url: "https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/",
    tracks: ["tech-evolution", "agi-progress", "model-economics", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "llama-4-native-multimodal-moe",
    title: "Llama 4 发布：开放模型转向原生多模态 MoE",
    fact: "Meta 发布 Llama 4 Scout 与 Maverick，采用原生多模态和混合专家架构。",
    summary: "开放模型路线跟进多模态、超长上下文和稀疏激活，继续压缩闭源模型的基础能力差异。",
    technical: "MoE 让总参数规模与推理成本解耦，Scout 将上下文扩展到千万 token 级别。",
    industry: "开放生态进入复杂系统竞争，但训练透明度、评测可信度和部署门槛仍是约束。",
    future: "观察社区复现、实际上下文利用、企业部署和后续旗舰模型。",
    business: "私有化与开放权重方案更丰富，企业需要评估总拥有成本而不是只看 benchmark。",
    category: "model-release",
    company: "Meta",
    keywords: ["Llama 4", "MoE", "原生多模态", "开放模型"],
    scores: [97, 0, 91, 88],
    date: "2025-04-05T00:00:00.000Z",
    source: "meta-ai",
    url: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["meta"],
  }),
  event({
    slug: "google-a2a-agent-protocol",
    title: "Google A2A 发布：多 Agent 协作进入协议竞争",
    fact: "Google 联合多家企业发布 Agent2Agent Protocol，用于不同平台和厂商 Agent 之间协作。",
    summary: "在 MCP 解决 Agent 与工具连接之后，A2A 把标准化推进到 Agent 身份、任务和结果交换。",
    technical: "Agent Card、任务生命周期、消息与 artifact 形成跨组织协作的公共抽象。",
    industry: "Agent 生态开始从单体应用转向协议、目录、身份和治理组成的网络。",
    future: "观察 MCP/A2A 分工、企业身份、跨域授权和实际互操作案例。",
    business: "平台型产品应把能力封装为可发现、可授权、可审计的 Agent 服务。",
    category: "developer-platform",
    company: "Google",
    keywords: ["A2A", "Agent2Agent", "互操作", "协议"],
    scores: [98, 0, 92, 94],
    date: "2025-04-09T00:00:00.000Z",
    source: "google-developers",
    url: "https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/",
    tracks: ["tech-evolution", "to-d", "to-b", "commercialization"],
    actors: ["google"],
  }),
  event({
    slug: "openai-o3-o4-mini-tools",
    title: "o3 与 o4-mini 发布：推理模型开始主动调用全套工具",
    fact: "OpenAI 发布 o3 和 o4-mini，并让推理模型在 ChatGPT 中组合使用浏览、代码、文件和图像工具。",
    summary: "推理与行动合流，模型从在单一上下文中思考转向选择工具、验证结果并完成任务。",
    technical: "模型原生工具选择把规划、执行和检查纳入统一推理过程。",
    industry: "Agent 能力逐渐内建进旗舰模型，纯编排层产品面临价值压缩。",
    future: "观察工具选择准确性、错误恢复、长任务成本和安全控制。",
    business: "应用公司的竞争力需要建立在专有数据、权限体系、评测和完整业务流程上。",
    category: "reasoning",
    company: "OpenAI",
    keywords: ["o3", "o4-mini", "工具使用", "Agent"],
    scores: [99, 0, 97, 96],
    date: "2025-04-16T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-o3-and-o4-mini/",
    tracks: ["tech-evolution", "agi-progress", "to-c", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "qwen-3-hybrid-thinking",
    title: "Qwen3 开源：中国模型进入混合推理与 Agent 阶段",
    fact: "Qwen 团队发布 Qwen3 系列开放模型，支持 thinking/non-thinking 切换与多语言能力。",
    summary: "国产开放模型快速吸收推理时计算和 MoE 路线，并把成本、尺寸和部署选择做成完整矩阵。",
    technical: "混合推理允许同一模型按任务切换思考预算，MoE 提升参数容量与推理效率。",
    industry: "中国模型与全球前沿的技术代差缩短，竞争转向生态、产品、算力和海外分发。",
    future: "观察 Agent 工具使用、海外采用、企业落地和下一代旗舰模型。",
    business: "国内 To D 市场的模型供给更充分，价值继续向工具链和行业数据迁移。",
    category: "model-release",
    company: "Alibaba / Qwen",
    keywords: ["Qwen3", "混合推理", "MoE", "中国创新"],
    scores: [98, 0, 94, 94],
    date: "2025-04-29T00:00:00.000Z",
    source: "qwen",
    url: "https://qwenlm.github.io/blog/qwen3/",
    tracks: ["tech-evolution", "agi-progress", "global-innovation", "to-d"],
    actors: ["alibaba"],
  }),
  event({
    slug: "openai-codex-cloud-agent",
    title: "Codex 云端 Agent 发布：编码任务从辅助转向委派",
    fact: "OpenAI 发布 Codex 研究预览，可在隔离云环境中并行处理代码库任务。",
    summary:
      "开发者可以把修复、测试和代码理解任务交给后台 Agent，编码产品从同步对话进入异步任务队列。",
    technical: "隔离环境、仓库上下文、并行执行和可审查变更是可靠编码 Agent 的关键系统能力。",
    industry: "GitHub、IDE、终端和云 Agent 开始争夺软件交付的控制面。",
    future: "观察 PR 合并率、运行成本、安全边界和团队协作模式。",
    business:
      "软件团队采用 Agent 时，需要同步建立权限、评审、CI 和产能度量，购买个人席位只是第一步。",
    category: "coding-agent",
    company: "OpenAI",
    keywords: ["Codex", "云端 Agent", "异步编码", "软件工程"],
    scores: [98, 0, 97, 98],
    date: "2025-05-16T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-codex/",
    tracks: ["tech-evolution", "commercialization", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-4-long-running-agents",
    title: "Claude 4 发布：长时编码与 Agent 能力成为旗舰卖点",
    fact: "Anthropic 发布 Claude Opus 4 与 Sonnet 4，强调编码、工具使用和长任务能力。",
    summary: "前沿模型的评价中心继续从聊天质量转向可持续执行真实工作的可靠性。",
    technical: "混合推理、并行工具、记忆与长任务行为围绕 Agent 工作负载优化。",
    industry: "Anthropic 以 Claude Code 和企业 API 将模型优势直接转化为开发者与企业产品。",
    future: "观察长任务成功率、Agent 安全等级、企业收入和模型成本。",
    business: "编码与知识工作成为模型商业化最清晰的高价值入口。",
    category: "model-release",
    company: "Anthropic",
    keywords: ["Claude 4", "Opus 4", "Sonnet 4", "长任务"],
    scores: [99, 0, 97, 98],
    date: "2025-05-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-4",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-d", "to-b"],
    actors: ["anthropic"],
  }),
  event({
    slug: "minimax-m1-long-context-reasoning",
    title: "MiniMax-M1 开源：国产推理模型竞争延伸到百万上下文",
    fact: "MiniMax 发布并开源 M1 混合注意力推理模型，提供百万 token 输入上下文。",
    summary: "国产模型厂商开始在推理、长上下文、Agent 工具使用和成本之间寻找差异化路线。",
    technical: "Lightning Attention 与混合注意力降低长上下文计算成本，面向复杂生产力任务。",
    industry: "国内前沿模型从跟随单一 benchmark 转向架构和产品约束共同优化。",
    future: "观察开源复现、长上下文有效性、API 使用和 Agent 产品转化。",
    business: "长文档、代码库和企业知识场景获得更低成本的国产模型选项。",
    category: "reasoning",
    company: "MiniMax",
    keywords: ["MiniMax-M1", "长上下文", "混合注意力", "开源"],
    scores: [96, 0, 88, 88],
    date: "2025-06-16T00:00:00.000Z",
    source: "minimax",
    url: "https://www.minimax.io/news/minimaxm1",
    tracks: ["tech-evolution", "global-innovation", "to-d", "model-economics"],
    actors: ["minimax"],
  }),
  event({
    slug: "kimi-k2-agentic-open-model",
    title: "Kimi K2 开放：Moonshot 把国产模型竞争推向 Agent 与代码",
    fact: "Moonshot AI 发布 Kimi K2 混合专家模型并开放权重，重点强化代码和 Agent 工具使用。",
    summary: "中国头部创业公司从消费级长文本产品延伸到开放基础模型和开发者生态。",
    technical: "大规模 MoE、工具调用和代码训练面向可执行 Agent，而不仅是对话体验。",
    industry: "国内模型厂商同时争夺 To C 用户、To D 生态和海外开发者。",
    future: "观察 API 收入、权重采用、工具调用可靠性和海外生态。",
    business: "创业公司需要证明开放模型能够反向增强付费产品和平台分发。",
    category: "model-release",
    company: "Moonshot AI",
    keywords: ["Kimi K2", "MoE", "Agent", "开放权重"],
    scores: [96, 0, 91, 91],
    date: "2025-07-11T00:00:00.000Z",
    source: "moonshot",
    url: "https://github.com/MoonshotAI/Kimi-K2",
    tracks: ["tech-evolution", "global-innovation", "commercialization", "to-c", "to-d"],
    actors: ["moonshot"],
  }),
  event({
    slug: "chatgpt-agent-research-to-action",
    title: "ChatGPT Agent 发布：研究、浏览与行动合并为统一模式",
    fact: "OpenAI 发布 ChatGPT Agent，将 Operator 的操作、Deep Research 的研究和对话能力整合。",
    summary: "消费级 AI 产品开始从多个实验入口转向目标驱动的通用任务执行模式。",
    technical: "视觉浏览器、文本浏览器、终端、连接器和人工确认共同组成多工具 Agent runtime。",
    industry: "模型、产品入口和执行环境进一步合并，独立通用 Agent 的生存空间缩小。",
    future: "观察高频任务、成功率、交易安全和订阅留存。",
    business:
      "To C 团队应围绕结果、信任和完整垂直场景建立优势，复制通用聊天与浏览能力很难形成差异。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["ChatGPT Agent", "Operator", "Deep Research", "任务执行"],
    scores: [99, 0, 98, 98],
    date: "2025-07-17T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-chatgpt-agent/",
    tracks: ["agi-progress", "commercialization", "to-c", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "gpt-5-unified-routing",
    title: "GPT-5 发布：快模型与深度推理被统一到一个产品入口",
    fact: "OpenAI 发布 GPT-5，并在 ChatGPT 中通过统一系统路由即时回答和更深推理。",
    summary: "用户不再需要理解复杂模型菜单，模型选择开始由平台按任务难度、成本和延迟自动完成。",
    technical: "路由器、能力模型与安全策略共同决定每个请求的计算预算。",
    industry: "模型品牌让位于产品级体验，平台对成本、分发和用户反馈的控制增强。",
    future: "观察路由质量、API 迁移、单位任务成本和用户对模型人格的偏好。",
    business: "企业应建立自己的任务评测和路由策略，避免把平台默认选择当作最优解。",
    category: "model-release",
    company: "OpenAI",
    keywords: ["GPT-5", "模型路由", "推理", "ChatGPT"],
    scores: [99, 0, 99, 98],
    date: "2025-08-07T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-gpt-5/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "model-economics"],
    actors: ["openai"],
  }),
  event({
    slug: "codex-general-availability",
    title: "Codex 正式可用：编码 Agent 从实验进入团队基础设施",
    fact: "OpenAI 宣布 Codex 正式可用，并发布 SDK、Slack 集成和企业管理能力。",
    summary: "编码 Agent 从单点云任务发展为连接 IDE、终端、团队沟通和组织管理的协作系统。",
    technical: "SDK、运行环境、权限和监控把 Agent 纳入可编程的软件交付流水线。",
    industry: "编码 Agent 的竞争开始从模型能力转向工作流覆盖、团队治理和生态嵌入。",
    future: "观察企业席位、实际代码产出、SDK 生态和安全事故率。",
    business: "软件组织需要调整开发者产能的衡量方式，并明确评审责任和 Agent 使用政策。",
    category: "coding-agent",
    company: "OpenAI",
    keywords: ["Codex", "GA", "SDK", "团队协作"],
    scores: [99, 0, 96, 98],
    date: "2025-10-06T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/codex-now-generally-available/",
    tracks: ["commercialization", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-constitution-2026",
    title: "Claude 新宪法发布：模型行为治理走向可审查的制度层",
    fact: "Anthropic 发布 2026 版 Claude Constitution，系统说明模型的价值、行为原则和冲突处理。",
    summary: "前沿模型治理从简单规则列表走向更完整、可讨论的行为框架，安全与产品人格开始合流。",
    technical: "宪法式训练为复杂情境中的原则权衡提供显式监督结构。",
    industry: "模型厂商需要同时竞争能力、可控性、信任和制度透明度。",
    future: "观察外部评测、行为一致性、企业可配置性和监管接受度。",
    business: "高风险行业采购需要把模型行为政策纳入技术和法律尽调。",
    category: "safety-governance",
    company: "Anthropic",
    keywords: ["Claude Constitution", "对齐", "治理", "安全"],
    scores: [98, 0, 88, 89],
    date: "2026-01-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-new-constitution",
    tracks: ["agi-progress", "to-b", "to-g"],
    actors: ["anthropic"],
  }),
  event({
    slug: "claude-opus-4-7-agent-work",
    title: "Claude Opus 4.7 发布：前沿能力继续聚焦复杂工作与 Agent",
    fact: "Anthropic 发布 Claude Opus 4.7，重点提升代码、Agent、视觉和多步骤任务表现。",
    summary: "模型升级的价值越来越以完成复杂工作来衡量，而不是单一知识或生成 benchmark。",
    technical: "长任务规划、工具使用、视觉理解和一致性成为统一能力包。",
    industry: "Anthropic 继续把模型能力接入 Claude Code、Cowork 和企业工作场景。",
    future: "观察真实任务完成率、企业收入、推理成本和安全边界。",
    business: "To B 竞争需要同时拥有模型、执行环境、权限和行业工作流。",
    category: "model-release",
    company: "Anthropic",
    keywords: ["Claude Opus 4.7", "Agent", "编码", "复杂工作"],
    scores: [98, 0, 95, 96],
    date: "2026-04-16T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-opus-4-7",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["anthropic"],
  }),
  event({
    slug: "gpt-5-5-real-work",
    title: "GPT-5.5 发布：模型升级开始按端到端工作结果衡量",
    fact: "OpenAI 发布 GPT-5.5，重点提升编码、研究、数据分析、文档和跨工具操作。",
    summary: "前沿竞争从回答质量继续转向能否理解模糊目标、跨工具执行并检查结果。",
    technical: "Agentic coding、computer use、科学研究和长时执行被统一到旗舰模型。",
    industry: "模型与办公、开发和研究产品的边界进一步消失。",
    future: "观察单位任务成本、失败恢复、工作流接管和企业采用。",
    business: "CEO 应以完整流程节省和结果质量评估模型，而非只比较 token 价格。",
    category: "model-release",
    company: "OpenAI",
    keywords: ["GPT-5.5", "真实工作", "Computer Use", "Agent"],
    scores: [99, 0, 98, 98],
    date: "2026-04-23T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-gpt-5-5/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "anthropic-series-h-scale",
    title: "Anthropic 完成 Series H：模型竞争进入资本、收入与算力共振",
    fact: "Anthropic 宣布完成 650 亿美元 Series H 融资，投后估值 9650 亿美元，并披露年化收入超过 470 亿美元。",
    summary: "前沿模型公司的资本需求、商业收入和算力扩张同步放大，行业集中度继续上升。",
    technical: "持续训练、推理服务和 Agent 产品扩张把资本开支转化为长期基础设施竞争。",
    industry:
      "模型公司正在形成接近云平台的资本密度和收入规模，创业窗口向应用、数据和垂直系统迁移。",
    future: "观察收入质量、算力承诺、企业留存和估值消化。",
    business: "投资判断应把模型收入、推理毛利、资本开支和产品粘性放在同一张表中。",
    category: "investment",
    company: "Anthropic",
    keywords: ["Series H", "融资", "算力", "企业收入"],
    scores: [99, 0, 99, 97],
    date: "2026-05-28T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/series-h",
    tracks: ["investing", "commercialization", "to-b", "model-economics"],
    actors: ["anthropic"],
  }),
  event({
    slug: "predicatelongbench-long-context-difficulty",
    title: "PredicateLongBench：长上下文评测开始测量“任务难度”而非只测长度",
    fact: "2026 年 7 月 9 日提交的 PredicateLongBench 预印本提出可控生成长上下文任务的两条流水线，并报告前沿模型随谓词难度上升出现明显性能下降。",
    summary:
      "长上下文能力长期被“上下文窗口有多长”主导，但窗口可容纳信息不等于模型能在复杂约束下可靠找到并组合证据。该研究把长度与任务难度拆开控制，为企业文档、研究和 Agent 评测提供更接近真实工作的压力测试思路。",
    technical:
      "论文通过谓词结构控制检索条件、组合关系和推理复杂度，并以两类生成流程构造可重复的数据。它提供了一条难度轴，使团队能观察模型在上下文长度相同、约束复杂度不同条件下的退化曲线，信息量高于单一平均分。",
    industry:
      "模型厂商仅公布长上下文窗口和单一 benchmark 分数将更难支持采购判断；应用团队需要围绕自己的文档结构、约束数量和证据组合方式建立分层评测。",
    future:
      "这是尚未完成独立复现的预印本。下一步应检查数据生成是否引入捷径、不同模型版本的复现实验，以及难度轴与真实法律、金融和研发文档任务的相关性。",
    business:
      "采购长上下文模型时，应把“最大窗口”替换为按任务难度分层的成功率、重试率和人工核验成本，避免为无法转化为可靠结果的容量付费。",
    category: "research",
    company: "PredicateLongBench",
    keywords: ["长上下文", "benchmark", "难度轴", "评测"],
    scores: [92, 0, 84, 86],
    date: "2026-07-09T09:28:06.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08284",
    tracks: ["tech-evolution", "agi-progress", "to-d", "to-b"],
    actors: [],
  }),
  event({
    slug: "compete-then-collaborate-multi-agent",
    title: "Compete Then Collaborate：多智能体推理不再默认“越合作越好”",
    fact: "2026 年 7 月 9 日提交的预印本 Compete Then Collaborate 提出先让 Agent 独立竞争、再选择性协作的推理框架，用于降低过早共识和错误传播。",
    summary:
      "多智能体系统常用更多讨论轮次提高质量，但 Agent 过早共享中间结论也可能放大同一种错误。该研究将独立探索与后续协作分阶段，提示系统设计需要同时关注观点多样性、选择机制、协作时机和 Agent 数量。",
    technical:
      "框架先保留多个独立解题轨迹，再根据候选质量和差异选择进入协作的方案，从结构上减少早期信息污染。技术判断重点应放在选择器是否可靠、额外推理成本、不同任务上的收益稳定性，以及失败案例能否互补。",
    industry:
      "Agent 平台的竞争将从编排更多角色转向管理推理多样性和协作预算；企业不应把角色数量、消息数量或工作流复杂度直接当成更高可靠性的证据。",
    future:
      "该结果仍属于预印本证据。需要独立复现其基线、公平比较单 Agent 的等成本推理，并验证在代码、研究和工具调用任务中能否保持收益。",
    business:
      "设计高价值 Agent 流程时，可用“独立候选 → 质量门控 → 有条件协作”替代全程群聊，并以每个正确结果的总推理成本衡量是否值得。",
    category: "research",
    company: "Compete Then Collaborate",
    keywords: ["多智能体", "协作", "推理", "Agent 编排"],
    scores: [91, 0, 85, 84],
    date: "2026-07-09T08:32:31.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08255",
    tracks: ["tech-evolution", "agi-progress", "to-d"],
    actors: [],
  }),
  event({
    slug: "autopersonas-agent-simulation-diversity",
    title: "AutoPersonas：Agent 模拟的瓶颈从规模转向角色多样性与重复污染",
    fact: "2026 年 7 月 9 日提交的 AutoPersonas 预印本分析 8 个模型生成的 1,600 个角色，并讨论自动生成 Persona 时的重复、偏差与有效多样性问题。",
    summary:
      "用大量虚拟用户或专家 Agent 做产品研究看似可以低成本扩样，但角色数量并不等于观点覆盖。研究把 Persona 生成本身变成可测量对象，揭示重复模板和模型偏差可能制造虚假的“用户共识”。",
    technical:
      "论文比较多模型生成角色的语义覆盖、重复模式与人口属性分布，核心方法是把 Persona 集合质量从主观观感转成多样性和冗余指标。对模拟系统而言，采样策略、去重和真实用户校准与下游 Agent 能力同等重要。",
    industry:
      "合成用户研究、市场模拟和多 Agent 社会实验需要新的数据质量规范；未经覆盖度与偏差审计的 Persona 池不能替代真实访谈或被包装成市场证据。",
    future:
      "预印本结论仍需在更多语言、地区和垂直人群中复现，并检验角色多样性指标能否预测下游决策质量，避免指标只反映文本表面差异。",
    business:
      "使用合成 Persona 做早期探索时，应保留真实样本校准集，披露模型与采样方法，并把去重率、覆盖缺口和与真实用户的偏差纳入决策置信度。",
    category: "research",
    company: "AutoPersonas",
    keywords: ["Persona", "Agent 模拟", "合成用户", "多样性"],
    scores: [90, 0, 82, 85],
    date: "2026-07-09T08:25:44.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08252",
    tracks: ["tech-evolution", "to-b", "to-d"],
    actors: [],
  }),
  event({
    slug: "blind-spots-bench-vision-language",
    title: "Blind-Spots-Bench：多模态模型高分背后仍有系统性视觉盲区",
    fact: "2026 年 7 月 9 日提交的 Blind-Spots-Bench 预印本构建 235 个样本，评测 10 类视觉语言理解缺口，用于暴露常规平均分容易掩盖的系统性失败。",
    summary:
      "多模态模型在主流 benchmark 上持续提升，但平均准确率难以回答它会在哪类图像关系、局部细节或视觉条件下稳定失败。该研究按盲区类型组织测试，使安全评估从单一排行榜转向可诊断的能力边界。",
    technical:
      "基准通过小规模、类型化样本隔离不同视觉语言缺口，强调失败分布而非总分。落地时需要检查样本规模、任务构造和模型是否见过相似数据，并将类别级召回与置信校准加入真实场景测试。",
    industry:
      "视觉 Agent、文档理解和质检产品不能只引用通用多模态分数；采购和上线门槛需要明确业务中不可接受的盲区，并对这些类别单独验收。",
    future:
      "该预印本样本规模有限，需扩展到真实世界分布、更多语言和视频任务，并验证模型更新后盲区是消失了，还是转移到了其他任务。",
    business:
      "在医疗、制造和文档审核场景，应建立盲区清单、人工接管规则与类别级回归集，把“何时不能信模型”作为部署决策的一部分。",
    category: "research",
    company: "Blind-Spots-Bench",
    keywords: ["多模态", "视觉语言模型", "盲区", "安全评测"],
    scores: [91, 0, 86, 87],
    date: "2026-07-09T11:05:17.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08317",
    tracks: ["tech-evolution", "agi-progress", "to-b"],
    actors: [],
  }),
  event({
    slug: "overthinking-secret-leakage-reasoning-models",
    title: "Overthinking：推理模型的长思考可能把秘密泄露风险放大至 10 倍",
    fact: "2026 年 7 月 9 日提交的 Overthinking 预印本评测 2B 至 32B 参数模型，并报告更长推理过程在部分设置下使秘密泄露风险最高增加约 10 倍。",
    summary:
      "推理时间扩展通常被视为能力增强手段，但更长的中间推理也扩大了模型重建、重复或暴露敏感上下文的机会。研究把“想得更久”与信息泄露联系起来，提示推理预算同时是安全预算。",
    technical:
      "论文跨多个模型规模比较秘密保留与推理长度的关系，关注泄露随计算预算变化的趋势。关键技术问题包括威胁模型、提示设置、可见推理与隐藏状态的差异，以及过滤器是否只是掩盖输出而非降低内部暴露。",
    industry:
      "企业在引入 reasoning model 和长链 Agent 时需要重新审视日志、上下文拼接、可观察性与数据最小化；能力评测不能与隐私和安全评测分开。",
    future:
      "“最高约 10 倍”来自特定预印本实验，不应外推为所有模型。需独立复现不同 API、推理可见性、系统提示和防护机制下的绝对风险。",
    business:
      "高敏数据流程应限制不必要的推理预算与上下文范围，分离秘密，审计日志，并以泄露率随推理预算变化的曲线决定哪些任务可以使用深度推理。",
    category: "research",
    company: "Overthinking",
    keywords: ["推理模型", "秘密泄露", "安全", "推理预算"],
    scores: [91, 0, 91, 92],
    date: "2026-07-09T06:02:41.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08173",
    tracks: ["tech-evolution", "agi-progress", "to-b", "to-g"],
    actors: [],
  }),
  event({
    slug: "causalds-causal-data-science-agents",
    title: "CausalDS：数据科学 Agent 从生成代码走向结构因果推断与拒答",
    fact: "2026 年 7 月 9 日提交的 CausalDS 预印本提出面向数据科学 Agent 的因果评测，覆盖结构因果模型、Pearl 三层因果阶梯与在证据不足时拒绝回答。",
    summary:
      "当前数据 Agent 擅长生成查询、图表和相关性分析，但业务决策需要区分观察、干预与反事实。该研究把因果结构和拒答能力纳入评测，使“能产出分析”与“能支持行动决策”之间的差距变得可见。",
    technical:
      "基准围绕结构因果模型构造关联、干预和反事实问题，并检查模型在不可识别或信息不足时是否能够 abstain。它同时测试推理正确性和模型能否识别信息边界，最终答案格式或代码可运行性只覆盖部分能力。",
    industry:
      "企业数据 Copilot 若不能识别因果假设和证据边界，可能把相关性包装成策略建议；数据 Agent 的验收需要增加因果层级、假设披露和拒答率。",
    future:
      "该研究仍是预印本和受控基准。需验证在脏数据、隐藏混杂、时间序列和真实组织指标中是否成立，并比较工具增强 Agent 与纯模型的差异。",
    business:
      "将数据 Agent 用于定价、增长或运营决策前，应要求它明确因果图、识别假设和不可回答条件，并由领域专家审核干预建议，而非只验收 SQL 与图表。",
    category: "research",
    company: "CausalDS",
    keywords: ["因果推断", "数据科学 Agent", "拒答", "评测"],
    scores: [92, 0, 88, 91],
    date: "2026-07-09T02:51:43.000Z",
    source: "arxiv-ai",
    url: "https://arxiv.org/abs/2607.08093",
    tracks: ["tech-evolution", "to-b", "to-d"],
    actors: [],
  }),
  ...vendorHistoryEvents,
  ...ecosystemHistoryEvents,
  ...capitalHistoryEvents,
  ...directResearchHistory2026,
  ...researchHistory2022To2025,
  ...researchHistory2026,
] as const satisfies readonly CuratedEventSeed[];

export const industryNarratives = {
  horizon: { start: "2022-08-22", end: "2026-07-13", label: "2022—今天" },
  eras: [
    {
      slug: "public-generative-ai",
      label: "生成式 AI 进入大众市场",
      period: "2022 H2",
      summary:
        "Stable Diffusion 把生成模型带入开放生态，ChatGPT 把大模型从研究能力变成大众每天可以使用的产品。",
      projects: [
        {
          name: "ChatGPT",
          status: "active",
          note: "从 research preview 演化为通用 AI 产品入口。",
          url: "https://openai.com/index/chatgpt/",
        },
        {
          name: "Stable Diffusion",
          status: "active",
          note: "开放权重持续支撑图像生成生态。",
          url: "https://stability.ai/news-updates/stable-diffusion-public-release",
        },
      ],
    },
    {
      slug: "model-platforms-and-copilots",
      label: "模型平台与 Copilot 成形",
      period: "2023",
      summary:
        "GPT-4、Claude 2、Llama 2、Qwen、Mistral 与 Gemini 建立多路线竞争，API、插件和 Copilot 开始进入软件与组织工作流。",
      projects: [
        {
          name: "Microsoft 365 Copilot",
          status: "active",
          note: "将模型、组织数据和办公工作流绑定为企业产品。",
          url: "https://blogs.microsoft.com/blog/2023/03/16/introducing-microsoft-365-copilot-your-copilot-for-work/",
        },
        {
          name: "Artifact",
          status: "acquired",
          note: "独立应用停止后，个性化技术由 Yahoo 收购并继续整合。",
          url: "https://www.yahooinc.com/press/yahoo-announces-the-acquisition-of-artifact-the-news-discovery-platform-created-by-instagram-cofounders-kevin-systrom-and-mike-krieger",
        },
      ],
    },
    {
      slug: "multimodal-and-reasoning",
      label: "多模态、推理与应用分化",
      period: "2024",
      summary:
        "原生多模态与推理时计算打开新的能力曲线，开放模型继续提升；应用市场同时进入整合，单一包装型产品开始失去空间。",
      projects: [
        {
          name: "Inflection AI",
          status: "pivoted",
          note: "联合创始人与部分团队加入 Microsoft AI 后，原有消费助手路线进入组织与战略重构。",
          url: "https://blogs.microsoft.com/blog/2024/03/19/mustafa-suleyman-deepmind-and-inflection-co-founder-joins-microsoft-to-lead-copilot/",
        },
        {
          name: "Stability AI",
          status: "pivoted",
          note: "在领导层和资本结构调整后继续聚焦开放生成媒体模型。",
          url: "https://stability.ai/news/stability-ai-secures-significant-new-investment",
        },
      ],
    },
    {
      slug: "agents-and-runtime",
      label: "Agent 从演示走向运行时",
      period: "2025 H1",
      summary:
        "DeepSeek-R1 重估效率边界，Operator、Deep Research、Claude Code 与 Agents SDK 将模型推进浏览器、代码和长任务。",
      projects: [
        {
          name: "Adept",
          status: "pivoted",
          note: "部分团队加入 Amazon 后，公司转向更聚焦的 Agent 产品与企业路线。",
          url: "https://adept.ai/blog/adept-update/",
        },
        {
          name: "Humane Ai Pin",
          status: "sunset",
          note: "消费者设备服务停止，说明新硬件入口必须同时解决产品价值与持续运营。",
          url: "https://support.humane.com/hc/en-us/articles/34243204841997-Ai-Pin-Consumers-FAQ",
        },
      ],
    },
    {
      slug: "product-and-protocol-convergence",
      label: "协议、产品与工作流合流",
      period: "2025 H2",
      summary:
        "MCP、A2A、Agent 产品与模型原生工具共同形成连接和执行层，竞争从功能演示转向真实工作流所有权。",
      projects: [
        {
          name: "MCP",
          status: "active",
          note: "从单一厂商协议扩展为跨模型、工具和平台的连接生态。",
          url: "https://modelcontextprotocol.io/",
        },
        {
          name: "Codex",
          status: "active",
          note: "编码能力从补全演化为云端与本地协同的 Agent 工作流。",
          url: "https://openai.com/codex/",
        },
      ],
    },
    {
      slug: "real-work-and-industry-concentration",
      label: "真实工作与产业再集中",
      period: "2026 H1—今天",
      summary:
        "旗舰模型围绕复杂工作、科学与长任务继续升级，收入、融资、算力和分发向头部集中，应用层开始按留存和结果重新分化。",
      projects: [
        {
          name: "Claude Code",
          status: "active",
          note: "编码 Agent 向团队协作、长任务、SDK 与企业治理扩张。",
          url: "https://www.anthropic.com/claude-code",
        },
        {
          name: "DeepSeek",
          status: "active",
          note: "开放推理与工程效率持续影响全球模型成本和部署讨论。",
          url: "https://api-docs.deepseek.com/news/",
        },
      ],
    },
  ],
  tracks: [
    {
      slug: "tech-evolution",
      thesis:
        "模型能力的主轴已从单纯扩大预训练，转向推理时计算、原生多模态、数据效率和可验证研究。",
      now: "旗舰模型正以可分配推理预算、多模态输入和科学评测扩展能力边界。",
      next: "下一阶段应关注能力增量能否跨基准复现，以及训练数据、评测污染、可靠性与成本是否透明。",
      stages: [
        {
          start: "2022-08-01",
          end: "2022-12-31",
          period: "2022 H2",
          label: "生成能力产品化",
          summary: "扩散模型和对话模型把生成能力从研究展示变成公众可直接使用的产品。",
          interpretation: "技术竞争第一次同时受到交互体验、反馈数据和开放生态扩散速度影响。",
          chinaPosition:
            "国内团队快速进入对话、图像生成与应用验证，但尚未形成可比的开放基础模型矩阵。",
          nextSignal: "能力能否从流畅生成跨越到复杂推理、工具使用和稳定专业任务。",
        },
        {
          start: "2023-01-01",
          end: "2023-06-30",
          period: "2023 H1",
          label: "能力平台化",
          summary: "GPT-4 抬高复杂任务上限，API、插件和 Copilot 把模型能力接入软件。",
          interpretation: "评测分数开始转化为开发接口和组织工作流，模型平台成为独立技术层。",
          chinaPosition: "中文模型密集发布，竞争重点从参数披露转向中文能力、合规和本地交付。",
          nextSignal: "开放权重与多区域模型能否缩小对少数闭源 API 的依赖。",
        },
        {
          start: "2023-07-01",
          end: "2023-12-31",
          period: "2023 H2",
          label: "开放模型成形",
          summary: "Llama 2、Qwen、Mistral 与 Gemini 形成开放权重、多尺寸和原生多模态路线。",
          interpretation:
            "能力不再只由单一旗舰定义，许可、部署控制和衍生生态成为技术选择的一部分。",
          chinaPosition:
            "Qwen 建立中文开放模型起点，中国团队开始通过开源和云服务同时参与全球生态。",
          nextSignal: "开放模型能否在推理、长上下文和多模态上持续接近闭源前沿。",
        },
        {
          start: "2024-01-01",
          end: "2024-06-30",
          period: "2024 H1",
          label: "原生多模态",
          summary: "语音、图像、视频与长上下文被纳入统一模型，交互从文本框扩展到实时环境。",
          interpretation:
            "模型结构、训练数据和端到端延迟开始共同决定可用能力，而非只比较文本榜单。",
          chinaPosition: "国内模型在长文本、视频生成和多尺寸部署形成差异化，但独立评测仍不足。",
          nextSignal: "多模态增量能否稳定转化为可重复任务完成，而不是发布演示。",
        },
        {
          start: "2024-07-01",
          end: "2024-12-31",
          period: "2024 H2",
          label: "推理时计算",
          summary: "o1 把推理预算变成新的 Scaling 轴，Llama 3.1 和 Qwen2.5 同时扩大开放模型边界。",
          interpretation: "能力、延迟和成本不再是固定点，系统需要按任务动态分配计算。",
          chinaPosition:
            "Qwen 与 DeepSeek 以开放模型、训练效率和工程透明度形成不同于封闭平台的路径。",
          nextSignal: "强化学习和长链推理能否在外部评测与真实任务中复现，并控制泄漏与过度思考。",
        },
        {
          start: "2025-01-01",
          end: "2025-06-30",
          period: "2025 H1",
          label: "效率与工具融合",
          summary:
            "DeepSeek-R1、Gemini 2.5、Qwen3 与 o3/o4-mini 把推理、工具和成本放进同一能力曲线。",
          interpretation: "模型价值从静态回答转向在预算约束下调用工具并完成可验证步骤。",
          chinaPosition: "开放推理和低成本训练成为中国路线的全球影响力来源。",
          nextSignal: "工具增强能力是否能减少重试、人工接管和端到端总成本。",
        },
        {
          start: "2025-07-01",
          end: "2025-12-31",
          period: "2025 H2",
          label: "统一能力路由",
          summary: "旗舰产品开始在速度、推理深度、工具和模态之间自动路由。",
          interpretation: "用户购买的不再是单个模型，而是选择模型、记忆、工具与安全策略的系统。",
          chinaPosition: "Kimi K2、MiniMax M1 等开放路线继续扩大长上下文和 Agent 能力供给。",
          nextSignal: "自动路由能否在透明成本下保持一致行为，并允许企业审计和锁定策略。",
        },
        {
          start: "2026-01-01",
          end: "9999-12-31",
          period: "2026—今天",
          label: "可验证真实能力",
          summary: "能力评价转向长任务、科学、具身、多模态和部署环境中的可复现表现。",
          interpretation:
            "前沿差距越来越取决于系统可靠性、持续数据反馈和评测设计，模型规模只是其中一个因素。",
          chinaPosition:
            "不同团队在开放推理、端侧、视频和具身模型形成优势，仍需更多跨环境可比证据。",
          nextSignal: "关注独立复现、生产失败分布、长期记忆污染和单位有效任务成本。",
        },
      ],
      lenses: [
        {
          role: "ceo",
          question: "能力进步会改变哪个经营控制点？",
          answer:
            "控制点正从采购某个模型，迁移到掌握任务数据、评测集、工具权限和持续反馈。模型会快速替换，组织自己的验收标准和工作流上下文更难复制。",
          implications: [
            "统一模型采购应改成按任务分层路由。",
            "高风险流程必须保留可回放证据与人工接管。",
          ],
          actions: [
            "选择三个高价值任务，建立成功率、重试、人工分钟和单位结果成本基线。",
            "把内部评测集、权限策略和失败分类设为平台资产。",
          ],
          watch: [
            "跨版本真实任务胜率是否提升，而非只看厂商榜单。",
            "模型路由是否制造不可解释的成本和行为漂移。",
          ],
          evidenceSlugs: [
            "openai-o1-test-time-reasoning",
            "deepseek-r1-open-reasoning",
            "gpt-5-5-real-work",
          ],
        },
        {
          role: "investor",
          question: "技术价值会沉淀在哪一层？",
          answer:
            "基础模型溢价仍存在，但可持续价值更可能沉淀在独有数据、可靠执行、推理基础设施和能证明结果改善的垂直系统。单纯包装最新模型的窗口持续缩短。",
          implications: [
            "模型领先期缩短会压缩纯 API 转售毛利。",
            "评测、推理优化和持续数据反馈成为新的尽调重点。",
          ],
          actions: [
            "把收入增长拆成模型红利、工作流锁定和数据网络效应。",
            "要求公司展示跨模型替换后的留存与毛利敏感性。",
          ],
          watch: [
            "开放模型与闭源模型在真实任务上的价差。",
            "能力提升是否带来更高使用频次和更低服务成本。",
          ],
          evidenceSlugs: [
            "llama-3-1-open-frontier-model",
            "deepseek-v3-efficient-frontier",
            "gemma-4-open-model-efficiency",
          ],
        },
        {
          role: "cto",
          question: "能力与工程边界如何变化？",
          answer:
            "工程边界从单次 prompt 扩展到模型路由、上下文压缩、工具调用、状态恢复、评测和策略治理。可靠性是系统属性，不能由更强模型单独解决。",
          implications: [
            "同一业务需要快速模型与深度推理模型协作。",
            "长上下文不能替代检索、记忆清理和最小权限。",
          ],
          actions: ["建立版本化评测集和回归检查。", "记录每次工具调用、权限决策、重试和人工接管。"],
          watch: [
            "长任务中的错误累积和状态污染。",
            "推理预算上升后延迟、吞吐和失败恢复的交换关系。",
          ],
          evidenceSlugs: [
            "openai-o3-o4-mini-tools",
            "gpt-5-unified-routing",
            "deployment-simulation-model-behavior",
          ],
        },
        {
          role: "product",
          question: "下一项产品验证应该是什么？",
          answer:
            "验证重点应从用户是否喜欢回答，转向用户是否愿意把完整任务委派给系统，以及系统失败时能否被理解、修正和继续执行。",
          implications: [
            "展示模型能力不等于形成可重复使用习惯。",
            "信任来自可预览、可撤销和可验证的任务过程。",
          ],
          actions: [
            "把一个完整任务拆成可观测的计划、执行和验收节点。",
            "为高风险动作提供预览、确认、撤销和证据回链。",
          ],
          watch: ["7/30 日任务复用率与委派深度。", "用户修正后，同类错误是否持续减少。"],
          evidenceSlugs: [
            "claude-computer-use",
            "gemini-3-5-frontier-action",
            "blind-spots-bench-vision-language",
          ],
        },
      ],
    },
    {
      slug: "agi-progress",
      thesis:
        "Agent 的关键变化是模型开始连接工具、维护任务状态，并承担跨软件的完整工作。聊天体验只是外在表现。",
      now: "编码、研究、浏览器操作和企业流程已经出现可重复的有限自治，软件入口正在从功能菜单转向任务委派。",
      next: "需要关注端到端完成率、记忆、权限、错误恢复、人工接管，以及 Agent 是否已经改变软件的交付和收费方式。",
      stages: [
        {
          start: "2022-11-01",
          end: "2023-03-31",
          period: "2022 H2—2023 Q1",
          label: "对话委派",
          summary: "用户开始用自然语言委派信息整理、写作和代码建议。",
          interpretation: "Agent 的最初形态是可连续对话的助手，仍缺少稳定工具、状态和执行权限。",
          chinaPosition: "国内产品迅速验证对话入口，但主要能力仍依赖模型问答和人工复制结果。",
          nextSignal: "模型能否安全连接外部工具并把建议变成可执行步骤。",
        },
        {
          start: "2023-04-01",
          end: "2023-12-31",
          period: "2023 Q2—Q4",
          label: "工具与 Copilot",
          summary: "插件、Assistants API 和 Copilot 把模型接入搜索、代码、文件和组织数据。",
          interpretation: "Agent 从生成文本转向调用受控工具，但编排仍由开发者预设。",
          chinaPosition: "国内云与应用团队快速接入工具链，开放协议与跨产品执行仍不成熟。",
          nextSignal: "系统是否能维护更长任务状态并处理工具失败。",
        },
        {
          start: "2024-01-01",
          end: "2024-09-30",
          period: "2024 Q1—Q3",
          label: "推理与状态",
          summary: "长上下文和推理时计算增强计划能力，Agent 开始承担更长的知识工作。",
          interpretation: "任务长度提升后，记忆、验证和成本成为与模型能力同等重要的约束。",
          chinaPosition: "长上下文和低成本模型扩大本地 Agent 试验，但真实完成率公开证据较少。",
          nextSignal: "复杂计划能否跨软件执行，并在中途错误后恢复。",
        },
        {
          start: "2024-10-01",
          end: "2025-03-31",
          period: "2024 Q4—2025 Q1",
          label: "通用界面行动",
          summary: "Computer Use、Operator 和 Deep Research 让模型操作浏览器、桌面与长检索链。",
          interpretation: "无需专用 API 的行动扩大覆盖面，也显著放大提示注入、误操作和权限风险。",
          chinaPosition: "开源推理缩小规划能力差距，通用浏览器和桌面 Agent 仍在验证可靠性。",
          nextSignal: "端到端完成率、人工接管率和安全隔离能否达到生产水位。",
        },
        {
          start: "2025-04-01",
          end: "2025-06-30",
          period: "2025 Q2",
          label: "编码 Agent",
          summary: "Codex、Claude Code 和长任务模型开始连续完成仓库理解、执行和结果验证。",
          interpretation: "编码成为首个能用测试与 diff 验收结果的高价值 Agent 市场。",
          chinaPosition: "开放模型和本地工具链提供成本优势，但团队级采用、生态和分发证据仍不足。",
          nextSignal: "Agent 是否能稳定完成跨文件任务并减少 review 与返工总时间。",
        },
        {
          start: "2025-07-01",
          end: "2025-12-31",
          period: "2025 H2",
          label: "协议与多 Agent",
          summary: "MCP、A2A 和 Agents SDK 把工具、上下文和 Agent 间协作抽象成运行时。",
          interpretation: "竞争从单一助手转向谁能控制连接、权限、可观测性和任务路由。",
          chinaPosition: "中国模型与应用进入协议兼容阶段，全球生态贡献和企业采用仍需持续观察。",
          nextSignal: "跨厂商互操作是否真实降低集成成本，而非增加协议层复杂度。",
        },
        {
          start: "2026-01-01",
          end: "9999-12-31",
          period: "2026—今天",
          label: "真实工作与长任务",
          summary: "Agent 评价转向数小时任务、科学、具身和组织内持续运行。",
          interpretation: "模型峰值能力之外，恢复、记忆治理、责任边界和结果验收决定可部署性。",
          chinaPosition: "需观察中国 Agent 在高价值任务、企业部署和全球分发中的真实份额。",
          nextSignal: "长期运行是否降低单位结果成本，并在异常时留下足够审计证据。",
        },
      ],
      lenses: [
        {
          role: "ceo",
          question: "Agent 会重写哪类组织边界？",
          answer:
            "可数字验收、需要跨系统搬运信息且等待时间长的流程会最先变化。组织需要明确新的责任、审批和异常升级方式，Bot 数量本身无法形成优势。",
          implications: ["部分软件席位会变成任务预算。", "管理跨度可能扩大，但失败责任会更集中。"],
          actions: [
            "选一个跨部门流程建立人工与 Agent 对照组。",
            "明确哪些动作可自动执行、哪些必须审批。",
          ],
          watch: [
            "端到端周期、人工接管和返工是否同时下降。",
            "供应商是否提供可导出的任务记录和权限审计。",
          ],
          evidenceSlugs: ["claude-computer-use", "openai-codex-cloud-agent", "gpt-5-5-real-work"],
        },
        {
          role: "investor",
          question: "Agent 价值向哪一层迁移？",
          answer:
            "价值从聊天入口迁向拥有工作流、权限和结果数据的运行时。能证明任务成功率和留存的垂直系统，比通用 Agent 壳层更可能保有定价权。",
          implications: [
            "Agent 数量与消息量不是收入质量。",
            "分发入口和系统记录权比单次能力领先更持久。",
          ],
          actions: [
            "尽调真实付费任务、失败成本和续费驱动。",
            "测试更换底层模型后产品差异是否仍存在。",
          ],
          watch: ["按结果收费是否提升毛利而非转嫁不可控成本。", "平台厂商是否向同一工作流下沉。"],
          evidenceSlugs: [
            "model-context-protocol",
            "codex-general-availability",
            "chatgpt-agent-research-to-action",
          ],
        },
        {
          role: "cto",
          question: "Agent 运行时的硬边界是什么？",
          answer:
            "硬边界是权限、状态一致性、幂等、回滚、可观测性和外部内容注入。模型更强不会自动解决分布式系统和安全工程问题。",
          implications: [
            "工具契约必须可验证且最小权限。",
            "长任务需要 checkpoint、预算和人工中断。",
          ],
          actions: [
            "为工具调用定义 schema、超时、重试和补偿。",
            "按失败类别记录环境、模型、步骤和恢复结果。",
          ],
          watch: ["长任务中的重复副作用和隐性权限扩张。", "MCP/A2A 兼容是否经过真实互操作测试。"],
          evidenceSlugs: [
            "model-context-protocol",
            "google-a2a-agent-protocol",
            "openai-responses-agents-sdk",
          ],
        },
        {
          role: "product",
          question: "怎样证明 Agent 不是一次性演示？",
          answer:
            "证明标准是同一用户反复委派更深任务，并愿意让系统在明确边界内采取行动。需要同时衡量完成率、信任、修正成本和结果价值。",
          implications: ["成功演示可能掩盖长尾失败。", "用户需要理解系统当前状态和下一动作。"],
          actions: [
            "把任务进度、证据、等待和失败原因做成产品界面。",
            "为每类高风险动作设计确认与撤销。",
          ],
          watch: ["30 日任务复用率和平均委派步骤数。", "用户取消、接管和回退发生在哪个节点。"],
          evidenceSlugs: [
            "openai-operator-browser-agent",
            "openai-deep-research",
            "claude-opus-4-7-agent-work",
          ],
        },
      ],
    },
    {
      slug: "commercialization",
      thesis: "商业化从 API token 消费，转向订阅、席位、任务结果和嵌入核心工作流。",
      now: "编码和知识工作率先形成高价值付费，模型厂商直接向应用和运行时扩张。",
      next: "关键指标将从调用量转为完成任务、留存、毛利和组织产能。",
      stages: [
        {
          start: "2022-08-01",
          end: "2022-12-31",
          period: "2022 H2",
          label: "大众需求验证",
          summary: "ChatGPT 和生成图像证明用户会主动寻找生成式 AI 产品。",
          interpretation: "市场从技术可行性转向留存、分发和使用成本问题。",
          chinaPosition: "消费应用跟进迅速，但商业模式主要依赖订阅探索和流量分发。",
          nextSignal: "高频使用能否形成付费，以及 API 是否打开应用创业。",
        },
        {
          start: "2023-01-01",
          end: "2023-06-30",
          period: "2023 H1",
          label: "API 与 Copilot",
          summary: "模型 API 降低集成门槛，Microsoft 365 Copilot 把 AI 放进组织软件。",
          interpretation: "商业价值从独立聊天产品扩展到已有分发和数据权限的应用。",
          chinaPosition: "国内大厂以云和办公入口推进，创业公司集中验证内容与效率工具。",
          nextSignal: "企业是否为席位付费，以及应用能否建立模型之外的壁垒。",
        },
        {
          start: "2023-07-01",
          end: "2024-06-30",
          period: "2023 H2—2024 H1",
          label: "多模型供给",
          summary: "开放模型和多家 API 供应商降低单一模型依赖，产品竞争转向数据与工作流。",
          interpretation: "API 包装的稀缺性下降，采购开始比较成本、隐私、延迟和部署方式。",
          chinaPosition: "Qwen 等开放模型扩大私有化供给，价格竞争加速市场教育。",
          nextSignal: "产品是否能在更换模型后保持留存、质量和毛利。",
        },
        {
          start: "2024-07-01",
          end: "2024-12-31",
          period: "2024 H2",
          label: "企业与治理门槛",
          summary: "推理能力、计算机使用和 AI Act 同时提高可做任务与交付责任。",
          interpretation: "企业采购同时评估模型能力、治理、权限、审计和长期服务。",
          chinaPosition: "消费入口扩张快，企业付费、合规交付和全球服务能力仍需更多证据。",
          nextSignal: "部署能否从试点进入重复采购，并形成可审计 ROI。",
        },
        {
          start: "2025-01-01",
          end: "2025-12-31",
          period: "2025",
          label: "Agent 产品",
          summary: "研究、浏览、编码和开发平台出现可按任务验收的 Agent 产品。",
          interpretation: "定价从 token 和功能席位向任务额度、团队计划和结果价值移动。",
          chinaPosition: "模型价格竞争激烈，完整应用流程和全球分发能力仍在形成。",
          nextSignal: "Agent 使用是否提升留存、扩张收入和组织级标准化。",
        },
        {
          start: "2026-01-01",
          end: "9999-12-31",
          period: "2026—今天",
          label: "工作流所有权",
          summary: "模型厂商、云、办公软件和垂直应用争夺完整任务入口与组织预算。",
          interpretation: "价值取决于谁控制上下文、权限、记录和结果反馈，而非谁先发布功能。",
          chinaPosition: "云与大厂分发占优，创业公司需要以行业数据、交付和跨境能力建立壁垒。",
          nextSignal: "比较任务留存、单位经济、净收入留存和供应商替换成本。",
        },
      ],
      lenses: [
        {
          role: "ceo",
          question: "商业控制点正在迁移到哪里？",
          answer:
            "控制点从软件功能和模型 API 迁移到拥有用户任务入口、组织上下文、审批权和结果记录的一层。企业需要防止关键流程被单一模型供应商锁定。",
          implications: [
            "采购应同时保留模型可替换性与数据可携带性。",
            "AI 预算会与软件、外包和人力预算重新分配。",
          ],
          actions: [
            "建立按任务而非按席位的 ROI 台账。",
            "在合同中明确数据、日志、模型切换和退出边界。",
          ],
          watch: ["试点转生产的周期与扩张率。", "单位任务毛利是否随使用增加而改善。"],
          evidenceSlugs: [
            "microsoft-365-copilot-introduced",
            "codex-general-availability",
            "google-io-2026-ai-platform-bundle",
          ],
        },
        {
          role: "investor",
          question: "收入质量怎样与 AI 热度分开？",
          answer:
            "评估重点应放在付费任务是否高频、是否嵌入核心流程、模型成本能否被规模摊薄，以及续费是否来自真实结果。ARR 标签和补贴都可能掩盖实际采用情况。",
          implications: [
            "席位增长可能掩盖低激活和高推理成本。",
            "服务收入过高可能说明产品尚未标准化。",
          ],
          actions: [
            "重建 cohort、毛利和使用深度三张表。",
            "压力测试模型降价、平台捆绑和客户自建。",
          ],
          watch: ["净收入留存与活跃任务增长是否同向。", "头部客户集中和底层模型依赖。"],
          evidenceSlugs: [
            "chatgpt-whisper-apis",
            "anthropic-series-h-scale",
            "openai-acquires-ona",
          ],
        },
        {
          role: "cto",
          question: "商业化对技术架构提出什么要求？",
          answer:
            "多模型路由、成本归因、租户隔离、审计和可降级能力会直接决定毛利与交付速度。架构必须允许能力升级而不重写业务流程。",
          implications: ["每个任务需要成本、质量和延迟追踪。", "企业功能不能作为后期补丁。"],
          actions: [
            "把模型、工具和业务策略解耦为版本化契约。",
            "建立按客户和任务的成本与失败观测。",
          ],
          watch: ["供应商变更导致的行为回归。", "高峰时延迟、降级与 SLA 违约。"],
          evidenceSlugs: [
            "openai-responses-agents-sdk",
            "model-context-protocol",
            "claude-fable-5-microsoft-foundry",
          ],
        },
        {
          role: "product",
          question: "怎样从功能使用走向可持续付费？",
          answer:
            "产品必须让用户更快得到可验收结果，并在团队中积累模板、权限、历史和协作价值。一次生成质量不足以形成续费。",
          implications: ["使用频次需要与任务价值一起衡量。", "团队协作和治理会成为扩张杠杆。"],
          actions: [
            "定义从首次成功到团队扩张的关键行为链。",
            "展示结果证据、节省时间和可复用资产。",
          ],
          watch: ["7/30/90 日留存与任务深度。", "用户是否把输出带回原系统继续工作。"],
          evidenceSlugs: [
            "chatgpt-research-preview",
            "openai-codex-cloud-agent",
            "ai-co-clinician-healthcare-model",
          ],
        },
      ],
    },
    {
      slug: "investing",
      thesis: "资本主线从模型融资，扩展到芯片、数据中心、电力、云承诺和高价值应用。",
      now: "头部模型公司正在形成云平台级资本密度，基础设施与收入规模同步放大。",
      next: "需要同时跟踪训练/推理 CapEx、收入质量、毛利和平台锁定。",
      stages: [
        {
          start: "2022-08-01",
          end: "2023-06-30",
          period: "2022 H2—2023 H1",
          label: "平台联盟",
          summary: "模型公司与云平台形成算力、资本和分发绑定。",
          interpretation: "前沿模型的资本需求使云承诺和战略投资成为竞争结构，而非普通融资。",
          chinaPosition: "国内由云厂商与大模型团队共同投入，公开可比融资和算力数据有限。",
          nextSignal: "资本是否转化为模型领先、企业分发和可持续收入。",
        },
        {
          start: "2023-07-01",
          end: "2024-06-30",
          period: "2023 H2—2024 H1",
          label: "模型融资与应用整合",
          summary: "基础模型融资放大，应用层同时出现收购、团队迁移和路线转向。",
          interpretation: "资本开始区分基础设施密集型平台与缺少工作流壁垒的应用。",
          chinaPosition: "模型创业密集融资，但价格竞争与备案交付提高现金消耗。",
          nextSignal: "应用公司能否在平台下沉前证明留存、分发和数据壁垒。",
        },
        {
          start: "2024-07-01",
          end: "2025-06-30",
          period: "2024 H2—2025 H1",
          label: "训练与推理建设",
          summary: "Blackwell、AI Factory、数据中心和电力承诺成为资本主线。",
          interpretation: "投资对象从模型公司扩展到芯片、网络、云、电力和施工周期。",
          chinaPosition: "算力限制推动系统效率、国产适配和开放模型路线。",
          nextSignal: "CapEx 是否带来可售算力、利用率和推理收入，而非闲置承诺。",
        },
        {
          start: "2025-07-01",
          end: "2025-12-31",
          period: "2025 H2",
          label: "资本再集中",
          summary: "头部模型、云和基础设施平台获得更大融资与长期合作承诺。",
          interpretation: "规模优势扩大，但估值开始依赖收入增速、毛利和持续融资能力。",
          chinaPosition: "DeepSeek 等效率路线证明资本规模不是唯一变量，融资与全球分发差距仍在。",
          nextSignal: "观察融资条款、云依赖、客户集中和单位推理毛利。",
        },
        {
          start: "2026-01-01",
          end: "9999-12-31",
          period: "2026—今天",
          label: "收入、退出与纪律",
          summary: "行业同时出现大额融资、并购、人才交易与对真实收入质量的追问。",
          interpretation: "资本叙事从拥有模型转向能否控制工作流、基础设施现金流和可持续退出路径。",
          chinaPosition: "开放生态与工程成本仍有优势，但上市、并购和跨境资本路径更受约束。",
          nextSignal: "把增长、毛利、CapEx、债务、客户集中和退出可行性放进同一模型。",
        },
      ],
      lenses: [
        {
          role: "ceo",
          question: "资本集中会怎样影响经营选择？",
          answer:
            "企业应假设模型与算力供应将长期集中，同时保持关键任务的供应商替换与成本可见性。过早押注单一平台会把采购优惠变成未来迁移成本。",
          implications: ["长期云承诺需要与真实需求爬坡匹配。", "小团队应避开纯资本规模竞争。"],
          actions: [
            "对关键供应商做价格、容量和退出压力测试。",
            "把自建、托管和 API 的总拥有成本放在同一模型。",
          ],
          watch: ["承诺用量与实际利用率偏差。", "融资或并购是否改变产品路线和服务连续性。"],
          evidenceSlugs: [
            "nvidia-blackwell-ultra-reasoning-factory",
            "anthropic-series-h-scale",
            "openai-acquires-ona",
          ],
        },
        {
          role: "investor",
          question: "怎样识别资本支出背后的价值？",
          answer:
            "必须把算力规模拆成可用容量、利用率、单位收入、合同期限和融资结构。大额 CapEx 只有在需求、毛利和现金回收可验证时才是壁垒。",
          implications: ["芯片采购不等于可售推理产能。", "云关联融资可能同时带来分发与锁定。"],
          actions: ["建立 CapEx 到收入的滞后桥接表。", "分别估值模型、基础设施和应用现金流。"],
          watch: ["推理收入增速与折旧、能源成本。", "客户集中、关联交易和再融资需求。"],
          evidenceSlugs: [
            "nvidia-blackwell-ultra-reasoning-factory",
            "deepseek-v3-efficient-frontier",
            "anthropic-series-h-scale",
          ],
        },
        {
          role: "cto",
          question: "资本周期会约束哪些技术路线？",
          answer:
            "可获得芯片、网络、电力和云额度会反向决定模型规模、训练频率与推理架构。效率工程既是成本优化，也是供应安全能力。",
          implications: [
            "硬件路线需要软件栈和模型结构共同适配。",
            "推理增长会把容量规划从训练峰值转向持续负载。",
          ],
          actions: [
            "记录有效利用率、故障恢复和每任务资源消耗。",
            "验证替代硬件与模型压缩的质量边界。",
          ],
          watch: ["容量瓶颈从芯片转向网络、电力或冷却。", "新硬件交付时间与软件成熟度错配。"],
          evidenceSlugs: [
            "nvidia-blackwell-ultra-reasoning-factory",
            "decoupled-diloco-resilient-distributed-training",
            "gemma-4-open-model-efficiency",
          ],
        },
        {
          role: "product",
          question: "资本变化如何传导到产品？",
          answer:
            "融资与基础设施扩张会带来更低价格和更强能力，也可能推动供应商优先服务高价值工作流。产品需要把价格红利转成用户价值，而非无限增加生成量。",
          implications: ["降价会加速功能同质化。", "平台并购可能改变 API、配额和路线图。"],
          actions: [
            "把成本下降投入更深任务或更好验证。",
            "为供应商变更设计用户可感知的质量回归检查。",
          ],
          watch: ["模型降价是否改善留存和毛利。", "并购后产品承诺与接口稳定性。"],
          evidenceSlugs: [
            "deepseek-r1-open-reasoning",
            "openai-acquires-ona",
            "google-io-2026-ai-platform-bundle",
          ],
        },
      ],
    },
    {
      slug: "global-innovation",
      thesis:
        "全球 AI 创新由多条路线共同推动：中国的开放模型、工程效率、应用分发和本土算力，与美国的平台能力、欧洲治理和全球开源生态相互影响。",
      now: "中国团队已在开放推理、模型效率、视频生成和应用规模上形成独立影响，差异更多来自生态、算力、市场与分发路径。",
      next: "观察跨区域开发者采用、全球收入、开放生态贡献、国产算力的端到端验证和产品长期留存。",
      stages: [
        {
          start: "2022-08-01",
          end: "2022-12-31",
          period: "2022 H2",
          label: "开放生成扩散",
          summary: "Stable Diffusion 证明开放权重可以在全球开发者和创作者中快速扩散。",
          interpretation: "创新速度开始由社区改造、工具链和本地部署共同推动。",
          chinaPosition: "中国开发者快速进入开放生成生态，但基础模型贡献和许可影响仍有限。",
          nextSignal: "开放生态能否从图像扩展到通用语言模型。",
        },
        {
          start: "2023-01-01",
          end: "2023-06-30",
          period: "2023 H1",
          label: "区域模型起跑",
          summary: "全球团队围绕语言、监管和本地部署建立区域模型路线。",
          interpretation: "单一美国平台之外，数据主权、语言与产业环境开始塑造技术路线。",
          chinaPosition: "国内大模型密集发布并进入备案与产品验证。",
          nextSignal: "是否形成可下载、可评测、可持续维护的开放模型。",
        },
        {
          start: "2023-07-01",
          end: "2023-12-31",
          period: "2023 H2",
          label: "开放模型多中心",
          summary: "Llama 2、Qwen、Mistral 与 Gemini 形成美国、中国、欧洲多路线供给。",
          interpretation: "全球竞争从追随单一榜单转向许可、语言、尺寸、部署和生态的组合。",
          chinaPosition: "Qwen-7B 开放使中国模型开始直接进入全球开发者比较。",
          nextSignal: "多区域模型能否在前沿能力和生态采用上持续迭代。",
        },
        {
          start: "2024-01-01",
          end: "2024-06-30",
          period: "2024 H1",
          label: "多模态与应用分化",
          summary: "不同区域围绕长上下文、视频、端侧和行业应用形成专长。",
          interpretation: "创新不再只有一个能力轴，市场与数据条件决定路线优先级。",
          chinaPosition: "中国团队在视频生成、长文本和消费分发形成独立产品节奏。",
          nextSignal: "产品热度能否转化为全球留存、收入与开发者生态。",
        },
        {
          start: "2024-07-01",
          end: "2025-03-31",
          period: "2024 H2—2025 Q1",
          label: "开放效率转折",
          summary: "Qwen2.5、DeepSeek-V3/R1 把模型矩阵、训练效率和开放推理带入全球主线。",
          interpretation: "资本规模之外，架构、数据和工程效率成为可观察的创新变量。",
          chinaPosition: "中国模型从本地替代叙事进入影响全球成本、开源和推理路线的阶段。",
          nextSignal: "独立复现、海外开发者采用和衍生生态是否持续。",
        },
        {
          start: "2025-04-01",
          end: "2025-12-31",
          period: "2025 Q2—Q4",
          label: "Agent 与开放生态",
          summary: "Qwen3、MiniMax M1、Kimi K2 等模型转向混合推理、长上下文和 Agent。",
          interpretation: "竞争已经从模型发布扩展到工具兼容、全球分发和完整应用流程。",
          chinaPosition: "开放模型供给保持活跃，企业采用、国际服务和商业收入成为新门槛。",
          nextSignal: "观察全球 API 使用、开源贡献、企业案例和区域合规。",
        },
        {
          start: "2026-01-01",
          end: "9999-12-31",
          period: "2026—今天",
          label: "全球采用与产业落地",
          summary: "各区域围绕真实工作、具身、科学、算力和治理形成不同组合优势。",
          interpretation: "领先不应由单一榜单定义，而要比较能力、成本、生态、收入和供应链韧性。",
          chinaPosition: "竞争进入产品留存、企业采用、全球分发与国产算力协同。",
          nextSignal: "用同维度证据比较开发者份额、全球收入、生产部署和国产算力的端到端表现。",
        },
      ],
      lenses: [
        {
          role: "ceo",
          question: "全球创新版图会改变哪些区域决策？",
          answer:
            "模型选择应按语言、数据边界、供应安全、生态和任务表现组合决策，而不是默认单一全球冠军。多区域供应可以提高韧性，也会增加治理复杂度。",
          implications: [
            "中国与海外业务可能需要不同模型组合。",
            "开源模型提供控制力但增加运维责任。",
          ],
          actions: ["为关键区域建立同任务、同成本评测。", "明确跨境数据、模型许可和退出方案。"],
          watch: [
            "区域供应商的长期服务与全球节点覆盖。",
            "监管变化是否影响模型、数据或芯片可得性。",
          ],
          evidenceSlugs: [
            "qwen-2-5-open-model-matrix",
            "deepseek-r1-open-reasoning",
            "kimi-k2-agentic-open-model",
          ],
        },
        {
          role: "investor",
          question: "怎样避免把全球比较做成单一排名？",
          answer:
            "应分别比较能力、成本、开放生态、分发、收入和供应链。中国团队的效率与开放影响力可以领先，但全球企业收入和分发仍可能受限。",
          implications: ["技术领先与商业领先可能分离。", "区域政策和云生态会改变可实现市场。"],
          actions: ["建立同维度区域 scorecard。", "拆分国内收入、海外收入、开发者采用和生态贡献。"],
          watch: [
            "海外留存与付费是否同步增长，避免只看下载量。",
            "国产算力适配能否通过完整生产验证。",
          ],
          evidenceSlugs: [
            "qwen-3-hybrid-thinking",
            "minimax-m1-long-context-reasoning",
            "deepseek-v3-efficient-frontier",
          ],
        },
        {
          role: "cto",
          question: "多区域模型供给怎样进入架构？",
          answer:
            "需要标准化模型接口、评测、内容安全和数据路由，同时保留各模型在语言、工具和部署上的差异。最低公分母抽象会损失能力。",
          implications: ["多模型不是简单 endpoint 切换。", "许可、权重来源和区域部署需要可审计。"],
          actions: ["建立模型能力 manifest 与区域策略。", "对同一任务持续回归质量、成本和安全。"],
          watch: ["模型升级造成的语言与工具行为漂移。", "开源依赖、权重和训练数据许可变化。"],
          evidenceSlugs: [
            "llama-2-open-model-release",
            "qwen-7b-open-release",
            "mistral-7b-release",
          ],
        },
        {
          role: "product",
          question: "全球产品应该先验证什么？",
          answer:
            "先验证不同地区用户是否在同一核心任务上持续获得价值，再决定统一产品或区域化。翻译界面不能替代本地工作流、支付、合规和分发。",
          implications: ["模型语言能力不等于市场进入能力。", "本地生态合作可能比功能复制更重要。"],
          actions: ["按地区追踪激活、任务留存和付费原因。", "为区域差异建立产品假设而非只改文案。"],
          watch: ["海外用户是否形成自然复用和口碑。", "分发成本、支付与合规是否吞噬单位经济。"],
          evidenceSlugs: [
            "qwen-2-5-open-model-matrix",
            "kimi-k2-agentic-open-model",
            "deepmind-apac-climate-accelerator",
          ],
        },
      ],
    },
    {
      slug: "model-economics",
      thesis: "单位 token 价格仍在下降，企业评估成本时开始转向“一次任务可靠完成需要多少钱”。",
      now: "MoE、FP8、推理预算和模型路由共同决定成本曲线。",
      next: "采购需要比较成功率、重试、延迟、人工接管和总拥有成本。",
      stages: [
        {
          start: "2022-11-01",
          end: "2023-06-30",
          period: "2022 H2—2023 H1",
          label: "API 成本下降",
          summary: "对话与语音 API 标准化并快速降价，应用验证门槛下降。",
          interpretation: "模型成本首次成为可直接进入产品单位经济的变量。",
          chinaPosition: "国内团队通过云服务和价格竞争快速扩大可及性。",
          nextSignal: "开放权重是否进一步压低推理与锁定成本。",
        },
        {
          start: "2023-07-01",
          end: "2023-12-31",
          period: "2023 H2",
          label: "开放部署选择",
          summary: "Llama 2、Qwen、Mistral 提供不同尺寸和本地部署路径。",
          interpretation: "采购从 API 单价比较扩展到硬件、运维、许可和定制成本。",
          chinaPosition: "开放中文模型扩大私有化选择，真实运维成本仍缺少统一口径。",
          nextSignal: "同质量下的吞吐、显存和部署复杂度能否持续改善。",
        },
        {
          start: "2024-01-01",
          end: "2024-06-30",
          period: "2024 H1",
          label: "MoE 与推理优化",
          summary: "稀疏模型、量化和推理框架降低单位激活计算。",
          interpretation: "参数规模不再等于每次请求成本，系统软件和硬件利用率影响扩大。",
          chinaPosition: "国内价格战与工程优化同时推进，形成低价 API 供给。",
          nextSignal: "低价是否在可靠性、峰值容量和服务质量下仍成立。",
        },
        {
          start: "2024-07-01",
          end: "2024-12-31",
          period: "2024 H2",
          label: "推理预算",
          summary: "o1 让推理成本随任务难度和思考长度变化。",
          interpretation: "固定 token 单价无法解释复杂任务的真实成本与价值。",
          chinaPosition: "Qwen 与 DeepSeek 加速转向推理与效率路线。",
          nextSignal: "更多计算是否稳定提高可验证结果，还是带来过度思考和泄漏。",
        },
        {
          start: "2025-01-01",
          end: "2025-03-31",
          period: "2025 Q1",
          label: "效率冲击",
          summary: "DeepSeek-V3/R1 把训练与推理效率带入全球成本讨论。",
          interpretation: "架构、数据和工程能力可以改变对前沿模型资本门槛的估计。",
          chinaPosition: "DeepSeek 把效率、开放权重和价格变成全球竞争力。",
          nextSignal: "外部复现、真实部署成本和持续服务能力。",
        },
        {
          start: "2025-04-01",
          end: "2025-09-30",
          period: "2025 Q2—Q3",
          label: "工具与 Agent 成本",
          summary: "模型开始为每个任务调用搜索、代码、浏览器和多个子步骤。",
          interpretation: "重试、工具费用、长上下文和等待时间使单次请求成本失真。",
          chinaPosition: "低价模型有利于扩大尝试，但端到端成功率决定实际优势。",
          nextSignal: "比较一次成功任务的总调用、重试和人工接管。",
        },
        {
          start: "2025-10-01",
          end: "2026-03-31",
          period: "2025 Q4—2026 Q1",
          label: "系统级 TCO",
          summary: "自动路由、缓存、压缩和多模型组合成为成本控制核心。",
          interpretation: "采购单位从模型 token 迁移到包含平台、工程和治理的总拥有成本。",
          chinaPosition: "开放模型和本地部署提供控制力，SLA 与运维成熟度决定企业价值。",
          nextSignal: "模型切换、容量峰值和治理要求下的真实年度成本。",
        },
        {
          start: "2026-04-01",
          end: "9999-12-31",
          period: "2026 Q2—今天",
          label: "单位有效结果",
          summary: "行业开始按可靠完成的任务、节省的人工和业务结果衡量成本。",
          interpretation: "便宜但失败的调用可能比昂贵但一次完成的模型更贵。",
          chinaPosition: "需要补齐真实 ROI、SLA、全球交付和企业续费证据。",
          nextSignal: "公开成功率、失败分布、人工分钟、毛利和长期留存。",
        },
      ],
      lenses: [
        {
          role: "ceo",
          question: "应该用什么单位管理 AI 成本？",
          answer:
            "用一次被业务接受的结果作为成本单位。计算时应包含模型、工具、重试、人工复核、失败损失和治理成本，不能只看 token 或调用次数。",
          implications: ["低单价可能被低成功率抵消。", "不同任务应配置不同质量与预算上限。"],
          actions: [
            "为核心任务建立 cost-per-accepted-outcome。",
            "把人工接管和失败损失纳入采购复盘。",
          ],
          watch: ["规模增加后单位结果成本是否下降。", "供应商降价是否伴随容量或质量变化。"],
          evidenceSlugs: [
            "chatgpt-whisper-apis",
            "deepseek-r1-open-reasoning",
            "gpt-5-unified-routing",
          ],
        },
        {
          role: "investor",
          question: "成本下降会把利润留给谁？",
          answer:
            "底层降价会扩大需求，但利润更可能留在拥有分发、专有工作流、数据和基础设施利用率的一层。纯模型转售会持续承压。",
          implications: [
            "推理毛利需要结合折旧和容量利用率。",
            "应用毛利要剔除模型补贴和人工服务。",
          ],
          actions: ["按任务拆解收入、推理成本和服务成本。", "压力测试价格每年下降时的竞争位置。"],
          watch: ["降价是否带来需求弹性和留存。", "自建与 API 的临界规模是否真实到达。"],
          evidenceSlugs: [
            "deepseek-v3-efficient-frontier",
            "nvidia-blackwell-ultra-reasoning-factory",
            "gemma-4-open-model-efficiency",
          ],
        },
        {
          role: "cto",
          question: "怎样工程化控制单位任务成本？",
          answer:
            "通过模型路由、缓存、上下文压缩、批处理、工具预算和失败早停共同优化；任何单点优化都必须在质量回归下验证。",
          implications: ["长上下文可能增加无效计算。", "重试策略既影响可靠性也影响尾部成本。"],
          actions: [
            "记录每任务 token、工具、延迟、重试和结果。",
            "为不同风险等级设模型与预算策略。",
          ],
          watch: ["缓存命中、路由漂移和峰值容量。", "量化或替代模型导致的长尾质量损失。"],
          evidenceSlugs: [
            "openai-o1-test-time-reasoning",
            "decoupled-diloco-resilient-distributed-training",
            "gemma-4-12b-unified-multimodal",
          ],
        },
        {
          role: "product",
          question: "如何把成本约束转成更好的产品？",
          answer:
            "让用户感知任务预算、等待和结果置信度，并把高成本计算留给高价值步骤。盲目追求即时或无限生成会伤害毛利和信任。",
          implications: ["速度、质量和价格需要按场景表达。", "用户应能选择快速草稿或深度执行。"],
          actions: ["设计明确的任务模式与预算提示。", "用结果接受率而非生成次数优化体验。"],
          watch: ["高成本模式的付费意愿和复用率。", "等待时间是否换来可感知的结果提升。"],
          evidenceSlugs: [
            "openai-o1-test-time-reasoning",
            "gpt-5-unified-routing",
            "gemini-2-5-thinking-model",
          ],
        },
      ],
    },
  ],
} as const;
