export const productVersion = "0.11.1";

export const capabilities = [
  {
    slug: "source-catalog",
    name: "重点来源目录",
    domain: "sensing",
    status: "operational",
    maturity: 68,
    release: "0.2.0",
    evidence: "414 sources classified by region, role, acquisition and maintenance state",
  },
  {
    slug: "upstream-discovery",
    name: "聚合上游发现",
    domain: "sensing",
    status: "experimental",
    maturity: 56,
    release: "0.3.0",
    evidence: "aggregator observations are stored as discoveries and matched to direct publishers",
  },
  {
    slug: "continuous-data-refresh",
    name: "持续数据刷新",
    domain: "sensing",
    status: "operational",
    maturity: 72,
    release: "0.7.0",
    evidence:
      "daily data refresh and Pages deployment, serialized monotonic snapshot writes, isolated optional AI stages and parse-validated quality artifacts",
  },
  {
    slug: "ai-event-convergence",
    name: "AI 事件整理与决策周报",
    domain: "intelligence",
    status: "experimental",
    maturity: 42,
    release: "unreleased",
    evidence:
      "DeepSeek V4 Flash produces schema-validated Event drafts and weekly decision cards behind evidence, readiness and public-DTO gates",
  },
  {
    slug: "public-source-observations",
    name: "公开来源观察流",
    domain: "sensing",
    status: "operational",
    maturity: 66,
    release: "0.9.0",
    evidence:
      "4,940 allowlisted source observations are searchable by title, description, attribution, date, category, tags and canonical link without exposing raw payloads",
  },
  {
    slug: "dynamic-home-discovery",
    name: "动态首页发现",
    domain: "product",
    status: "operational",
    maturity: 72,
    release: "0.9.0",
    evidence:
      "multiple evidence-backed trend candidates, randomized recent Events and six visible trend blocks with internal Event carousels are consumed by the public homepage",
  },
  {
    slug: "industry-history-baseline",
    name: "2022—今天行业基线",
    domain: "understanding",
    status: "operational",
    maturity: 72,
    release: "0.8.0",
    evidence:
      "source-backed milestones from Stable Diffusion and ChatGPT in 2022 through the current public snapshot",
  },
  {
    slug: "track-synthesis",
    name: "主线阶段整理",
    domain: "intelligence",
    status: "operational",
    maturity: 66,
    release: "0.4.0",
    evidence: "five eras and six executive track narratives with China-position comparisons",
  },
  {
    slug: "major-stage-promotion",
    name: "重大里程碑阶段晋级",
    domain: "intelligence",
    status: "experimental",
    maturity: 46,
    release: "unreleased",
    evidence:
      "deterministic rarity gates, DeepSeek V4 Pro high-effort review, evidence allowlists, dedicated GitHub Issues and versioned narrative promotion records",
  },
  {
    slug: "primary-source-gate",
    name: "一手事实检查",
    domain: "governance",
    status: "operational",
    maturity: 65,
    release: "0.3.0",
    evidence: "aggregator-role collectors cannot write factual signals or enter event clustering",
  },
  {
    slug: "source-lifecycle",
    name: "信源生命周期",
    domain: "sensing",
    status: "operational",
    maturity: 62,
    release: "0.2.0",
    evidence: "draft/shadow/active/degraded/quarantined/retired state machine",
  },
  {
    slug: "resilient-fetch",
    name: "弹性拉取",
    domain: "sensing",
    status: "operational",
    maturity: 72,
    release: "0.2.0",
    evidence:
      "direct-first fetch with bounded fallback proxy, timeout, retry classification, backoff, cache, per-host rate limit and redirect guard",
  },
  {
    slug: "source-observability",
    name: "来源可观测性",
    domain: "sensing",
    status: "operational",
    maturity: 70,
    release: "0.2.0",
    evidence:
      "append-only source checks plus separate production active coverage and latest-audit healthy-rate monitoring",
  },
  {
    slug: "source-audit",
    name: "逐源恢复审计",
    domain: "sensing",
    status: "operational",
    maturity: 68,
    release: "0.5.0",
    evidence:
      "414/414 live rows checked; 266 healthy, 398 accessible and 276 produced parseable content",
  },
  {
    slug: "shadow-observation",
    name: "隔离观察数据池",
    domain: "sensing",
    status: "operational",
    maturity: 58,
    release: "0.5.0",
    evidence:
      "188 qualified sources supply an isolated observation pool; the repository snapshot retains 4,940 Signals without bypassing production promotion",
  },
  {
    slug: "source-contract",
    name: "适配器契约验证",
    domain: "sensing",
    status: "experimental",
    maturity: 36,
    release: "0.1.0",
    evidence: "shared SourceAdapter and partial parser fixtures",
  },
  {
    slug: "incremental-sync",
    name: "增量同步",
    domain: "sensing",
    status: "experimental",
    maturity: 52,
    release: "0.2.0",
    evidence:
      "ETag/Last-Modified state, monotonic snapshot merge, full source-run history and policy-aware all-source synchronization; general cursor pagination pending",
  },
  {
    slug: "coverage-map",
    name: "国内外覆盖地图",
    domain: "sensing",
    status: "experimental",
    maturity: 58,
    release: "0.7.0",
    evidence:
      "region/category coverage plus a 12-person AI expert identity matrix with automatic feeds and restricted social profiles",
  },
  {
    slug: "normalize",
    name: "信号规范化",
    domain: "understanding",
    status: "operational",
    maturity: 58,
    release: "0.1.0",
    evidence: "shared CollectedSignal model and sanitization",
  },
  {
    slug: "dedupe",
    name: "URL 与内容去重",
    domain: "understanding",
    status: "operational",
    maturity: 58,
    release: "0.1.0",
    evidence:
      "canonical URL/content hash plus per-source observations with first/last seen time and idempotent snapshot recovery",
  },
  {
    slug: "event-clustering",
    name: "事件聚类",
    domain: "understanding",
    status: "experimental",
    maturity: 48,
    release: "0.1.0",
    evidence:
      "eventability gate, model family/facet fingerprints and reviewable merge candidates; multilingual semantic clustering pending",
  },
  {
    slug: "reversible-signal-triage",
    name: "可逆信号分诊",
    domain: "understanding",
    status: "experimental",
    maturity: 58,
    release: "0.5.0",
    evidence:
      "533 low-eventability signals retained as deferred observations, zero clustering backlog and reversible review snapshots",
  },
  {
    slug: "event-convergence",
    name: "人工事件整理",
    domain: "understanding",
    status: "experimental",
    maturity: 50,
    release: "0.5.0",
    evidence:
      "family/facet merge queue, readiness-aware target selection, explicit confirmation and append-only merge audit",
  },
  {
    slug: "entity-resolution",
    name: "实体与别名对齐",
    domain: "understanding",
    status: "planned",
    maturity: 10,
    release: "future",
    evidence: "actor catalog only",
  },
  {
    slug: "claim-evidence",
    name: "Claim 级证据链",
    domain: "understanding",
    status: "planned",
    maturity: 12,
    release: "future",
    evidence: "event-signal provenance exists; claim mapping pending",
  },
  {
    slug: "fact-reason-impact",
    name: "Fact / Reason / Impact",
    domain: "understanding",
    status: "experimental",
    maturity: 38,
    release: "0.1.0",
    evidence: "event fields exist; automatic reasoning evaluation pending",
  },
  {
    slug: "confidence",
    name: "可信度评分",
    domain: "intelligence",
    status: "experimental",
    maturity: 35,
    release: "0.1.0",
    evidence: "explainable baseline; real calibration set pending",
  },
  {
    slug: "heat",
    name: "跨圈热度判断",
    domain: "intelligence",
    status: "experimental",
    maturity: 24,
    release: "0.1.0",
    evidence: "baseline factors; real cross-platform observation network pending",
  },
  {
    slug: "impact-value",
    name: "影响与价值分析",
    domain: "intelligence",
    status: "experimental",
    maturity: 32,
    release: "0.1.0",
    evidence: "scoring schema and curated examples; outcome calibration pending",
  },
  {
    slug: "trend",
    name: "趋势与拐点识别",
    domain: "intelligence",
    status: "planned",
    maturity: 8,
    release: "future",
    evidence: "timeline grouping only",
  },
  {
    slug: "contradiction",
    name: "反证与冲突检测",
    domain: "intelligence",
    status: "planned",
    maturity: 5,
    release: "future",
    evidence: "Scout counter-signal field only",
  },
  {
    slug: "scout",
    name: "Opportunity Scout",
    domain: "intelligence",
    status: "experimental",
    maturity: 56,
    release: "0.7.0",
    evidence:
      "evidence-bound deterministic opportunities with recency-aware selection, cooldown, automatic publication gates and archival",
  },
  {
    slug: "forecast",
    name: "预测与校准",
    domain: "intelligence",
    status: "planned",
    maturity: 0,
    release: "future",
    evidence: "roadmap only",
  },
  {
    slug: "today",
    name: "关键变化摘要",
    domain: "experience",
    status: "experimental",
    maturity: 36,
    release: "0.1.0",
    evidence: "executive lead from published events",
  },
  {
    slug: "timeline",
    name: "Timeline 主线",
    domain: "experience",
    status: "operational",
    maturity: 66,
    release: "0.6.0",
    evidence:
      "year/month evidence timeline with track/search filters, a global evidence drawer and 64 addressable event pages",
  },
  {
    slug: "radar",
    name: "Radar 格局观察",
    domain: "experience",
    status: "experimental",
    maturity: 30,
    release: "0.1.0",
    evidence: "actor catalog and visual radar; evidence-based movement pending",
  },
  {
    slug: "inbox",
    name: "自动机会沉淀",
    domain: "experience",
    status: "experimental",
    maturity: 55,
    release: "0.7.0",
    evidence: "Scout opportunities are automatically published or archived without a human queue",
  },
  {
    slug: "control-room",
    name: "Control Room",
    domain: "experience",
    status: "experimental",
    maturity: 70,
    release: "0.7.0",
    evidence:
      "read-only operational audit for source health, automated publication, merge candidates, evaluation and Scout outcomes",
  },
  {
    slug: "publication-readiness",
    name: "发布前检查",
    domain: "governance",
    status: "operational",
    maturity: 74,
    release: "0.7.0",
    evidence:
      "ready events publish automatically while missing evidence, placeholders, taxonomy gaps, low confidence and unsupported heat remain isolated",
  },
  {
    slug: "static-release",
    name: "隐私安全静态发布",
    domain: "delivery",
    status: "operational",
    maturity: 76,
    release: "0.6.0",
    evidence:
      "allowlist JSON export, 60-route static multipage renderer, repository metadata and GitHub Pages workflow",
  },
  {
    slug: "multipage-intelligence",
    name: "多页决策情报体验",
    domain: "experience",
    status: "operational",
    maturity: 70,
    release: "0.6.0",
    evidence:
      "latest material shift above the fold, six strategic lines, event permalinks, four decision tools and a productized changelog",
  },
  {
    slug: "issue-source-governance",
    name: "Issue 驱动的来源治理",
    domain: "governance",
    status: "experimental",
    maturity: 52,
    release: "0.6.0",
    evidence:
      "structured source proposals, offline validation, trusted maintainer gate and disabled draft PR import",
  },
  {
    slug: "content-rights-boundary",
    name: "内容版权与引用边界",
    domain: "governance",
    status: "operational",
    maturity: 64,
    release: "0.6.0",
    evidence:
      "320-character snapshot excerpts, canonical attribution, takedown route and explicit code/content license separation",
  },
  {
    slug: "repository-snapshot",
    name: "仓库数据快照",
    domain: "delivery",
    status: "operational",
    maturity: 72,
    release: "0.4.0",
    evidence:
      "deterministic privacy-safe JSON snapshot with merge restore and sensitive URL stripping",
  },
  {
    slug: "release-evolution",
    name: "版本演进与 Changelog",
    domain: "delivery",
    status: "operational",
    maturity: 74,
    release: "0.7.0",
    evidence:
      "versioned repository and website changelogs with an enforced contract and automatic GitHub Release creation",
  },
  {
    slug: "evaluation",
    name: "多维评测体系",
    domain: "governance",
    status: "experimental",
    maturity: 62,
    release: "0.2.0",
    evidence:
      "versioned evaluation history, a current scorecard, previous-main CI regression gates and ranked evidence-backed improvement actions",
  },
  {
    slug: "bounded-evolution",
    name: "有界持续进化循环",
    domain: "governance",
    status: "experimental",
    maturity: 54,
    release: "0.5.0",
    evidence:
      "bounded scheduled loop with atomic checkpoints, per-iteration reports, failure isolation, explicit mutation flags and graceful shutdown",
  },
  {
    slug: "security",
    name: "采集与管理安全",
    domain: "governance",
    status: "operational",
    maturity: 66,
    release: "0.1.0",
    evidence: "SSRF guard, body limit, CSP, bearer auth and text rendering",
  },
  {
    slug: "capability-accounting",
    name: "能力资产核算",
    domain: "governance",
    status: "operational",
    maturity: 58,
    release: "0.2.0",
    evidence: "capability map links status, maturity, release and implementation evidence",
  },
] as const;

export const roadmap = [
  {
    state: 1,
    name: "可信时间轴骨架",
    promise: "把分散信号变成可审核、可发布的唯一事件节点。",
    status: "current",
    milestones: [
      "M1 · Node/TypeScript + SQLite 的可复现数据与发布骨架",
      "M2 · Event / Track / Actor / Evidence 基础模型与静态 Timeline",
      "M3 · 管理审核、隐私 allowlist 与 GitHub Pages release 链路",
      "M4 · 用真实数据替换 demo 分数，并验证后台数据能够完整进入发布快照",
    ],
  },
  {
    state: 2,
    name: "可信感知网络",
    promise: "来源可以长期运行，数据质量和覆盖缺口可以被量化。",
    status: "building",
    milestones: [
      "M1 · 100+ 可靠来源目录与国内外覆盖评分",
      "M2 · 生命周期、契约 fixture、重试限流、增量状态与 Source SLO",
      "M3 · 分离 Document 与 Observation，保留跨来源传播和媒体归属关系",
      "M4 · 调度、漂移检测、fallback、canary 与可回放的来源运维系统",
    ],
  },
  {
    state: 3,
    name: "行业理解与证据洞察",
    promise: "系统在记录事件的同时，解释事件之间的关系、冲突和趋势。",
    status: "planned",
    milestones: [
      "M1 · 多语言实体、Claim、Evidence、Contradiction 知识图谱",
      "M2 · 自动整理 Fact / Reason / Impact / Signal / Future，并建立评测集",
      "M3 · 具备阶段、转折、因果与对比关系的 Narrative Timeline",
      "M4 · Opportunity Scout Beta：串联证据、反证、反馈和产出结果",
    ],
  },
  {
    state: 4,
    name: "个人战略与知识网络",
    promise: "把行业变化连接到用户目标、行动和长期个人资产。",
    status: "planned",
    milestones: [
      "M1 · CEO / 投资 / 技术 / 创业关注组合与本地 Owner Profile",
      "M2 · Scout 建议到 48 小时实验、7 日产物和结果复盘",
      "M3 · 判断记录、作品、关系和影响力的长期资产图谱",
      "M4 · 个性化 weekly decision brief 与弱信号注意力预算",
    ],
  },
  {
    state: 5,
    name: "可校准的 AI 决策副驾",
    promise: "从持续观察走向可验证预测，并在治理边界内自我演进。",
    status: "planned",
    milestones: [
      "M1 · Scenario、领先指标、预测 Ledger 与 Brier 校准",
      "M2 · 自动发现覆盖缺口并提出 Source / Detector / Adapter 改进提案",
      "M3 · Shadow replay、策略 A/B、自动回滚与人工 promotion 治理",
      "M4 · 受预算、权限、审计和人工批准约束的多 Agent 调研网络",
    ],
  },
] as const;

export const releases = [
  {
    status: "unreleased",
    version: "unreleased",
    date: "",
    name: "Next Evidence Iteration",
    summary: "让公开站更容易理解，并保持自动化来源生命周期证据准确可审计。",
    capabilities: [
      "Fork 独立生产发布",
      "全站用户语言导航",
      "领域趋势信息层级",
      "目的明确的跨页入口",
      "事件时间线筛选交互",
      "AI 可读站点索引",
    ],
    changes: [
      "GitHub Pages、数据刷新与监控动态使用当前仓库站点 URL，健康监控按标签和审计 marker 查找来源健康 Issue，使 fork 不依赖上游 URL 与固定 Issue 编号即可独立部署",
      "直接研究源采集失败时，Actions warning 只陈述本次未采集、生命周期不变与批次继续，不再把实际 quarantined 状态误写成 shadow",
      "Source Audit 与 Data Refresh 在远端快照 merge 后重新执行来源对账，防止旧生命周期覆盖已满足连续健康门槛的隔离来源恢复结果",
      "公开站统一使用领域趋势、事件时间线、来源更新、行动建议、公司与机构、模型价格和信息来源等直白名称",
      "首页明确随机展示六个领域中的一个趋势；趋势页把阶段轨迹和阶段证据改为趋势变化轨迹与关键事件和证据",
      "查看趋势详情等含糊入口改为查看领域分析、查看相关事件、查看事件时间线等明确目的文案",
      "趋势变化轨迹与关键事件改为最新阶段优先，阶段箭头同步反向",
      "来源更新新增粗粒度来源类型过滤，移动端地域与来源类型过滤器紧凑并排",
      "本地启动、数据库 seed 与默认静态导出自动合并仓库最新快照，避免新 clone 停留在不完整的 seed 数据",
      "系统能力评测历史进入版本化快照，CI 以上一提交为基线阻止分数回退，并持续输出按加权缺口排序的真实改进动作",
      "事件时间线筛选 tabs 支持桌面鼠标拖拽，取消加载时自动居中，仅在用户点击筛选项后平滑居中",
      "公开站新增符合 llms.txt 约定的 AI 可读索引，明确事实、观察与假设边界，并在 Footer 提供可发现入口",
    ],
  },
  {
    status: "released",
    version: "0.11.1",
    date: "2026-07-14",
    name: "Audited Research Continuity",
    summary:
      "少一点噪声，多一点能行动的判断：研究先经过直接信源与影响审计，AI 再在证据门禁后参与整理，Timeline 与移动阅读也更顺手。",
    capabilities: [
      "年龄感知研究质量门禁",
      "限期审计的直接信源影响路径",
      "2026 官方研究脉络",
      "Microsoft 与 Google Research 影子采集",
      "连续研究覆盖缺口告警",
      "移动端趋势换一条对齐",
    ],
    changes: [
      "当年论文不再被成熟论文引用阈值误伤；官方研究页、完整论文与正式出版、代码或部署证据组成限期审计包后可进入事件脉络",
      "补充 Microsoft、OpenAI、Anthropic 与 Google 直接发布的 7 项研究，恢复 2026 年 1—7 月高质量研究脉络；Microsoft Research 与 Google Research RSS 在 Actions 中保持 shadow 观察",
      "研究审计检查最近 6 个完整月份；连续 2 个月没有合格研究时阻止静默发布并暴露信源缺口，但不会自动降低门槛补量",
      "移动端首页“最新趋势判断”的“换一个”操作固定在卡片头部右上角，窄屏下仍与标题清晰对齐",
    ],
  },
  {
    status: "released",
    version: "0.11.0",
    date: "2026-07-14",
    name: "Clearer Evidence and Automated Briefs",
    summary:
      "以跨 Tab 发布门禁、外部研究影响证据和安全 AI 自动化，补齐时间线、资本来源、监控、SEO / GEO 与静态发布闭环。",
    capabilities: [
      "跨 Tab 公开内容一致性门禁",
      "批量静态导出",
      "可抓取事件详情与来源地图 Dataset",
      "安全结构化数据",
      "生产依赖安全升级",
      "DeepSeek 结构化整理事件",
      "AI 决策周报",
      "阶段证据默认展示",
      "行动参考 tabs 滚动修复",
      "紧凑 GitHub 周报",
      "空周报发布检查",
      "实时 GitHub Star",
      "Actions 增量数据可靠回流",
      "重大里程碑阶段晋级",
      "Timeline 月级密度控制",
      "外部影响证据约束的当月论文组",
      "可审计研究影响门禁",
      "移动端事件抽屉滚动复位",
      "全站文案审校",
      "移动阅读与页脚交互优化",
      "移动端 Hero 标题对齐",
      "长页回到顶部",
      "移动端列表分批展示",
      "AI 参与的健康告警降噪",
      "投资机构信源与资本事件补强",
      "Timeline 年月快捷导航",
    ],
    changes: [
      "DeepSeek 只处理已有一手证据的待审事件，结构化结果通过格式、证据引用、趋势归属和发布条件检查后才会发布",
      "周报只读取公开 DTO，按核心判断、判断变化、角色决策、待验证项和下周观察生成结构化草稿，再由程序确定性渲染 Markdown",
      "Actions Secret 只在对应步骤注入，运行摘要不记录密钥、原始响应或私有字段",
      "趋势详情的阶段证据退出全局滚入动画，其他模块动效保持不变",
      "行动参考 tabs 关闭纵向溢出，只在极窄屏保留横向容错",
      "周报按 Event 去重，只保留最多三个关键变化和三项行动；空趋势合并，覆盖指标默认折叠",
      "当周没有事件通过发布检查时，不生成周报正文，Data Refresh 也不会创建或更新 Issue",
      "顶部 Star 在页面加载时请求 GitHub 官方 API；构建值和本地缓存仅作为失败兜底",
      "Data Refresh 先完成快照 merge、隐私校验、commit、push 与 Pages dispatch，再尝试可选 AI 周报；模型失败不会丢失确定性增量",
      "AI 周报结构失败会进行一次有界修复重试并留下安全状态，Monitor 生命周期百分比与 CI 失败定位同步修正",
      "趋势阶段新增改为极低频晋级：确定性门禁先筛候选，DeepSeek V4 Pro 以高强度思考默认审慎保留，只有通过 Event、Evidence、Source、时间边界和置信度复核后才会创建专属 Issue 并写入版本化阶段记录",
      "阶段 Issue 必须先于数据落库成功创建，完整记录重大事件、旧阶段失效原因、影响、中国位置、反向信号和下一验证；模型或 Issue 失败不会阻断确定性快照增量回流",
      "事件脉络超过 500 个公开 Event 时按月份懒挂载旧内容；单月超过 6 个表层条目时提供展开与收起，并在筛选和搜索时完整显示命中项",
      "研究内容按月整理，只在“全部变化”和“论文与研究”视图展示；取消逐月保底，月份可以没有论文，每月最多展示 10 篇通过内容与研究影响双重门禁的论文",
      "研究影响报告通过 OpenAlex 批量核验论文身份、引用总量和近年引用速度；Data Refresh 在自动发布前 fail-closed 执行，报告缺失、过期或身份不匹配的论文不进入 Timeline",
      "Timeline 以置信度为第一排序键，再比较影响、价值与热度；中英文不设比例，当月论文组也不占单月 6 个普通事件名额",
      "可点击块不再显示点击后的 outline；单一一手证据统一使用“官方资料”标签",
      "移动端事件抽屉每次打开事件时重置到顶部，不再继承上一次查看的滚动位置",
      "事件抽屉仅在存在至少两条发展记录时展示“事情如何发展”，避免单条内容与原始证据重复",
      "中英文 README 改为决策问题与产品地图结构，并按最新机器证据区分目录、观测、active 与公开发布状态",
      "来源动态瀑布流支持整卡打开原文、hover 与键盘焦点反馈，轻量高亮标签和来源，并修正外链 icon 与加载入口对齐",
      "逐页审校公开站与管理台文案，减少模板化对比句和抽象内部术语，并用更直接的语言说明内容、证据范围与操作结果",
      "事件抽屉使用独立内容滚动并简化卡片层级；移动端时间线和趋势导航更紧凑且平滑居中，来源动态区分论文与 Tier 1 来源，页脚增加快照追溯和作者联系方式",
      "移动端顶部 Hero 统一标题间距、换行和响应式字号；默认趋势详情取消顶部留白，小屏隐藏会挤压文字的装饰动效",
      "长页滚动超过首屏后提供回到顶部按钮；移动端避让底部导航和安全区，减少动效模式下改为立即返回",
      "移动端将来源动态、Scout、关键角色、模型成本、覆盖与来源目录改为 4–12 条一批；支持按批继续查看，筛选后自动回到紧凑首批",
      "健康监控使用稳定指纹和七天冷却抑制重复通知，人工触发默认只评估；上下文型 critical 由 AI 返回结构化建议并通过本地置信度门禁，站点故障等硬错误始终立即告警",
      "资本与公司演化接入 Sequoia、Menlo、Madrona、Battery 与顺为官方 Feed，并补齐 10 个由公司官方公告支撑的融资、战略投资和公司整合事件；新增来源保持 disabled + shadow",
      "事件脉络左侧日期支持直接选择年份和月份，并在筛选可见范围内平滑定位、按需加载较早月份，同时写入可分享的 date 查询参数",
      "公开站完整性验证会检查中英文主 Tabs、数据生成时间、详情页、canonical、hreflang、JSON-LD 与 Sitemap，并在 CI、数据刷新、来源审计和 Pages 发布前 fail-closed",
      "静态导出批量读取 Event 的 Evidence、Track 与 Actor 关系；Timeline 使用可抓取链接并保留抽屉交互和无 JavaScript 详情回退",
      "首页、事件、时间线和来源地图补齐 WebSite、Organization、Article、BreadcrumbList、CollectionPage、ItemList 与 Dataset 结构化数据，页面摘要唯一且 Sitemap 路径标准编码",
      "JSON-LD 安全转义脚本边界字符，管理台动态字段统一转义；生产静态文件依赖升级并启用 TypeScript 未使用代码检查",
    ],
  },
  {
    status: "released",
    version: "0.10.0",
    date: "2026-07-14",
    name: "Living Evidence Interface",
    summary:
      "把重点厂商覆盖、全来源回填和更轻的静态交互连接起来，让趋势、阶段证据与来源动态在保持证据边界的同时承载更多可探索信息。",
    capabilities: [
      "22 家重点厂商覆盖表",
      "27 个官方来源入口",
      "32 个关键 Event",
      "411 源全量审计与回填",
      "静态资源与 JSON 压缩",
      "非关键数据按需加载",
      "模块级趋势展开",
      "阶段序号证据映射",
      "每日数据与 Pages 刷新",
    ],
    changes: [
      "事件脉络补齐全球前沿模型、中国重点模型团队与 AI 原生搜索产品，不再只按单个品牌补漏",
      "新增覆盖契约，重点厂商只有在同时具备官方来源与可检索 Event 时才算进入事件脉络",
      "新增来源保持 disabled + shadow，目录登记、端点可访问和用于公开事实分别执行不同检查",
      "完成 411 个来源的全量审计，并在 284 个合规来源上回填 299 条新 Signal；16 个来源错误保持单源隔离",
      "CSS、JavaScript 和公开 JSON 在导出时压缩，主脚本提前下载，全量来源数据改为交互时按需请求，Stars 与第三方行情延后加载",
      "来源动态地域筛选改为与搜索框一致的自定义选择控件，并保留键盘和原生 select 可访问性",
      "趋势判断取消全局展示模式，默认使用简洁呈现；阶段轨迹、阶段证据、角色判断和观察源池各自在模块内展开",
      "阶段轨迹的整块展开与收起位于标题栏右侧，阶段证据用相同的 01、02 序号对应轨迹阶段",
      "Data Refresh 每天抓取并刷新 Pages；weekly-brief 仍只在周日或显式触发时按 ISO 周幂等更新",
    ],
  },
  {
    status: "released",
    version: "0.9.0",
    date: "2026-07-13",
    name: "Evidence-Dense Decision Intelligence",
    summary:
      "把扩大的来源与事件供给组织为真实阶段、分阶段证据和角色决策镜头；持续监测，只在重要证据出现时更新公开判断，并以 GitHub 周报完成周期复盘。",
    capabilities: [
      "5—8 段真实趋势轨迹",
      "简洁 / 全量双密度模式",
      "分阶段证据与观察源池",
      "24 组角色决策镜头",
      "GitHub AI 周报",
      "100-source 扩展波次",
      "来源组合四维视图",
      "18 个 Tier 1 来源",
      "宏观与央行覆盖",
      "监管与交易所披露",
      "Shadow-first 治理",
      "授权数据隔离",
      "单调快照合并",
      "跨来源观测",
      "合规全来源同步",
      "事件驱动判断更新",
      "公开内容变更部署",
      "动态首页内容发现",
      "公开来源观察流",
      "周更自动运营",
    ],
    changes: [
      "首页移除冗长宣言区并直接展示最新关键变化；全站内容区取消右上角说明文案，主要标题统一收短",
      "趋势总览改为六个视角，总览与详情页统一使用轻量横向列表，并移除首屏与阶段证据统计仪表",
      "六条趋势按各自主线拆成 5—8 个阶段，单行横向滚动，并按阶段展示全部公开 Event、证据计数、解读与下一验证",
      "增量证据按发布时间进入开放阶段，同时保留唯一 Event 的事实起点与证据回链，阶段计数互不串位",
      "四种角色补齐核心回答、影响链、动作、继续观察和 Event 回链，不再各取一条事件字段作为答案",
      "新增可持久化的简洁/全量模式；观察源池与事实证据严格分开，低覆盖主线保留可见缺口",
      "紫色实心按钮统一使用白字，行动参考内容区取消纵向 section padding",
      "Watch 与 AI 周报订阅入口并入 Footer，主导航页标题、间距和行动参考布局统一",
      "首页首模块改为趋势阶段、当前判断、最新证据与下一信号，轻量证据网络替代悬浮黑球动效",
      "首页移除形成判断和继续深入模块，相关入口并入 Footer；行动参考只展示行动、角色和成本三个入口",
      "简洁模式支持逐阶段展开全部证据并随时收起",
      "趋势详情移除证据缺口块，Footer 重构为品牌、订阅、分组导航与元信息层",
      "趋势总览移除理解框架，Timeline 左侧粘性时间标记随滚动展示年月",
      "四个主入口使用各自不同的轻量动效，语言切换移入暖灰渐变 Footer",
      "趋势判断默认进入模型能力与研究，行业演化拆为 Footer 独立入口，并移除中国实践模块",
      "字体统一为浏览器系统字体栈，链接焦点不再显示 outline 外框",
      "首页移除本周研究，行业趋势整卡可点击；事件脉络筛选项选中后自动居中",
      "Footer 改为浅暖灰渐变与更大留白，证据状态简化为官方来源、多源核验等直接表达",
      "修复右上角 GitHub Stars 在构建元数据缺失和窄屏下不展示的问题，增加浏览器补取缓存与紧凑移动端样式",
      "全站只保留 Watch 与周报订阅入口；取消固定日更，Data Refresh 在北京时间周日幂等更新 weekly-brief Issue",
      "新增 FRED、ALFRED、IMF WEO、BIS、BLS、BEA、美国财政部、ECB、OECD、World Bank 与 Eurostat",
      "新增 SEC EDGAR、国家统计局、人民银行、CNINFO、SSE 与 SZSE 官方入口",
      "新增 80 个官方 Release Feed 与 20 个研究、产业、政策和资本 Feed，全部从 shadow 开始",
      "来源页按领域、地域、采集通道和真实运行状态展示来源组合，并提供健康与通道筛选",
      "Nasdaq Data Link 明确保持 restricted，未授权行情和估值数据不进入公开输出",
      "所有新增来源默认 disabled 与 shadow/manual，不改变既有采集、排名和发布规则",
      "快照恢复保留较新和更完整的本地记录、完整来源运行历史与事件关系",
      "同一 canonical Signal 保存多来源 observation，不再因 URL 去重丢失观测来源",
      "GitHub Actions 写入前合并 origin/main 最新快照，避免旧任务覆盖有序增长",
      "首页按刷新随机展示一个有公开证据的趋势方向；近期变化在刷新页面时随机展示六条，桌面端一行两条",
      "六个行业趋势块保持同时可见，以六种主题色区分方向；每块内部轮播多个 Event，并支持手动切换、键盘、触摸与 reduced-motion",
      "趋势判断、近期换批与主要模块滚入使用克制的上浮淡入；阶段轨迹以序号、间距与连接关系表达阶段变化",
      "新增来源动态瀑布流，以独立动效、简述和 allowlist DTO 搜索、筛选、分批呈现 4,057 条合规 Signal",
      "Data Refresh、Source Audit、Quality Guard 和 Monitor 从日内高频调整为周计划",
    ],
  },
  {
    version: "0.8.1",
    date: "2026-07-13",
    name: "A Denser Action Surface",
    summary: "简化首页、趋势和行动参考的首屏路径，并让星探持续维护覆盖六类行动方式的公开建议池。",
    capabilities: [
      "紧凑阅读路径",
      "趋势主线直达",
      "六类星探机会",
      "18 条公开机会池",
      "确定性去重与过期轮换",
    ],
    changes: [
      "首页把关键变化、证据脉络、每周复盘阅读路径移到价值标题右侧，并保留窄屏单列阅读体验",
      "趋势总览用六条可点击主线替换事件数、时间跨度和引导标签，减少进入详情前的判断成本",
      "收紧星探机会标题、观察与假设之间的纵向间距，提高同屏信息密度",
      "星探扩展为创业、内容、工作、学习、产物与影响力六类，并自动补齐缺失类型",
      "公开机会池维持至少 18 条唯一建议，生成内容 14 天后自动轮换，避免无限累积与重复上架",
      "每轮后台数据刷新最多生成 12 条候选，以便在机会池不足时及时恢复公开密度",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-07-13",
    name: "The Industry Evolution Map",
    summary:
      "把 2022 年至今的技术、产品、公司和商业变化连接成可追溯的产业演化地图；早期增量简报现已合并到周报。",
    capabilities: [
      "2022—今天产业骨架",
      "六个趋势判断维度",
      "项目生命周期状态",
      "完整证据抽屉",
      "高置信星探去重",
      "GitHub 增量简报（已合并到周报）",
    ],
    changes: [
      "六个趋势调整为模型研究、Agent 软件、产品商业、基础设施、资本公司和全球创新，每个板块都提供详情入口",
      "新增 13 个 2022—2023 官方来源里程碑，并以六个产业阶段连接 ChatGPT 时刻到今天",
      "阶段卡片展示代表项目的持续发展、转向、收购与停止状态，所有状态回链官方资料",
      "移除论文批次和近三月密度运营模块，事件筛选改为普通用户可理解的官方发布、研究与趋势问题",
      "证据抽屉展示完整发展节点、五类分析、置信度和全部原始资料，并统一桌面与移动端间距",
      "公开星探自动去重，标签左对齐，补充目标用户、四项质量指标和完整实验信息",
      "数据刷新每四小时运行，并只消费公开静态 DTO；固定频率公开简报现已停止",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-07-13",
    name: "The Autonomous Intelligence Loop",
    summary:
      "让来源、事件、论文、星探、评测、版本和 Pages 可以按计划自动更新，同时补齐近期内容与核心 AI 专家覆盖。",
    capabilities: [
      "全站证据抽屉",
      "年月事件脉络",
      "研究内容分层",
      "事件与星探自动发布",
      "低分质量守卫",
      "核心 AI 专家列表",
      "GitHub Release 自动发布",
    ],
    changes: [
      "首页围绕关键变化、影响与判断重建信息消费路径",
      "事件脉络按年月倒序组织，证据在首页、趋势、研究、事件和星探等入口原地打开",
      "最近 7 天内容统一高亮，并把最近三个完整自然月补齐到每月不少于 6 个官方来源事件",
      "论文区域展示最近三天批次状态，区分真实更新、周末节奏与等待下一批，不用空卡或虚构数据掩盖缺口",
      "事件通过事实检查后自动发布；行动建议通过质量检查后直接上线，不合格项自动归档",
      "数据每四小时后台刷新，评测低于 60 分时由两小时质量守卫按冷却规则触发增量更新",
      "新增 12 位国内外核心 AI 专家，个人 RSS 自动采集，受限社交账户明确标记且不绕过平台限制",
      "CI 校验仓库与网站 Changelog 后自动创建对应 GitHub Release，并继续触发隐私安全的 Pages 发布",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-07-12",
    name: "The Intelligence Atlas",
    summary:
      "把拥挤的单页拆成可寻址的决策情报地图，并将来源提案、健康维护、版权边界与 GitHub 自更新纳入同一产品链路。",
    capabilities: [
      "多页决策情报",
      "六条主线详情",
      "独立证据工作台",
      "44 个事件永久链接",
      "Issue 来源治理",
      "持续健康维护",
      "动态 GitHub 元数据",
      "版权与纠错边界",
    ],
    changes: [
      "首页将关键变化判断提升到首屏，把产品宣言移动到末尾，并复用主线、证据、工具与版本数据",
      "生成 60 个可独立访问的静态内容页，六条主线、证据时间轴、事件和四个决策工具不再挤在单页",
      "来源 Proposal Issue 先离线校验，再经可信维护者标签进入 disabled draft PR，不能直接激活或写入生产",
      "来源审计与数据刷新共享串行写锁、恢复并回写同一快照；健康摘要由单一 Issue 幂等维护",
      "Pages 构建时注入 Stars、Forks 与 Issues 元数据；默认 README 国际化为英文并提供完整中文入口",
      "仓库快照只保留最多 320 字符的内容摘录，并新增来源归属、版权、纠错下架与第三方图标许可说明",
    ],
  },
  {
    version: "0.5.1",
    date: "2026-07-12",
    name: "Snapshot Parity",
    summary:
      "让本地、定时刷新与 GitHub Pages 从同一份来源健康和星探证据恢复，消除发布路径数据漂移。",
    capabilities: [
      "来源检查快照",
      "运行证据快照",
      "星探公开产物快照",
      "跨环境评测一致性",
      "隐私安全恢复",
    ],
    changes: [
      "快照新增 990 条来源检查、137 个逐源最新运行、4 条公开星探与 4 条证据关联",
      "来源成功/失败计数、最近成功和验证时间随快照恢复，CI 不再丢失健康上下文",
      "fresh database 恢复后评测保持 30 分、raw 42、证据覆盖 20%，星探保持 4 条",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-07-12",
    name: "The Evidence Engine",
    summary: "恢复 100+ 严格有效信源，以隔离观察、诚实评测和证据优先体验重建从供给到决策的链路。",
    capabilities: [
      "100+ 严格实时有效信源",
      "隔离观察数据池",
      "逐源恢复审计",
      "可逆信号分诊",
      "人工事件整理",
      "诚实评测校准",
      "证据优先时间轴",
      "有界持续进化",
    ],
    changes: [
      "来源目录扩至 258 个；全量实测 131 healthy、120 strict effective、104 strict realtime effective",
      "99 个合格 shadow 来源进入 E3 隔离观察，采集到的数据仍需通过 E4 检查才能用于公开事实",
      "建立逐源检查、失败分类、代理降级、质量检查、可逆分诊、重复事件候选和发布状态统计",
      "评测从目录数量和人工自评分转向真实样本、证据覆盖与硬上限，旧口径 69 分回落到诚实水位",
      "公开页改为关键变化判断、六条主线和证据优先时间轴；默认事件必须包含一手来源",
      "管理台补齐来源健康、观察开关、漏斗、阻断原因、证据详情、合并队列与校准评测",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-07-11",
    name: "The Industry Arc",
    summary: "从新闻式堆叠转向两年行业主线，并让数据采集、仓库快照与 GitHub Pages 持续联动。",
    capabilities: [
      "持续数据刷新",
      "仓库数据快照",
      "两年行业基线",
      "主线阶段整理",
      "高密度公开首页",
    ],
    changes: [
      "新增每 6 小时 GitHub Actions 数据刷新；数据变化后提交隐私安全 JSON 快照并显式部署 Pages",
      "建立 2024-07 至 2026-07 行业基线，加入 30 个一手来源里程碑和 5 个发展阶段",
      "默认公开页面聚焦关键变化、六条趋势和两年演进摘要，其他工具按需展开",
      "新增全球创新版图的阶段性同维度对照，不再只呈现静态公司排名",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-07-11",
    name: "Primary Source Protocol",
    summary: "聚合站只用于发现线索，事实、传播热度和原始发布者分别记录在对应的数据层。",
    capabilities: [
      "聚合上游发现",
      "一手事实检查",
      "来源身份匹配",
      "聚合热度回填",
      "官方价格基线目录",
      "候选来源发现",
    ],
    changes: [
      "AI HOT、HuggingNews 等聚合器只写 Source Discovery，不再直接生成事实 Signal",
      "按原始 URL、唯一域名和社交账号匹配直接来源，无法匹配的内容进入人工候选队列",
      "补入 AI HOT 背后的官方、研究、专家与专业媒体来源，并扩充至 195 个来源",
      "PriceAI 保留为比较入口，价格改由厂商官网、App Store 与独立汇率源采集",
      "Evaluation 新增一手来源归属维度，持续暴露历史聚合器证据债务",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-07-11",
    name: "The Source & Scout Foundation",
    summary: "从可演示 Timeline 转向可运营来源平台，并第一次把行业信号转化为机会假设。",
    capabilities: [
      "重点来源目录",
      "信源生命周期",
      "弹性拉取",
      "SourceRun",
      "Opportunity Scout",
      "多维评测",
      "能力资产核算",
    ],
    changes: [
      "建立 100+ 国内外来源目录，并区分 ready、candidate、restricted 与 manual",
      "加入有界并发、瞬时错误重试、条件请求、健康分、自动降级与人工隔离",
      "加入有证据支持的行动建议、冷却去重、私有 inbox 和人工发布检查",
      "加入 State 1–5 Roadmap、Capability Map、评测 Scorecard 与公开演进时间轴",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-07-11",
    name: "First Signal",
    summary: "把 Python/JSON 原型重构为可运行的 Node/TypeScript 行业证据与判断系统。",
    capabilities: ["Event 模型", "多主线 Timeline", "Control Room", "静态发布"],
    changes: [
      "建立 SQLite/MySQL 抽象、migration、统一 SourceAdapter 与 Event pipeline",
      "建立多条趋势、角色列表、模型资源和右侧详情抽屉",
      "建立 Fastify 管理 API、静态导出、CI 与 GitHub Pages",
    ],
  },
] as const;
