import {
  type SourceProposalCatalogEntry,
  SourceProposalCatalogSchema,
} from "../domain/source-proposal.js";
import { capitalEvidenceSources20260714 } from "./capital-evidence-sources-2026-07.js";
import { ecosystemEvidenceSources20260714 } from "./ecosystem-evidence-sources-2026-07.js";
import { type EmbodiedCatalogSource, embodiedSourceCatalog } from "./embodied-data/sources.js";
import { sourceExpansionWave20260713 } from "./source-expansion-2026-07.js";
import sourceProposalRows from "./source-proposals.json" with { type: "json" };
import { vendorEvidenceSources20260714 } from "./vendor-evidence-sources-2026-07.js";

export type SourceCategory =
  | "frontier-lab"
  | "china-lab"
  | "research-eval"
  | "open-source"
  | "agent-devtool"
  | "robotics"
  | "infra-chip-cloud"
  | "capital-business"
  | "model-economics"
  | "policy"
  | "expert"
  | "media"
  | "community-heat"
  | "aggregator"
  | "robot-team"
  | "data-service"
  | "capture-tool"
  | "dataset-benchmark"
  | "standard-policy"
  | "peer-evidence";

export type Acquisition = "rss" | "api" | "github" | "arxiv" | "html" | "social" | "manual";

export interface CatalogSource {
  slug: string;
  name: string;
  owner?: string;
  homepageUrl: string;
  endpoint: string;
  adapter: string;
  tier: 1 | 2 | 3 | 4;
  role: "primary" | "research" | "expert" | "media" | "heat" | "aggregator" | "policy";
  region: string;
  language: string;
  authorityScore: number;
  qualityScore: number;
  enabled: boolean;
  lifecycleStatus: "draft" | "shadow" | "active";
  category: SourceCategory;
  acquisition: Acquisition;
  topics: string[];
  maintenanceStatus: "ready" | "candidate" | "restricted" | "manual" | "proposal";
  cadence: string;
  licenseNote: string;
  robotsPolicy?: string;
  freshnessSloHours?: number;
  adapterVersion?: string;
  identityHosts?: string[];
  socialHandles?: string[];
  proposalIssueNumber?: number;
  proposalEvidenceUrls?: string[];
}

type SourceSeed = readonly [
  slug: string,
  name: string,
  homepageUrl: string,
  region: string,
  category: SourceCategory,
  tier: 1 | 2 | 3 | 4,
  role: "primary" | "research" | "expert" | "media" | "heat" | "aggregator" | "policy",
  acquisition: Acquisition,
  endpoint: string | undefined,
  topics?: string,
];

const rows: SourceSeed[] = [
  // Global frontier labs and product companies.
  [
    "openai",
    "OpenAI",
    "https://openai.com/news/",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "rss",
    "https://openai.com/news/rss.xml",
    "foundation-model,agent,product,safety",
  ],
  [
    "anthropic",
    "Anthropic",
    "https://www.anthropic.com/news",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "foundation-model,agent,safety,enterprise",
  ],
  [
    "deepmind",
    "Google DeepMind",
    "https://deepmind.google/discover/blog/",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "rss",
    "https://deepmind.google/blog/rss.xml",
    "research,agi,robotics,science",
  ],
  [
    "google-ai",
    "Google AI",
    "https://blog.google/technology/ai/",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "rss",
    "https://blog.google/technology/ai/rss/",
    "product,gemini,consumer",
  ],
  [
    "meta-ai",
    "Meta AI",
    "https://ai.meta.com/blog/",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "open-model,research,product",
  ],
  [
    "microsoft-research",
    "Microsoft Research",
    "https://www.microsoft.com/en-us/research/blog/",
    "GLOBAL",
    "frontier-lab",
    1,
    "research",
    "rss",
    "https://www.microsoft.com/en-us/research/feed/",
    "research,agent,enterprise",
  ],
  [
    "microsoft-ai",
    "Microsoft AI",
    "https://microsoft.ai/news/",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "copilot,consumer,enterprise",
  ],
  [
    "xai",
    "xAI",
    "https://x.ai/news",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "foundation-model,product,infra",
  ],
  [
    "mistral",
    "Mistral AI",
    "https://mistral.ai/news",
    "EU",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "open-model,enterprise,eu",
  ],
  [
    "cohere",
    "Cohere",
    "https://cohere.com/blog",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "rss",
    "https://cohere.com/blog/rss.xml",
    "enterprise,rag,foundation-model",
  ],
  [
    "ai2",
    "Allen Institute for AI",
    "https://allenai.org/news",
    "US",
    "frontier-lab",
    1,
    "research",
    "html",
    undefined,
    "open-model,research,science",
  ],
  [
    "nvidia-research",
    "NVIDIA Research",
    "https://research.nvidia.com/",
    "GLOBAL",
    "frontier-lab",
    1,
    "research",
    "html",
    undefined,
    "research,robotics,graphics",
  ],
  [
    "apple-ml",
    "Apple Machine Learning Research",
    "https://machinelearning.apple.com/",
    "GLOBAL",
    "frontier-lab",
    1,
    "research",
    "rss",
    "https://machinelearning.apple.com/rss.xml",
    "on-device,research,consumer",
  ],
  [
    "amazon-science",
    "Amazon Science",
    "https://www.amazon.science/blog",
    "GLOBAL",
    "frontier-lab",
    1,
    "research",
    "rss",
    "https://www.amazon.science/index.rss",
    "research,cloud,commerce",
  ],
  [
    "ibm-research",
    "IBM Research AI",
    "https://research.ibm.com/artificial-intelligence",
    "GLOBAL",
    "frontier-lab",
    1,
    "research",
    "html",
    undefined,
    "enterprise,research,governance",
  ],
  [
    "salesforce-research",
    "Salesforce AI Research",
    "https://www.salesforceairesearch.com/",
    "GLOBAL",
    "frontier-lab",
    1,
    "research",
    "html",
    undefined,
    "enterprise,agent,research",
  ],
  [
    "databricks",
    "Databricks",
    "https://www.databricks.com/blog/category/generative-ai",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "rss",
    "https://www.databricks.com/feed",
    "data,enterprise,open-model",
  ],
  [
    "stability-ai",
    "Stability AI",
    "https://stability.ai/news",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "image,video,open-model",
  ],
  [
    "runway",
    "Runway",
    "https://runwayml.com/research",
    "GLOBAL",
    "frontier-lab",
    1,
    "research",
    "html",
    undefined,
    "video,multimodal,research",
  ],
  [
    "elevenlabs",
    "ElevenLabs",
    "https://elevenlabs.io/blog",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "audio,voice,product",
  ],
  [
    "worldlabs",
    "World Labs",
    "https://www.worldlabs.ai/blog",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "world-model,spatial-intelligence",
  ],
  [
    "perplexity",
    "Perplexity",
    "https://www.perplexity.ai/hub/blog",
    "GLOBAL",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "search,consumer,agent",
  ],

  // China labs, platform companies and infrastructure players.
  [
    "deepseek",
    "DeepSeek",
    "https://api-docs.deepseek.com/news/",
    "CN",
    "china-lab",
    1,
    "primary",
    "html",
    undefined,
    "foundation-model,open-model,reasoning",
  ],
  [
    "qwen",
    "Qwen",
    "https://qwenlm.github.io/blog/",
    "CN",
    "china-lab",
    1,
    "primary",
    "rss",
    "https://qwenlm.github.io/blog/index.xml",
    "open-model,multimodal,agent",
  ],
  [
    "alibaba-cloud-ai",
    "Alibaba Cloud AI",
    "https://www.alibabacloud.com/blog/ai",
    "CN",
    "china-lab",
    1,
    "primary",
    "html",
    undefined,
    "cloud,enterprise,model",
  ],
  [
    "bytedance-seed",
    "ByteDance Seed",
    "https://seed.bytedance.com/en/",
    "CN",
    "china-lab",
    1,
    "research",
    "html",
    undefined,
    "research,foundation-model,multimodal",
  ],
  [
    "doubao",
    "Doubao",
    "https://www.volcengine.com/product/doubao",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "consumer,enterprise,api",
  ],
  [
    "volcengine-ai",
    "Volcano Engine AI",
    "https://www.volcengine.com/product/ark",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "cloud,api,enterprise",
  ],
  [
    "tencent-hunyuan",
    "Tencent Hunyuan",
    "https://hunyuan.tencent.com/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "foundation-model,multimodal,enterprise",
  ],
  [
    "tencent-ai-lab",
    "Tencent AI Lab",
    "https://ai.tencent.com/ailab/en/index/",
    "CN",
    "china-lab",
    1,
    "research",
    "html",
    undefined,
    "research,game,health",
  ],
  [
    "baidu-research",
    "Baidu Research",
    "http://research.baidu.com/",
    "CN",
    "china-lab",
    1,
    "research",
    "html",
    undefined,
    "research,autonomous-driving,foundation-model",
  ],
  [
    "baidu-ernie",
    "Baidu ERNIE",
    "https://yiyan.baidu.com/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "foundation-model,consumer,enterprise",
  ],
  [
    "zhipu",
    "Zhipu AI",
    "https://www.zhipuai.cn/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "foundation-model,agent,api",
  ],
  [
    "minimax",
    "MiniMax",
    "https://www.minimaxi.com/news",
    "CN",
    "china-lab",
    1,
    "primary",
    "html",
    undefined,
    "foundation-model,video,audio,consumer",
  ],
  [
    "moonshot",
    "Moonshot AI",
    "https://www.moonshot.cn/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "foundation-model,consumer,long-context",
  ],
  [
    "stepfun",
    "StepFun",
    "https://www.stepfun.com/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "foundation-model,multimodal",
  ],
  [
    "01-ai",
    "01.AI",
    "https://www.lingyiwanwu.com/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "open-model,enterprise,agent",
  ],
  [
    "baichuan",
    "Baichuan AI",
    "https://www.baichuan-ai.com/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "foundation-model,health,enterprise",
  ],
  [
    "modelbest",
    "ModelBest",
    "https://www.modelbest.cn/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "edge-model,open-model",
  ],
  [
    "sensetime",
    "SenseTime",
    "https://www.sensetime.com/cn/news",
    "CN",
    "china-lab",
    1,
    "primary",
    "html",
    undefined,
    "foundation-model,vision,enterprise",
  ],
  [
    "iflytek",
    "iFlytek Spark",
    "https://xinghuo.xfyun.cn/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "speech,education,enterprise",
  ],
  [
    "huawei-noah",
    "Huawei Noah's Ark Lab",
    "https://www.noahlab.com.hk/",
    "CN",
    "china-lab",
    1,
    "research",
    "html",
    undefined,
    "research,optimization,multimodal",
  ],
  [
    "huawei-ascend",
    "Huawei Ascend",
    "https://www.hiascend.com/en/news",
    "CN",
    "china-lab",
    1,
    "primary",
    "html",
    undefined,
    "chip,infra,ecosystem",
  ],
  [
    "ant-ai",
    "Ant Group AI",
    "https://www.antgroup.com/en/technology",
    "CN",
    "china-lab",
    1,
    "research",
    "html",
    undefined,
    "finance,agent,research",
  ],
  [
    "robbyant",
    "Robbyant / Ant Group",
    "https://github.com/Robbyant",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "robotics,open-source,vla",
  ],
  [
    "jd-explore",
    "JD Explore Academy",
    "https://www.jdcloud.com/cn/news",
    "CN",
    "china-lab",
    1,
    "research",
    "manual",
    undefined,
    "commerce,supply-chain,research",
  ],
  [
    "meituan-longcat",
    "Meituan LongCat",
    "https://github.com/meituan-longcat",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "open-model,agent,commerce",
  ],
  [
    "kuaishou-kling",
    "Kuaishou Kling",
    "https://klingai.com/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "video,consumer,creator",
  ],
  [
    "xiaomi-mimo",
    "Xiaomi MiMo",
    "https://github.com/XiaomiMiMo/MiMo-Code",
    "CN",
    "china-lab",
    1,
    "primary",
    "github",
    "https://github.com/XiaomiMiMo/MiMo-Code/releases.atom",
    "open-model,on-device,reasoning",
  ],
  [
    "oppo-ai",
    "OPPO AI",
    "https://ai.oppo.com/",
    "CN",
    "china-lab",
    1,
    "research",
    "html",
    undefined,
    "on-device,consumer,research",
  ],
  [
    "vivo-ai",
    "vivo AI Lab",
    "https://www.vivo.com/en/activity/ai",
    "CN",
    "china-lab",
    1,
    "research",
    "manual",
    undefined,
    "on-device,consumer,research",
  ],
  [
    "teleai",
    "China Telecom TeleAI",
    "https://www.teleai.com.cn/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "foundation-model,cloud,to-g",
  ],
  [
    "china-mobile-jiutian",
    "China Mobile Jiutian",
    "https://jiutian.10086.cn/",
    "CN",
    "china-lab",
    1,
    "primary",
    "manual",
    undefined,
    "foundation-model,telecom,to-g",
  ],

  // Research, benchmarks and governance evidence.
  [
    "arxiv-ai",
    "arXiv cs.AI",
    "https://arxiv.org/list/cs.AI/recent",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "arxiv",
    "https://export.arxiv.org/api/query?search_query=cat%3Acs.AI&start=0&max_results=50&sortBy=submittedDate&sortOrder=descending",
    "paper,agent,reasoning",
  ],
  [
    "arxiv-cl",
    "arXiv cs.CL",
    "https://arxiv.org/list/cs.CL/recent",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "arxiv",
    "https://export.arxiv.org/api/query?search_query=cat%3Acs.CL&start=0&max_results=50&sortBy=submittedDate&sortOrder=descending",
    "paper,language-model",
  ],
  [
    "arxiv-lg",
    "arXiv cs.LG",
    "https://arxiv.org/list/cs.LG/recent",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "arxiv",
    "https://export.arxiv.org/api/query?search_query=cat%3Acs.LG&start=0&max_results=50&sortBy=submittedDate&sortOrder=descending",
    "paper,machine-learning",
  ],
  [
    "arxiv-ro",
    "arXiv cs.RO",
    "https://arxiv.org/list/cs.RO/recent",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "arxiv",
    "https://export.arxiv.org/api/query?search_query=cat%3Acs.RO&start=0&max_results=50&sortBy=submittedDate&sortOrder=descending",
    "paper,robotics",
  ],
  [
    "huggingface-papers",
    "Hugging Face Daily Papers",
    "https://huggingface.co/papers",
    "GLOBAL",
    "research-eval",
    2,
    "research",
    "html",
    undefined,
    "paper,community",
  ],
  [
    "stanford-hai",
    "Stanford HAI",
    "https://hai.stanford.edu/news",
    "US",
    "research-eval",
    1,
    "research",
    "rss",
    "https://hai.stanford.edu/news/rss.xml",
    "index,policy,research",
  ],
  [
    "stanford-crfm",
    "Stanford CRFM",
    "https://crfm.stanford.edu/",
    "US",
    "research-eval",
    1,
    "research",
    "html",
    undefined,
    "foundation-model,evaluation",
  ],
  [
    "helm",
    "HELM",
    "https://crfm.stanford.edu/helm/",
    "US",
    "research-eval",
    1,
    "research",
    "manual",
    undefined,
    "evaluation,benchmark",
  ],
  [
    "epoch-ai",
    "Epoch AI",
    "https://epoch.ai/blog",
    "GLOBAL",
    "research-eval",
    2,
    "research",
    "rss",
    "https://epoch.ai/blog/rss.xml",
    "compute,forecast,research",
  ],
  [
    "metr",
    "METR",
    "https://metr.org/blog/",
    "US",
    "research-eval",
    1,
    "research",
    "rss",
    "https://metr.org/blog/rss.xml",
    "agent,evaluation,safety",
  ],
  [
    "arc-prize",
    "ARC Prize",
    "https://arcprize.org/blog",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "rss",
    "https://arcprize.org/feed.xml",
    "agi,reasoning,benchmark",
  ],
  [
    "swe-bench",
    "SWE-bench",
    "https://www.swebench.com/",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "github",
    "https://github.com/SWE-bench/SWE-bench/releases.atom",
    "coding,agent,benchmark",
  ],
  [
    "lmsys",
    "LMSYS Org",
    "https://lmsys.org/blog/",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "rss",
    "https://lmsys.org/blog/index.xml",
    "evaluation,serving,open-source",
  ],
  [
    "lmarena",
    "LMArena",
    "https://lmarena.ai/blog",
    "GLOBAL",
    "research-eval",
    2,
    "research",
    "html",
    undefined,
    "evaluation,preference",
  ],
  [
    "artificial-analysis",
    "Artificial Analysis",
    "https://artificialanalysis.ai/",
    "GLOBAL",
    "research-eval",
    2,
    "research",
    "manual",
    undefined,
    "model,price,latency,benchmark",
  ],
  [
    "mlcommons",
    "MLCommons",
    "https://mlcommons.org/news/",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "rss",
    "https://mlcommons.org/feed/",
    "benchmark,infra,safety",
  ],
  [
    "opencompass",
    "OpenCompass",
    "https://opencompass.org.cn/",
    "CN",
    "research-eval",
    1,
    "research",
    "github",
    "https://github.com/open-compass/opencompass/releases.atom",
    "evaluation,china,open-source",
  ],
  [
    "modelscope",
    "ModelScope",
    "https://modelscope.cn/headlines",
    "CN",
    "research-eval",
    1,
    "research",
    "html",
    undefined,
    "model,open-source,china",
  ],
  [
    "cais",
    "Center for AI Safety",
    "https://www.safe.ai/blog",
    "US",
    "research-eval",
    2,
    "research",
    "html",
    undefined,
    "safety,research",
  ],
  [
    "apollo-research",
    "Apollo Research",
    "https://www.apolloresearch.ai/blog",
    "UK",
    "research-eval",
    2,
    "research",
    "html",
    undefined,
    "safety,evaluation,deception",
  ],
  [
    "redwood-research",
    "Redwood Research",
    "https://www.redwoodresearch.org/blog",
    "US",
    "research-eval",
    2,
    "research",
    "html",
    undefined,
    "alignment,safety",
  ],

  // Open-source model and infrastructure projects.
  [
    "huggingface",
    "Hugging Face",
    "https://huggingface.co/blog",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "rss",
    "https://huggingface.co/blog/feed.xml",
    "open-source,model,developer",
  ],
  [
    "transformers",
    "Transformers",
    "https://github.com/huggingface/transformers",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/huggingface/transformers/releases.atom",
    "model,library",
  ],
  [
    "vllm",
    "vLLM",
    "https://github.com/vllm-project/vllm",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/vllm-project/vllm/releases.atom",
    "serving,inference",
  ],
  [
    "llamacpp",
    "llama.cpp",
    "https://github.com/ggml-org/llama.cpp",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/ggml-org/llama.cpp/releases.atom",
    "local,inference",
  ],
  [
    "ollama",
    "Ollama",
    "https://github.com/ollama/ollama",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/ollama/ollama/releases.atom",
    "local,developer",
  ],
  [
    "mlx",
    "MLX",
    "https://github.com/ml-explore/mlx",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/ml-explore/mlx/releases.atom",
    "apple,on-device,inference",
  ],
  [
    "sglang",
    "SGLang",
    "https://github.com/sgl-project/sglang",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/sgl-project/sglang/releases.atom",
    "serving,agent",
  ],
  [
    "tensorrt-llm",
    "TensorRT-LLM",
    "https://github.com/NVIDIA/TensorRT-LLM",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/NVIDIA/TensorRT-LLM/releases.atom",
    "inference,nvidia",
  ],
  [
    "deepspeed",
    "DeepSpeed",
    "https://github.com/microsoft/DeepSpeed",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/microsoft/DeepSpeed/releases.atom",
    "training,inference",
  ],
  [
    "pytorch",
    "PyTorch",
    "https://pytorch.org/blog/",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "rss",
    "https://pytorch.org/feed.xml",
    "framework,training",
  ],
  [
    "jax",
    "JAX",
    "https://github.com/jax-ml/jax",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/jax-ml/jax/releases.atom",
    "framework,training",
  ],
  [
    "langchain",
    "LangChain",
    "https://blog.langchain.dev/",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "rss",
    "https://blog.langchain.dev/rss/",
    "agent,framework",
  ],
  [
    "llamaindex",
    "LlamaIndex",
    "https://www.llamaindex.ai/blog",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/run-llama/llama_index/releases.atom",
    "rag,agent",
  ],
  [
    "vercel-ai-sdk",
    "Vercel AI SDK",
    "https://github.com/vercel/ai",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/vercel/ai/releases.atom",
    "developer,frontend,agent",
  ],
  [
    "dify",
    "Dify",
    "https://github.com/langgenius/dify",
    "CN",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/langgenius/dify/releases.atom",
    "agent,workflow,china",
  ],
  [
    "ragflow",
    "RAGFlow",
    "https://github.com/infiniflow/ragflow",
    "CN",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/infiniflow/ragflow/releases.atom",
    "rag,agent,china",
  ],
  [
    "fastgpt",
    "FastGPT",
    "https://github.com/labring/FastGPT",
    "CN",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/labring/FastGPT/releases.atom",
    "rag,agent,china",
  ],
  [
    "open-webui",
    "Open WebUI",
    "https://github.com/open-webui/open-webui",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/open-webui/open-webui/releases.atom",
    "local,interface",
  ],
  [
    "aider",
    "Aider",
    "https://aider.chat/blog/",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "rss",
    "https://aider.chat/blog/index.xml",
    "coding,agent",
  ],
  [
    "continue",
    "Continue",
    "https://blog.continue.dev/",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "rss",
    "https://blog.continue.dev/rss/",
    "coding,agent",
  ],
  [
    "cline",
    "Cline",
    "https://github.com/cline/cline",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/cline/cline/releases.atom",
    "coding,agent",
  ],
  [
    "openhands",
    "OpenHands",
    "https://github.com/All-Hands-AI/OpenHands",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/All-Hands-AI/OpenHands/releases.atom",
    "coding,agent",
  ],
  [
    "browser-use",
    "Browser Use",
    "https://github.com/browser-use/browser-use",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/browser-use/browser-use/releases.atom",
    "browser,agent",
  ],
  [
    "stagehand",
    "Stagehand",
    "https://github.com/browserbase/stagehand",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/browserbase/stagehand/releases.atom",
    "browser,agent",
  ],
  [
    "playwright",
    "Playwright",
    "https://github.com/microsoft/playwright",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/microsoft/playwright/releases.atom",
    "browser,automation",
  ],

  // First-party release streams for SDKs, agents, model runtimes and data infrastructure.
  // These sources stay in shadow until they satisfy the 20-check / 7-day activation gate.
  [
    "openai-codex-releases",
    "OpenAI Codex Releases",
    "https://github.com/openai/codex",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/openai/codex/releases.atom",
    "coding,agent,openai",
  ],
  [
    "openai-python-releases",
    "OpenAI Python SDK Releases",
    "https://github.com/openai/openai-python",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/openai/openai-python/releases.atom",
    "sdk,api,openai",
  ],
  [
    "anthropic-python-releases",
    "Anthropic Python SDK Releases",
    "https://github.com/anthropics/anthropic-sdk-python",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/anthropics/anthropic-sdk-python/releases.atom",
    "sdk,api,anthropic",
  ],
  [
    "google-genai-python-releases",
    "Google Gen AI Python SDK Releases",
    "https://github.com/googleapis/python-genai",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/googleapis/python-genai/releases.atom",
    "sdk,api,gemini",
  ],
  [
    "autogen-releases",
    "Microsoft AutoGen Releases",
    "https://github.com/microsoft/autogen",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/microsoft/autogen/releases.atom",
    "agent,framework,microsoft",
  ],
  [
    "semantic-kernel-releases",
    "Semantic Kernel Releases",
    "https://github.com/microsoft/semantic-kernel",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/microsoft/semantic-kernel/releases.atom",
    "agent,framework,enterprise",
  ],
  [
    "langgraph-releases",
    "LangGraph Releases",
    "https://github.com/langchain-ai/langgraph",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/langchain-ai/langgraph/releases.atom",
    "agent,workflow,framework",
  ],
  [
    "crewai-releases",
    "CrewAI Releases",
    "https://github.com/crewAIInc/crewAI",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/crewAIInc/crewAI/releases.atom",
    "agent,multi-agent,framework",
  ],
  [
    "mcp-typescript-sdk-releases",
    "MCP TypeScript SDK Releases",
    "https://github.com/modelcontextprotocol/typescript-sdk",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/modelcontextprotocol/typescript-sdk/releases.atom",
    "mcp,protocol,sdk",
  ],
  [
    "mcp-python-sdk-releases",
    "MCP Python SDK Releases",
    "https://github.com/modelcontextprotocol/python-sdk",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/modelcontextprotocol/python-sdk/releases.atom",
    "mcp,protocol,sdk",
  ],
  [
    "litellm-releases",
    "LiteLLM Releases",
    "https://github.com/BerriAI/litellm",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/BerriAI/litellm/releases.atom",
    "gateway,model-routing,developer",
  ],
  [
    "promptfoo-releases",
    "Promptfoo Releases",
    "https://github.com/promptfoo/promptfoo",
    "GLOBAL",
    "research-eval",
    1,
    "primary",
    "github",
    "https://github.com/promptfoo/promptfoo/releases.atom",
    "evaluation,security,developer",
  ],
  [
    "langfuse-releases",
    "Langfuse Releases",
    "https://github.com/langfuse/langfuse",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/langfuse/langfuse/releases.atom",
    "observability,evaluation,agent",
  ],
  [
    "phoenix-releases",
    "Arize Phoenix Releases",
    "https://github.com/Arize-ai/phoenix",
    "GLOBAL",
    "research-eval",
    1,
    "primary",
    "github",
    "https://github.com/Arize-ai/phoenix/releases.atom",
    "observability,evaluation,rag",
  ],
  [
    "instructor-releases",
    "Instructor Releases",
    "https://github.com/instructor-ai/instructor",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/instructor-ai/instructor/releases.atom",
    "structured-output,sdk,developer",
  ],
  [
    "tgi-releases",
    "Text Generation Inference Releases",
    "https://github.com/huggingface/text-generation-inference",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/huggingface/text-generation-inference/releases.atom",
    "inference,serving,huggingface",
  ],
  [
    "diffusers-releases",
    "Diffusers Releases",
    "https://github.com/huggingface/diffusers",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/huggingface/diffusers/releases.atom",
    "image,video,multimodal",
  ],
  [
    "peft-releases",
    "PEFT Releases",
    "https://github.com/huggingface/peft",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/huggingface/peft/releases.atom",
    "training,fine-tuning,model",
  ],
  [
    "trl-releases",
    "TRL Releases",
    "https://github.com/huggingface/trl",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/huggingface/trl/releases.atom",
    "post-training,rlhf,model",
  ],
  [
    "torchtune-releases",
    "TorchTune Releases",
    "https://github.com/pytorch/torchtune",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/pytorch/torchtune/releases.atom",
    "training,fine-tuning,pytorch",
  ],
  [
    "nemo-releases",
    "NVIDIA NeMo Releases",
    "https://github.com/NVIDIA/NeMo",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/NVIDIA/NeMo/releases.atom",
    "training,inference,nvidia",
  ],
  [
    "nccl-releases",
    "NVIDIA NCCL Releases",
    "https://github.com/NVIDIA/nccl",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "github",
    "https://github.com/NVIDIA/nccl/releases.atom",
    "training,networking,gpu",
  ],
  [
    "triton-releases",
    "Triton Compiler Releases",
    "https://github.com/triton-lang/triton",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "github",
    "https://github.com/triton-lang/triton/releases.atom",
    "compiler,gpu,inference",
  ],
  [
    "flash-attention-releases",
    "FlashAttention Releases",
    "https://github.com/Dao-AILab/flash-attention",
    "GLOBAL",
    "open-source",
    1,
    "research",
    "github",
    "https://github.com/Dao-AILab/flash-attention/releases.atom",
    "attention,kernel,training",
  ],
  [
    "ray-releases",
    "Ray Releases",
    "https://github.com/ray-project/ray",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "github",
    "https://github.com/ray-project/ray/releases.atom",
    "distributed,training,serving",
  ],
  [
    "tvm-releases",
    "Apache TVM Releases",
    "https://github.com/apache/tvm",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "github",
    "https://github.com/apache/tvm/releases.atom",
    "compiler,inference,hardware",
  ],
  [
    "milvus-releases",
    "Milvus Releases",
    "https://github.com/milvus-io/milvus",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/milvus-io/milvus/releases.atom",
    "vector-database,rag,data",
  ],
  [
    "qdrant-releases",
    "Qdrant Releases",
    "https://github.com/qdrant/qdrant",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/qdrant/qdrant/releases.atom",
    "vector-database,rag,data",
  ],
  [
    "weaviate-releases",
    "Weaviate Releases",
    "https://github.com/weaviate/weaviate",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/weaviate/weaviate/releases.atom",
    "vector-database,rag,data",
  ],
  [
    "chroma-releases",
    "Chroma Releases",
    "https://github.com/chroma-core/chroma",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/chroma-core/chroma/releases.atom",
    "vector-database,rag,data",
  ],
  [
    "qwen-agent-releases",
    "Qwen-Agent Releases",
    "https://github.com/QwenLM/Qwen-Agent",
    "CN",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/QwenLM/Qwen-Agent/releases.atom",
    "agent,qwen,china",
  ],
  [
    "lmdeploy-releases",
    "LMDeploy Releases",
    "https://github.com/InternLM/lmdeploy",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/InternLM/lmdeploy/releases.atom",
    "serving,inference,china",
  ],
  [
    "xtuner-releases",
    "XTuner Releases",
    "https://github.com/InternLM/xtuner",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/InternLM/xtuner/releases.atom",
    "training,fine-tuning,china",
  ],
  [
    "ms-swift-releases",
    "MS-SWIFT Releases",
    "https://github.com/modelscope/ms-swift",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/modelscope/ms-swift/releases.atom",
    "training,inference,china",
  ],
  [
    "paddlenlp-releases",
    "PaddleNLP Releases",
    "https://github.com/PaddlePaddle/PaddleNLP",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/PaddlePaddle/PaddleNLP/releases.atom",
    "model,training,china",
  ],
  [
    "mnn-releases",
    "MNN Releases",
    "https://github.com/alibaba/MNN",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/alibaba/MNN/releases.atom",
    "on-device,inference,china",
  ],
  [
    "verl-releases",
    "VeRL Releases",
    "https://github.com/volcengine/verl",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/volcengine/verl/releases.atom",
    "post-training,rlhf,china",
  ],
  [
    "deer-flow-releases",
    "DeerFlow Releases",
    "https://github.com/bytedance/deer-flow",
    "CN",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/bytedance/deer-flow/releases.atom",
    "agent,research,china",
  ],
  [
    "lightrag-releases",
    "LightRAG Releases",
    "https://github.com/HKUDS/LightRAG",
    "CN",
    "agent-devtool",
    1,
    "research",
    "github",
    "https://github.com/HKUDS/LightRAG/releases.atom",
    "rag,knowledge-graph,china",
  ],
  [
    "openmanus-releases",
    "OpenManus Releases",
    "https://github.com/FoundationAgents/OpenManus",
    "CN",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/FoundationAgents/OpenManus/releases.atom",
    "agent,open-source,china",
  ],
  [
    "internvl-releases",
    "InternVL Releases",
    "https://github.com/OpenGVLab/InternVL",
    "CN",
    "open-source",
    1,
    "research",
    "github",
    "https://github.com/OpenGVLab/InternVL/releases.atom",
    "multimodal,model,china",
  ],
  [
    "cosyvoice-releases",
    "CosyVoice Releases",
    "https://github.com/FunAudioLLM/CosyVoice",
    "CN",
    "open-source",
    1,
    "research",
    "github",
    "https://github.com/FunAudioLLM/CosyVoice/releases.atom",
    "speech,audio,china",
  ],
  [
    "deepseek-v3-releases",
    "DeepSeek V3 Releases",
    "https://github.com/deepseek-ai/DeepSeek-V3",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/deepseek-ai/DeepSeek-V3/releases.atom",
    "model,reasoning,china",
  ],
  [
    "deepseek-r1-releases",
    "DeepSeek R1 Releases",
    "https://github.com/deepseek-ai/DeepSeek-R1",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/deepseek-ai/DeepSeek-R1/releases.atom",
    "model,reasoning,china",
  ],
  [
    "minicpm-v-releases",
    "MiniCPM-V Releases",
    "https://github.com/OpenBMB/MiniCPM-V",
    "CN",
    "open-source",
    1,
    "research",
    "github",
    "https://github.com/OpenBMB/MiniCPM-V/releases.atom",
    "multimodal,on-device,china",
  ],
  [
    "yi-releases",
    "Yi Model Releases",
    "https://github.com/01-ai/Yi",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/01-ai/Yi/releases.atom",
    "model,open-source,china",
  ],
  [
    "openai-node-releases",
    "OpenAI Node SDK Releases",
    "https://github.com/openai/openai-node",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/openai/openai-node/releases.atom",
    "sdk,api,openai",
  ],
  [
    "anthropic-typescript-releases",
    "Anthropic TypeScript SDK Releases",
    "https://github.com/anthropics/anthropic-sdk-typescript",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/anthropics/anthropic-sdk-typescript/releases.atom",
    "sdk,api,anthropic",
  ],
  [
    "google-genai-js-releases",
    "Google Gen AI JavaScript SDK Releases",
    "https://github.com/googleapis/js-genai",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/googleapis/js-genai/releases.atom",
    "sdk,api,gemini",
  ],
  [
    "markitdown-releases",
    "Microsoft MarkItDown Releases",
    "https://github.com/microsoft/markitdown",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/microsoft/markitdown/releases.atom",
    "document,ingestion,agent",
  ],
  [
    "langchain-releases",
    "LangChain Releases",
    "https://github.com/langchain-ai/langchain",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/langchain-ai/langchain/releases.atom",
    "agent,framework,developer",
  ],
  [
    "openlit-releases",
    "OpenLIT Releases",
    "https://github.com/openlit/openlit",
    "GLOBAL",
    "research-eval",
    1,
    "primary",
    "github",
    "https://github.com/openlit/openlit/releases.atom",
    "observability,evaluation,agent",
  ],
  [
    "onnxruntime-releases",
    "ONNX Runtime Releases",
    "https://github.com/microsoft/onnxruntime",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "github",
    "https://github.com/microsoft/onnxruntime/releases.atom",
    "inference,runtime,hardware",
  ],
  [
    "onnxruntime-genai-releases",
    "ONNX Runtime GenAI Releases",
    "https://github.com/microsoft/onnxruntime-genai",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/microsoft/onnxruntime-genai/releases.atom",
    "inference,generative-ai,on-device",
  ],
  [
    "tensorrt-releases",
    "NVIDIA TensorRT Releases",
    "https://github.com/NVIDIA/TensorRT",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "github",
    "https://github.com/NVIDIA/TensorRT/releases.atom",
    "inference,gpu,nvidia",
  ],
  [
    "cutlass-releases",
    "NVIDIA CUTLASS Releases",
    "https://github.com/NVIDIA/cutlass",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "github",
    "https://github.com/NVIDIA/cutlass/releases.atom",
    "kernel,gpu,nvidia",
  ],
  [
    "kubeflow-trainer-releases",
    "Kubeflow Trainer Releases",
    "https://github.com/kubeflow/trainer",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "github",
    "https://github.com/kubeflow/trainer/releases.atom",
    "training,kubernetes,platform",
  ],
  [
    "whispercpp-releases",
    "whisper.cpp Releases",
    "https://github.com/ggml-org/whisper.cpp",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/ggml-org/whisper.cpp/releases.atom",
    "speech,on-device,inference",
  ],
  [
    "mineru-releases",
    "MinerU Releases",
    "https://github.com/opendatalab/MinerU",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/opendatalab/MinerU/releases.atom",
    "document,multimodal,china",
  ],
  [
    "paddleocr-releases",
    "PaddleOCR Releases",
    "https://github.com/PaddlePaddle/PaddleOCR",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/PaddlePaddle/PaddleOCR/releases.atom",
    "document,multimodal,china",
  ],
  [
    "ncnn-releases",
    "Tencent NCNN Releases",
    "https://github.com/Tencent/ncnn",
    "CN",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/Tencent/ncnn/releases.atom",
    "on-device,inference,china",
  ],
  [
    "safetensors-releases",
    "Safetensors Releases",
    "https://github.com/huggingface/safetensors",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/huggingface/safetensors/releases.atom",
    "model-format,security,huggingface",
  ],
  [
    "tokenizers-releases",
    "Hugging Face Tokenizers Releases",
    "https://github.com/huggingface/tokenizers",
    "GLOBAL",
    "open-source",
    1,
    "primary",
    "github",
    "https://github.com/huggingface/tokenizers/releases.atom",
    "tokenization,model,huggingface",
  ],

  // Coding products, robotics and embodied intelligence.
  [
    "cursor",
    "Cursor Changelog",
    "https://www.cursor.com/changelog",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "html",
    undefined,
    "coding,product",
  ],
  [
    "windsurf",
    "Windsurf Editor",
    "https://windsurf.com/changelog",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "html",
    undefined,
    "coding,product",
  ],
  [
    "github-copilot",
    "GitHub Copilot Changelog",
    "https://github.blog/changelog/label/copilot/",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "rss",
    "https://github.blog/changelog/label/copilot/feed/",
    "coding,product",
  ],
  [
    "open-robotics",
    "Open Robotics",
    "https://www.openrobotics.org/blog",
    "GLOBAL",
    "robotics",
    1,
    "primary",
    "rss",
    "https://www.openrobotics.org/blog?format=rss",
    "robotics,open-source",
  ],
  [
    "ros-discourse",
    "ROS Discourse",
    "https://discourse.ros.org/",
    "GLOBAL",
    "robotics",
    3,
    "heat",
    "rss",
    "https://discourse.ros.org/latest.rss",
    "robotics,community",
  ],
  [
    "physical-intelligence",
    "Physical Intelligence",
    "https://www.physicalintelligence.company/blog",
    "US",
    "robotics",
    1,
    "primary",
    "html",
    undefined,
    "robotics,vla,research",
  ],
  [
    "figure-ai",
    "Figure AI",
    "https://www.figure.ai/news",
    "US",
    "robotics",
    1,
    "primary",
    "html",
    undefined,
    "humanoid,robotics",
  ],
  [
    "1x",
    "1X",
    "https://www.1x.tech/discover",
    "GLOBAL",
    "robotics",
    1,
    "primary",
    "html",
    undefined,
    "humanoid,robotics",
  ],
  [
    "boston-dynamics",
    "Boston Dynamics",
    "https://bostondynamics.com/blog/",
    "US",
    "robotics",
    1,
    "primary",
    "rss",
    "https://bostondynamics.com/blog/feed/",
    "robotics,humanoid",
  ],
  [
    "agility-robotics",
    "Agility Robotics",
    "https://www.agilityrobotics.com/news",
    "US",
    "robotics",
    1,
    "primary",
    "html",
    undefined,
    "humanoid,enterprise",
  ],
  [
    "unitree",
    "Unitree Robotics",
    "https://www.unitree.com/news",
    "CN",
    "robotics",
    1,
    "primary",
    "html",
    undefined,
    "humanoid,robotics,china",
  ],

  // Chips, cloud and model infrastructure.
  [
    "nvidia-blog-ai",
    "NVIDIA AI Blog",
    "https://blogs.nvidia.com/blog/category/deep-learning/",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "rss",
    "https://blogs.nvidia.com/blog/category/deep-learning/feed/",
    "chip,infra,enterprise",
  ],
  [
    "amd-ai",
    "AMD AI",
    "https://www.amd.com/en/newsroom.html",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "html",
    undefined,
    "chip,infra",
  ],
  [
    "intel-ai",
    "Intel AI",
    "https://community.intel.com/t5/Blogs/Tech-Innovation/Artificial-Intelligence-AI/bg-p/blog-ai",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "rss",
    "https://community.intel.com/t5/Blogs/Tech-Innovation/Artificial-Intelligence-AI/bg-p/blog-ai/rss",
    "chip,infra",
  ],
  [
    "cerebras",
    "Cerebras",
    "https://www.cerebras.ai/blog",
    "US",
    "infra-chip-cloud",
    1,
    "primary",
    "html",
    undefined,
    "chip,training,inference",
  ],
  [
    "groq",
    "Groq",
    "https://groq.com/blog",
    "US",
    "infra-chip-cloud",
    1,
    "primary",
    "html",
    undefined,
    "chip,inference",
  ],
  [
    "coreweave",
    "CoreWeave",
    "https://www.coreweave.com/blog",
    "US",
    "infra-chip-cloud",
    1,
    "primary",
    "rss",
    "https://www.coreweave.com/blog/rss.xml",
    "cloud,gpu,capital",
  ],
  [
    "aws-ml",
    "AWS Machine Learning Blog",
    "https://aws.amazon.com/blogs/machine-learning/",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "rss",
    "https://aws.amazon.com/blogs/machine-learning/feed/",
    "cloud,enterprise,agent",
  ],
  [
    "azure-ai",
    "Azure AI Blog",
    "https://azure.microsoft.com/en-us/blog/category/ai-machine-learning/",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "rss",
    "https://azure.microsoft.com/en-us/blog/category/ai-machine-learning/feed/",
    "cloud,enterprise",
  ],
  [
    "google-cloud-ai",
    "Google Cloud AI",
    "https://cloud.google.com/blog/products/ai-machine-learning",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "rss",
    "https://cloud.google.com/blog/products/ai-machine-learning/rss",
    "cloud,enterprise",
  ],
  [
    "cloudflare-ai",
    "Cloudflare AI",
    "https://blog.cloudflare.com/tag/ai/",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "rss",
    "https://blog.cloudflare.com/tag/ai/rss/",
    "edge,inference,developer",
  ],
  [
    "together-ai",
    "Together AI",
    "https://www.together.ai/blog",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "rss",
    "https://www.together.ai/blog/rss.xml",
    "cloud,inference,open-model",
  ],
  [
    "fireworks-ai",
    "Fireworks AI",
    "https://fireworks.ai/blog",
    "GLOBAL",
    "infra-chip-cloud",
    1,
    "primary",
    "html",
    undefined,
    "cloud,inference",
  ],

  // Capital, strategy, experts and professional media.
  [
    "a16z-ai",
    "a16z AI",
    "https://a16z.com/ai/",
    "US",
    "capital-business",
    2,
    "expert",
    "manual",
    undefined,
    "investment,market,product",
  ],
  [
    "bessemer-ai",
    "Bessemer Venture Partners AI",
    "https://www.bvp.com/atlas",
    "US",
    "capital-business",
    2,
    "expert",
    "manual",
    undefined,
    "investment,cloud,enterprise",
  ],
  [
    "nfx",
    "NFX",
    "https://www.nfx.com/library",
    "US",
    "capital-business",
    2,
    "expert",
    "manual",
    undefined,
    "startup,network-effects",
  ],
  [
    "greylock",
    "Greylock",
    "https://greylock.com/greymatter/",
    "US",
    "capital-business",
    2,
    "expert",
    "rss",
    "https://greylock.com/feed/",
    "investment,enterprise,consumer",
  ],
  [
    "lightspeed",
    "Lightspeed",
    "https://lsvp.com/stories/",
    "GLOBAL",
    "capital-business",
    2,
    "expert",
    "html",
    undefined,
    "investment,startup",
  ],
  [
    "index-ventures",
    "Index Ventures",
    "https://www.indexventures.com/perspectives/",
    "GLOBAL",
    "capital-business",
    2,
    "expert",
    "html",
    undefined,
    "investment,startup",
  ],
  [
    "karpathy",
    "Andrej Karpathy",
    "https://karpathy.ai/",
    "GLOBAL",
    "expert",
    3,
    "expert",
    "social",
    undefined,
    "education,model,agent",
  ],
  [
    "baoyu",
    "宝玉的分享",
    "https://baoyu.io/",
    "CN",
    "expert",
    2,
    "expert",
    "rss",
    "https://baoyu.io/feed.xml",
    "ai-coding,prompt-engineering,product,china",
  ],
  [
    "mu-li-blog",
    "李沐 · Mu's Blog",
    "https://mli.github.io/",
    "CN",
    "expert",
    2,
    "expert",
    "rss",
    "https://mli.github.io/atom.xml",
    "deep-learning,education,systems,china",
  ],
  [
    "lilian-weng",
    "Lilian Weng · Lil'Log",
    "https://lilianweng.github.io/",
    "GLOBAL",
    "expert",
    2,
    "expert",
    "rss",
    "https://lilianweng.github.io/index.xml",
    "agent,alignment,research",
  ],
  [
    "eugene-yan",
    "Eugene Yan",
    "https://eugeneyan.com/",
    "GLOBAL",
    "expert",
    2,
    "expert",
    "rss",
    "https://eugeneyan.com/rss/",
    "ml-systems,ai-product,recommendation",
  ],
  [
    "simon-willison",
    "Simon Willison",
    "https://simonwillison.net/",
    "GLOBAL",
    "expert",
    3,
    "expert",
    "rss",
    "https://simonwillison.net/atom/everything/",
    "llm,developer,product",
  ],
  [
    "chip-huyen",
    "Chip Huyen",
    "https://huyenchip.com/blog/",
    "GLOBAL",
    "expert",
    3,
    "expert",
    "rss",
    "https://huyenchip.com/feed.xml",
    "ml-systems,product",
  ],
  [
    "sebastian-raschka",
    "Sebastian Raschka",
    "https://magazine.sebastianraschka.com/",
    "GLOBAL",
    "expert",
    3,
    "expert",
    "rss",
    "https://magazine.sebastianraschka.com/feed",
    "research,education,open-model",
  ],
  [
    "ethan-mollick",
    "One Useful Thing",
    "https://www.oneusefulthing.org/",
    "GLOBAL",
    "expert",
    3,
    "expert",
    "rss",
    "https://www.oneusefulthing.org/feed",
    "work,education,adoption",
  ],
  [
    "interconnects",
    "Interconnects",
    "https://www.interconnects.ai/",
    "GLOBAL",
    "expert",
    3,
    "expert",
    "rss",
    "https://www.interconnects.ai/feed",
    "open-model,research,policy",
  ],
  [
    "import-ai",
    "Import AI",
    "https://importai.substack.com/",
    "GLOBAL",
    "expert",
    3,
    "expert",
    "rss",
    "https://importai.substack.com/feed",
    "research,policy,industry",
  ],
  [
    "semianalysis",
    "SemiAnalysis",
    "https://semianalysis.com/",
    "GLOBAL",
    "expert",
    2,
    "expert",
    "rss",
    "https://semianalysis.com/feed/",
    "chip,infra,economics",
  ],
  [
    "latent-space",
    "Latent Space",
    "https://www.latent.space/",
    "GLOBAL",
    "expert",
    3,
    "expert",
    "rss",
    "https://www.latent.space/feed",
    "developer,agent,startup",
  ],
  [
    "reuters-ai",
    "Reuters AI",
    "https://www.reuters.com/technology/artificial-intelligence/",
    "GLOBAL",
    "media",
    2,
    "media",
    "manual",
    undefined,
    "business,policy,fact",
  ],
  [
    "ft-ai",
    "Financial Times AI",
    "https://www.ft.com/artificial-intelligence",
    "GLOBAL",
    "media",
    2,
    "media",
    "manual",
    undefined,
    "business,capital,policy",
  ],
  [
    "mit-tech-review-ai",
    "MIT Technology Review AI",
    "https://www.technologyreview.com/topic/artificial-intelligence/",
    "GLOBAL",
    "media",
    2,
    "media",
    "rss",
    "https://www.technologyreview.com/topic/artificial-intelligence/feed",
    "technology,policy,industry",
  ],
  [
    "the-information-ai",
    "The Information AI",
    "https://www.theinformation.com/artificial-intelligence",
    "US",
    "media",
    2,
    "media",
    "manual",
    undefined,
    "business,capital,company",
  ],
  [
    "techcrunch-ai",
    "TechCrunch AI",
    "https://techcrunch.com/category/artificial-intelligence/",
    "GLOBAL",
    "media",
    2,
    "media",
    "rss",
    "https://techcrunch.com/category/artificial-intelligence/feed/",
    "startup,funding,product",
  ],
  [
    "36kr-ai",
    "36Kr AI",
    "https://36kr.com/information/AI/",
    "CN",
    "media",
    2,
    "media",
    "html",
    undefined,
    "china,startup,funding",
  ],
  [
    "latepost",
    "LatePost",
    "https://www.latepost.com/",
    "CN",
    "media",
    2,
    "media",
    "manual",
    undefined,
    "china,business,company",
  ],
  [
    "infoq-cn-ai",
    "InfoQ China AI",
    "https://www.infoq.cn/topic/AI",
    "CN",
    "media",
    2,
    "media",
    "rss",
    "https://www.infoq.cn/feed",
    "china,developer,enterprise",
  ],

  // Policy and institutional originals.
  [
    "nist-ai",
    "NIST AI",
    "https://www.nist.gov/artificial-intelligence",
    "US",
    "policy",
    1,
    "policy",
    "rss",
    "https://www.nist.gov/news-events/cybersecurity/rss.xml",
    "standards,safety,governance",
  ],
  [
    "white-house-ostp",
    "White House OSTP",
    "https://www.whitehouse.gov/ostp/",
    "US",
    "policy",
    1,
    "policy",
    "manual",
    undefined,
    "policy,science,governance",
  ],
  [
    "us-caisi",
    "US CAISI",
    "https://www.nist.gov/caisi",
    "US",
    "policy",
    1,
    "policy",
    "html",
    undefined,
    "safety,evaluation,policy",
  ],
  [
    "uk-aisi",
    "UK AI Security Institute",
    "https://www.aisi.gov.uk/blog",
    "UK",
    "policy",
    1,
    "policy",
    "rss",
    "https://www.aisi.gov.uk/blog/rss.xml",
    "safety,evaluation,policy",
  ],
  [
    "eu-ai-office",
    "European AI Office",
    "https://digital-strategy.ec.europa.eu/en/policies/ai-office",
    "EU",
    "policy",
    1,
    "policy",
    "rss",
    "https://digital-strategy.ec.europa.eu/en/node/10634/rss_en",
    "regulation,policy,eu",
  ],
  [
    "oecd-ai",
    "OECD.AI",
    "https://oecd.ai/en/wonk",
    "GLOBAL",
    "policy",
    1,
    "policy",
    "html",
    undefined,
    "policy,data,governance",
  ],
  [
    "cac-ai",
    "Cyberspace Administration of China",
    "https://www.cac.gov.cn/",
    "CN",
    "policy",
    1,
    "policy",
    "manual",
    undefined,
    "china,regulation,filing",
  ],
  [
    "miit-ai",
    "MIIT",
    "https://www.miit.gov.cn/",
    "CN",
    "policy",
    1,
    "policy",
    "rss",
    "https://www.miit.gov.cn/search-front-server/api/search/info",
    "china,industry,policy",
  ],

  // Community, social heat and aggregators. Never sole factual evidence.
  [
    "hackernews-ai",
    "Hacker News · AI",
    "https://news.ycombinator.com/",
    "GLOBAL",
    "community-heat",
    4,
    "heat",
    "rss",
    "https://hnrss.org/newest?q=AI",
    "developer,startup,heat",
  ],
  [
    "reddit-ml",
    "Reddit r/MachineLearning",
    "https://www.reddit.com/r/MachineLearning/",
    "GLOBAL",
    "community-heat",
    4,
    "heat",
    "rss",
    "https://www.reddit.com/r/MachineLearning/.rss",
    "research,community,heat",
  ],
  [
    "reddit-localllama",
    "Reddit r/LocalLLaMA",
    "https://www.reddit.com/r/LocalLLaMA/",
    "GLOBAL",
    "community-heat",
    4,
    "heat",
    "rss",
    "https://www.reddit.com/r/LocalLLaMA/.rss",
    "open-model,community,heat",
  ],
  [
    "github-trending-ai",
    "GitHub Trending AI",
    "https://github.com/trending?since=daily",
    "GLOBAL",
    "community-heat",
    4,
    "heat",
    "html",
    undefined,
    "open-source,developer,heat",
  ],
  [
    "product-hunt-ai",
    "Product Hunt AI",
    "https://www.producthunt.com/topics/artificial-intelligence",
    "GLOBAL",
    "community-heat",
    4,
    "heat",
    "rss",
    "https://www.producthunt.com/feed",
    "product,startup,heat",
  ],
  [
    "linux-do-ai",
    "LINUX DO AI",
    "https://linux.do/tag/ai",
    "CN",
    "community-heat",
    4,
    "heat",
    "rss",
    "https://linux.do/tag/ai.rss",
    "china,developer,heat",
  ],
  [
    "v2ex-ai",
    "V2EX AI",
    "https://www.v2ex.com/go/ai",
    "CN",
    "community-heat",
    4,
    "heat",
    "rss",
    "https://www.v2ex.com/feed/ai.xml",
    "china,developer,heat",
  ],
  [
    "weibo-ai",
    "Weibo AI Signal",
    "https://s.weibo.com/weibo?q=AI",
    "CN",
    "community-heat",
    4,
    "heat",
    "social",
    undefined,
    "china,social,heat",
  ],
  [
    "zhihu-ai",
    "Zhihu AI Signal",
    "https://www.zhihu.com/topic/19551275/hot",
    "CN",
    "community-heat",
    4,
    "heat",
    "social",
    undefined,
    "china,opinion,heat",
  ],
  [
    "bilibili-ai",
    "Bilibili AI Signal",
    "https://search.bilibili.com/all?keyword=AI",
    "CN",
    "community-heat",
    4,
    "heat",
    "social",
    undefined,
    "china,video,heat",
  ],
  [
    "youtube-ai",
    "YouTube AI Signal",
    "https://www.youtube.com/results?search_query=artificial+intelligence",
    "GLOBAL",
    "community-heat",
    4,
    "heat",
    "social",
    undefined,
    "video,creator,heat",
  ],
  [
    "x-ai",
    "X AI Signal",
    "https://x.com/i/topics/847894353766334464",
    "GLOBAL",
    "community-heat",
    4,
    "heat",
    "social",
    undefined,
    "social,expert,heat",
  ],
  [
    "linkedin-ai-experts",
    "LinkedIn AI Expert Signal",
    "https://www.linkedin.com/",
    "GLOBAL",
    "community-heat",
    4,
    "heat",
    "social",
    undefined,
    "social,expert,enterprise,heat",
  ],
  [
    "jike-ai-experts",
    "即刻 AI KOL Signal",
    "https://web.okjike.com/",
    "CN",
    "community-heat",
    4,
    "heat",
    "social",
    undefined,
    "china,social,expert,product,heat",
  ],

  // First-party publishers and pricing baselines discovered behind aggregators.
  [
    "google-research",
    "Google Research",
    "https://research.google/blog/",
    "GLOBAL",
    "research-eval",
    1,
    "research",
    "rss",
    "https://research.google/blog/rss/",
    "research,paper,google",
  ],
  [
    "google-developers",
    "Google Developers Blog",
    "https://developers.googleblog.com/",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "rss",
    "https://developers.googleblog.com/feeds/posts/default",
    "developer,gemini,api",
  ],
  [
    "thinking-machines",
    "Thinking Machines Lab",
    "https://thinkingmachines.ai/blog/",
    "US",
    "frontier-lab",
    1,
    "primary",
    "html",
    undefined,
    "frontier-model,research,infra",
  ],
  [
    "openrouter",
    "OpenRouter",
    "https://openrouter.ai/announcements",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "html",
    undefined,
    "api,routing,model-economics",
  ],
  [
    "bair",
    "Berkeley AI Research",
    "https://bair.berkeley.edu/blog/",
    "US",
    "research-eval",
    1,
    "research",
    "rss",
    "https://bair.berkeley.edu/blog/feed.xml",
    "research,paper,academic",
  ],
  [
    "claude-code-releases",
    "Claude Code Releases",
    "https://github.com/anthropics/claude-code/releases",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/anthropics/claude-code/releases.atom",
    "coding-agent,release,developer",
  ],
  [
    "a2a-protocol-releases",
    "A2A Protocol Releases",
    "https://github.com/a2aproject/A2A",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "github",
    "https://github.com/a2aproject/A2A/releases.atom",
    "agent2agent,a2a-protocol,sdk,protocol,enterprise",
  ],
  [
    "lovable-changelog",
    "Lovable Changelog",
    "https://docs.lovable.dev/changelog",
    "GLOBAL",
    "agent-devtool",
    1,
    "primary",
    "rss",
    "https://docs.lovable.dev/changelog/rss.xml",
    "lovable,ai-coding,agent,product,enterprise",
  ],
  [
    "tom-tunguz",
    "Tom Tunguz",
    "https://tomtunguz.com/",
    "US",
    "expert",
    2,
    "expert",
    "rss",
    "https://tomtunguz.com/index.xml",
    "venture,saas,ai-business",
  ],
  [
    "ars-technica-ai",
    "Ars Technica AI",
    "https://arstechnica.com/ai/",
    "US",
    "media",
    2,
    "media",
    "rss",
    "https://feeds.arstechnica.com/arstechnica/technology-lab",
    "technology,ai,media",
  ],
  [
    "the-decoder",
    "The Decoder",
    "https://the-decoder.com/",
    "EU",
    "media",
    2,
    "media",
    "rss",
    "https://the-decoder.com/feed/",
    "ai,media,research",
  ],
  [
    "the-verge-ai",
    "The Verge AI",
    "https://www.theverge.com/ai-artificial-intelligence",
    "US",
    "media",
    2,
    "media",
    "rss",
    "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    "ai,product,media",
  ],
  [
    "ithome-ai",
    "IT之家 AI",
    "https://www.ithome.com/tag/ai/",
    "CN",
    "media",
    2,
    "media",
    "html",
    undefined,
    "china,ai,media",
  ],
  [
    "marktechpost",
    "MarkTechPost",
    "https://www.marktechpost.com/",
    "GLOBAL",
    "media",
    3,
    "media",
    "rss",
    "https://www.marktechpost.com/feed/",
    "research,ai,media",
  ],
  [
    "apple-app-store-ai-pricing",
    "Apple App Store AI Subscriptions",
    "https://apps.apple.com/",
    "GLOBAL",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "subscription,regional-price,consumer",
  ],
  [
    "openai-pricing",
    "OpenAI Pricing",
    "https://openai.com/api/pricing/",
    "GLOBAL",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,subscription,pricing",
  ],
  [
    "anthropic-pricing",
    "Anthropic Pricing",
    "https://www.anthropic.com/pricing",
    "GLOBAL",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,subscription,pricing",
  ],
  [
    "google-gemini-pricing",
    "Google Gemini API Pricing",
    "https://ai.google.dev/gemini-api/docs/pricing",
    "GLOBAL",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,gemini,pricing",
  ],
  [
    "xai-pricing",
    "xAI API Pricing",
    "https://docs.x.ai/docs/models",
    "GLOBAL",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,grok,pricing",
  ],
  [
    "deepseek-pricing",
    "DeepSeek API Pricing",
    "https://api-docs.deepseek.com/quick_start/pricing",
    "CN",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,china,pricing",
  ],
  [
    "qwen-pricing",
    "Alibaba Cloud Model Studio Pricing",
    "https://www.alibabacloud.com/help/en/model-studio/model-pricing",
    "CN",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,qwen,china,pricing",
  ],
  [
    "kimi-pricing",
    "Moonshot AI Pricing",
    "https://platform.moonshot.cn/docs/pricing/chat",
    "CN",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,kimi,china,pricing",
  ],
  [
    "zhipu-pricing",
    "Zhipu AI Pricing",
    "https://open.bigmodel.cn/pricing",
    "CN",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,glm,china,pricing",
  ],
  [
    "minimax-pricing",
    "MiniMax Pricing",
    "https://platform.minimaxi.com/document/Price",
    "CN",
    "model-economics",
    1,
    "primary",
    "manual",
    undefined,
    "api,minimax,china,pricing",
  ],
  [
    "frankfurter-fx",
    "Frankfurter FX",
    "https://www.frankfurter.app/",
    "GLOBAL",
    "model-economics",
    1,
    "research",
    "manual",
    undefined,
    "fx,normalization,pricing",
  ],
  [
    "open-er-api-fx",
    "ExchangeRate-API Open Access",
    "https://www.exchangerate-api.com/docs/free",
    "GLOBAL",
    "model-economics",
    2,
    "research",
    "manual",
    undefined,
    "fx,normalization,pricing",
  ],
  [
    "aihot",
    "AI HOT",
    "https://aihot.virxact.com",
    "CN",
    "aggregator",
    2,
    "aggregator",
    "api",
    "https://aihot.virxact.com/api/public/items",
    "china,aggregator,heat",
  ],
  [
    "huggingnews",
    "HuggingNews",
    "https://huggingnews.com",
    "GLOBAL",
    "aggregator",
    3,
    "aggregator",
    "html",
    undefined,
    "x,aggregator,heat",
  ],
  [
    "tldr-ai",
    "TLDR AI",
    "https://tldr.tech/ai",
    "GLOBAL",
    "aggregator",
    3,
    "aggregator",
    "manual",
    undefined,
    "newsletter,aggregator",
  ],
  [
    "alphasignal",
    "AlphaSignal",
    "https://alphasignal.ai/",
    "GLOBAL",
    "aggregator",
    3,
    "aggregator",
    "manual",
    undefined,
    "newsletter,research,aggregator",
  ],
];

const enabled = new Set([
  "aihot",
  "openai",
  "deepmind",
  "huggingface",
  "arxiv-ai",
  "hackernews-ai",
]);
const authorityByTier = { 1: 92, 2: 78, 3: 66, 4: 45 } as const;

const identities: Record<string, { identityHosts?: string[]; socialHandles?: string[] }> = {
  openai: { identityHosts: ["openai.com"], socialHandles: ["openai"] },
  anthropic: { identityHosts: ["anthropic.com"], socialHandles: ["anthropicai"] },
  deepmind: { identityHosts: ["deepmind.google"], socialHandles: ["googledeepmind"] },
  "google-ai": { identityHosts: ["blog.google"], socialHandles: ["googleai", "geminiapp"] },
  "google-research": { identityHosts: ["research.google"], socialHandles: ["googleresearch"] },
  "google-developers": { identityHosts: ["developers.googleblog.com"] },
  "meta-ai": { identityHosts: ["ai.meta.com"], socialHandles: ["aiatmeta"] },
  xai: { identityHosts: ["x.ai"], socialHandles: ["xai", "grok"] },
  mistral: { identityHosts: ["mistral.ai"], socialHandles: ["mistralai"] },
  openrouter: { identityHosts: ["openrouter.ai"], socialHandles: ["openrouter"] },
  perplexity: { identityHosts: ["perplexity.ai"], socialHandles: ["perplexity_ai"] },
  "thinking-machines": { identityHosts: ["thinkingmachines.ai"] },
  bair: { identityHosts: ["bair.berkeley.edu"] },
  "tom-tunguz": { identityHosts: ["tomtunguz.com"], socialHandles: ["ttunguz"] },
  karpathy: { identityHosts: ["karpathy.ai"], socialHandles: ["karpathy"] },
  "simon-willison": { identityHosts: ["simonwillison.net"], socialHandles: ["simonw"] },
  "chip-huyen": { identityHosts: ["huyenchip.com"], socialHandles: ["chipro"] },
  "lilian-weng": { identityHosts: ["lilianweng.github.io"], socialHandles: ["lilianweng"] },
  "eugene-yan": { identityHosts: ["eugeneyan.com"], socialHandles: ["eugeneyan"] },
  interconnects: { identityHosts: ["interconnects.ai"], socialHandles: ["natolambert"] },
  "latent-space": { identityHosts: ["latent.space"], socialHandles: ["swyx"] },
  baoyu: { identityHosts: ["baoyu.io", "github.com"], socialHandles: ["dotey"] },
  "mu-li-blog": { identityHosts: ["mli.github.io", "github.com"], socialHandles: ["mli"] },
  "ars-technica-ai": { identityHosts: ["arstechnica.com"] },
  "the-decoder": { identityHosts: ["the-decoder.com"] },
  "the-verge-ai": { identityHosts: ["theverge.com"] },
  "ithome-ai": { identityHosts: ["ithome.com"] },
  marktechpost: { identityHosts: ["marktechpost.com"] },
};

const builtInSources: CatalogSource[] = rows.map(
  ([slug, name, homepageUrl, region, category, tier, role, acquisition, endpoint, topics]) => ({
    slug,
    name,
    homepageUrl,
    endpoint: endpoint ?? homepageUrl,
    adapter:
      acquisition === "rss" || acquisition === "arxiv"
        ? "rss"
        : acquisition === "api"
          ? slug === "aihot"
            ? "aihot"
            : "generic-api"
          : acquisition === "github"
            ? "github-releases"
            : acquisition === "html" && slug === "huggingnews"
              ? "huggingnews"
              : acquisition === "html"
                ? "web-scraper"
                : "manual",
    tier,
    role,
    region,
    language: region === "CN" ? "zh-CN" : "en",
    authorityScore: authorityByTier[tier],
    qualityScore: Math.max(35, authorityByTier[tier] - (role === "aggregator" ? 8 : 0)),
    enabled: enabled.has(slug),
    lifecycleStatus: enabled.has(slug) ? "active" : "shadow",
    category,
    acquisition,
    topics: (topics ?? category).split(","),
    maintenanceStatus: enabled.has(slug)
      ? "ready"
      : acquisition === "rss" ||
          acquisition === "api" ||
          acquisition === "arxiv" ||
          acquisition === "github"
        ? "candidate"
        : acquisition === "social"
          ? "restricted"
          : "manual",
    cadence: tier === 1 ? "6h" : tier === 2 ? "12h" : "24h",
    licenseNote:
      acquisition === "social"
        ? "Discovery metadata only; obey platform access policy and never bypass login or anti-bot controls."
        : "Metadata and provenance only; verify robots, feed terms and attribution before activation.",
    ...identities[slug],
  }),
);

const supplementalOfficialSources: CatalogSource[] = [
  officialSupplement(
    "fred",
    "Federal Reserve Economic Data (FRED)",
    "https://fred.stlouisfed.org/docs/api/fred/",
    "https://api.stlouisfed.org/fred/series/observations",
    "US",
    "policy",
    "api",
    ["macro", "growth", "inflation", "labor", "liquidity", "release-calendar"],
    "candidate",
    "daily",
    "Official Federal Reserve Bank of St. Louis API; runtime API keys must never enter snapshots.",
  ),
  officialSupplement(
    "alfred",
    "Archival FRED (ALFRED)",
    "https://alfred.stlouisfed.org/",
    "https://api.stlouisfed.org/fred/series/observations",
    "US",
    "policy",
    "api",
    ["macro", "vintage", "revision", "point-in-time"],
    "candidate",
    "daily",
    "Official vintage observations accessed through FRED realtime fields; preserve release dates and revisions.",
  ),
  officialSupplement(
    "imf-weo",
    "IMF World Economic Outlook Database",
    "https://data.imf.org/en/datasets/IMF.RES:WEO",
    "https://data.imf.org/en/datasets/IMF.RES:WEO",
    "GLOBAL",
    "policy",
    "manual",
    ["macro", "growth", "inflation", "fiscal", "trade", "forecast"],
    "manual",
    "quarterly",
    "Official IMF dataset; retain edition, country, unit and forecast-vs-actual provenance.",
  ),
  officialSupplement(
    "bis-credit-gaps",
    "BIS Credit-to-GDP Gaps",
    "https://data.bis.org/topics/CREDIT_GAPS",
    "https://stats.bis.org/api/v1/data/WS_CREDIT_GAP/",
    "GLOBAL",
    "policy",
    "api",
    ["macro", "credit", "financial-cycle", "systemic-risk"],
    "candidate",
    "quarterly",
    "Official BIS data; credit gaps are contextual warning signals and must not be treated as deterministic forecasts.",
  ),
  officialSupplement(
    "bls-public-data",
    "U.S. Bureau of Labor Statistics Public Data",
    "https://www.bls.gov/bls/api_features.htm",
    "https://api.bls.gov/publicAPI/v2/timeseries/data/",
    "US",
    "policy",
    "api",
    ["macro", "cpi", "employment", "wages", "jolts"],
    "candidate",
    "monthly",
    "Official public API; obey documented request quotas and preserve series identifiers.",
  ),
  officialSupplement(
    "bea-api",
    "U.S. Bureau of Economic Analysis API",
    "https://apps.bea.gov/api/signup/",
    "https://apps.bea.gov/api/data/",
    "US",
    "policy",
    "api",
    ["macro", "gdp", "pce", "income", "trade"],
    "candidate",
    "monthly",
    "Official BEA API; runtime API keys remain private and public output is limited to normalized observations.",
  ),
  officialSupplement(
    "us-treasury-fiscal-data",
    "U.S. Treasury Fiscal Data",
    "https://fiscaldata.treasury.gov/api-documentation/",
    "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/",
    "US",
    "policy",
    "api",
    ["macro", "rates", "debt", "fiscal", "cash-balance"],
    "candidate",
    "daily",
    "Official U.S. Treasury API; publish normalized factual fields with dataset provenance.",
  ),
  officialSupplement(
    "ecb-data-portal",
    "ECB Data Portal API",
    "https://data.ecb.europa.eu/help/api/overview",
    "https://data-api.ecb.europa.eu/service/data/",
    "EU",
    "policy",
    "api",
    ["macro", "rates", "liquidity", "inflation", "credit", "sdmx"],
    "candidate",
    "daily",
    "Official ECB SDMX API; preserve series keys, dimensions, units and observation periods.",
  ),
  officialSupplement(
    "nbs-china",
    "National Bureau of Statistics of China",
    "https://www.stats.gov.cn/english/",
    "https://www.stats.gov.cn/english/PressRelease/",
    "CN",
    "policy",
    "manual",
    ["macro", "gdp", "cpi", "ppi", "pmi", "industry"],
    "manual",
    "monthly",
    "Official releases remain manual and shadow-only until a stable compliant acquisition contract is verified.",
  ),
  officialSupplement(
    "pboc-statistics",
    "People's Bank of China Statistics",
    "https://www.pbc.gov.cn/en/3688006/3995557/index.html",
    "https://www.pbc.gov.cn/en/3688006/3995557/index.html",
    "CN",
    "policy",
    "manual",
    ["macro", "social-financing", "money-supply", "credit", "rates"],
    "manual",
    "monthly",
    "Official releases are retained as evidence links; no login, anti-bot or access control may be bypassed.",
  ),
  officialSupplement(
    "oecd-data-explorer",
    "OECD Data Explorer",
    "https://data-explorer.oecd.org/",
    "https://sdmx.oecd.org/public/rest/v1/data/",
    "GLOBAL",
    "policy",
    "api",
    ["macro", "leading-indicators", "productivity", "trade", "employment"],
    "candidate",
    "monthly",
    "Official OECD SDMX API; use normalized observations with attribution and dimension metadata.",
  ),
  officialSupplement(
    "world-bank-indicators",
    "World Bank Indicators",
    "https://data.worldbank.org/",
    "https://api.worldbank.org/v2/",
    "GLOBAL",
    "policy",
    "api",
    ["macro", "development", "energy", "digital-economy", "trade"],
    "candidate",
    "monthly",
    "Official World Bank API; public output is limited to normalized indicators and provenance.",
  ),
  officialSupplement(
    "eurostat-data",
    "Eurostat Data",
    "https://ec.europa.eu/eurostat/",
    "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/",
    "EU",
    "policy",
    "api",
    ["macro", "growth", "inflation", "industry", "labor"],
    "candidate",
    "monthly",
    "Official European statistics API; preserve dataset dimensions, flags and units.",
  ),
  officialSupplement(
    "sec-edgar",
    "SEC EDGAR APIs",
    "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    "https://data.sec.gov/submissions/",
    "US",
    "capital-business",
    "api",
    ["filing", "10-k", "10-q", "8-k", "20-f", "companyfacts", "xbrl"],
    "candidate",
    "daily",
    "Official SEC JSON APIs; use a declared fair-access user agent and publish links or normalized facts, not full filings.",
  ),
  officialSupplement(
    "cninfo",
    "CNINFO",
    "https://www.cninfo.com.cn/",
    "https://www.cninfo.com.cn/",
    "CN",
    "capital-business",
    "manual",
    ["filing", "a-share", "announcement", "listed-company"],
    "restricted",
    "daily",
    "Official disclosure entry retained for manual verification; automated acquisition and redistribution require compliance review.",
  ),
  officialSupplement(
    "sse-announcements",
    "Shanghai Stock Exchange Announcements",
    "https://english.sse.com.cn/markets/equities/announcements/",
    "https://english.sse.com.cn/markets/equities/announcements/",
    "CN",
    "capital-business",
    "manual",
    ["filing", "sse", "star-market", "announcement"],
    "manual",
    "daily",
    "Official announcement links are curated manually until robots and acquisition stability are verified.",
  ),
  officialSupplement(
    "szse-announcements",
    "Shenzhen Stock Exchange Announcements",
    "https://www.szse.cn/English/disclosure/listed/announcements/index.html",
    "https://www.szse.cn/English/disclosure/listed/announcements/index.html",
    "CN",
    "capital-business",
    "manual",
    ["filing", "szse", "chinext", "announcement"],
    "manual",
    "daily",
    "Official announcement links remain manual until robots, licensing and schema stability are verified.",
  ),
  officialSupplement(
    "nasdaq-data-link",
    "Nasdaq Data Link",
    "https://docs.data.nasdaq.com/",
    "https://docs.data.nasdaq.com/",
    "GLOBAL",
    "capital-business",
    "manual",
    ["market-data", "price", "valuation", "market-expectation"],
    "restricted",
    "daily",
    "Licensed market-data candidate; no values may enter public output until access and redistribution rights are verified.",
  ),
];

function officialSupplement(
  slug: string,
  name: string,
  homepageUrl: string,
  endpoint: string,
  region: string,
  category: Extract<SourceCategory, "policy" | "capital-business">,
  acquisition: Extract<Acquisition, "api" | "manual">,
  topics: string[],
  maintenanceStatus: Extract<
    CatalogSource["maintenanceStatus"],
    "candidate" | "manual" | "restricted"
  >,
  cadence: string,
  licenseNote: string,
): CatalogSource {
  return {
    slug,
    name,
    homepageUrl,
    endpoint,
    adapter: acquisition === "api" ? "generic-api" : "manual",
    tier: 1,
    role: category === "policy" ? "policy" : "primary",
    region,
    language: region === "CN" ? "zh-CN" : "en",
    authorityScore: authorityByTier[1],
    qualityScore: maintenanceStatus === "candidate" ? 82 : 72,
    enabled: false,
    lifecycleStatus: "shadow",
    category,
    acquisition,
    topics,
    maintenanceStatus,
    cadence,
    licenseNote,
    identityHosts: [new URL(homepageUrl).hostname],
  };
}

export function proposalToCatalogSource(proposal: SourceProposalCatalogEntry): CatalogSource {
  return {
    slug: proposal.slug,
    name: proposal.name,
    homepageUrl: proposal.homepageUrl,
    endpoint: proposal.endpoint,
    adapter:
      proposal.acquisition === "rss" || proposal.acquisition === "arxiv"
        ? "rss"
        : proposal.acquisition === "api"
          ? "generic-api"
          : proposal.acquisition === "github"
            ? "github-releases"
            : proposal.acquisition === "html"
              ? "web-scraper"
              : "manual",
    tier: 3 as const,
    role: proposal.role,
    region: proposal.region,
    language: proposal.language,
    authorityScore: authorityByTier[3],
    qualityScore: 35,
    enabled: false,
    lifecycleStatus: "draft" as const,
    category: proposal.category,
    acquisition: proposal.acquisition,
    topics: proposal.topics,
    maintenanceStatus: "proposal" as const,
    cadence: proposal.cadence,
    licenseNote: proposal.licenseNote,
    identityHosts: [new URL(proposal.homepageUrl).hostname],
    proposalIssueNumber: proposal.issueNumber,
    proposalEvidenceUrls: proposal.evidenceUrls,
  };
}

const proposalSources: CatalogSource[] =
  SourceProposalCatalogSchema.parse(sourceProposalRows).map(proposalToCatalogSource);

export const legacySourceCatalog: CatalogSource[] = [
  ...builtInSources,
  ...supplementalOfficialSources,
  ...sourceExpansionWave20260713,
  ...capitalEvidenceSources20260714,
  ...vendorEvidenceSources20260714,
  ...ecosystemEvidenceSources20260714,
  ...proposalSources,
];

export const sourceCatalog: EmbodiedCatalogSource[] = embodiedSourceCatalog;
